export const financialData = {
    "This Month": {
      totalRevenue: 12500,
      pendingPayments: 1800,
      failedPayments: 750,
      successfulPayments: 9950,
      transactions: [
        {
          id: "tx-001",
          studioName: "Creative Studio A",
          studioOwner: "John Doe",
          date: "2023-05-15",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
        {
          id: "tx-002",
          studioName: "Design Hub Pro",
          studioOwner: "Jane Smith",
          date: "2023-05-14",
          amount: 200,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 150, description: "Large studio with premium equipment" },
            { name: "Storage", cost: 25, description: "Additional storage space" },
            { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
          ],
        },
        {
          id: "tx-003",
          studioName: "Art Space Beta",
          studioOwner: "Bob Johnson",
          date: "2023-05-12",
          amount: 150,
          status: "Failed",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 120, description: "Standard studio space" },
            { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
          ],
        },
        {
          id: "tx-004",
          studioName: "Media Works",
          studioOwner: "Alice Williams",
          date: "2023-05-10",
          amount: 300,
          status: "Pending",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 200, description: "Large studio with premium equipment" },
            { name: "Equipment Rental", cost: 50, description: "Specialized equipment rental" },
            { name: "Technical Support", cost: 50, description: "Dedicated technical support" },
          ],
        },
        {
          id: "tx-005",
          studioName: "Creative Lab",
          studioOwner: "Charlie Brown",
          date: "2023-05-08",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
      ],
    },
    "Last Month": {
      totalRevenue: 11800,
      pendingPayments: 1200,
      failedPayments: 600,
      successfulPayments: 10000,
      transactions: [
        {
          id: "tx-101",
          studioName: "Creative Studio A",
          studioOwner: "John Doe",
          date: "2023-04-15",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
        {
          id: "tx-102",
          studioName: "Design Hub Pro",
          studioOwner: "Jane Smith",
          date: "2023-04-14",
          amount: 200,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 150, description: "Large studio with premium equipment" },
            { name: "Storage", cost: 25, description: "Additional storage space" },
            { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
          ],
        },
        {
          id: "tx-103",
          studioName: "Art Space Beta",
          studioOwner: "Bob Johnson",
          date: "2023-04-12",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 120, description: "Standard studio space" },
            { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
          ],
        },
      ],
    },
    "Last 3 Months": {
      totalRevenue: 35400,
      pendingPayments: 3600,
      failedPayments: 1800,
      successfulPayments: 30000,
      transactions: [
        {
          id: "tx-201",
          studioName: "Creative Studio A",
          studioOwner: "John Doe",
          date: "2023-03-15",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
        {
          id: "tx-202",
          studioName: "Design Hub Pro",
          studioOwner: "Jane Smith",
          date: "2023-02-14",
          amount: 200,
          status: "Failed",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 150, description: "Large studio with premium equipment" },
            { name: "Storage", cost: 25, description: "Additional storage space" },
            { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
          ],
        },
        {
          id: "tx-203",
          studioName: "Art Space Beta",
          studioOwner: "Bob Johnson",
          date: "2023-01-12",
          amount: 150,
          status: "Pending",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 120, description: "Standard studio space" },
            { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
          ],
        },
      ],
    },
    "Last 6 Months": {
      totalRevenue: 70800,
      pendingPayments: 7200,
      failedPayments: 3600,
      successfulPayments: 60000,
      transactions: [
        {
          id: "tx-301",
          studioName: "Creative Studio A",
          studioOwner: "John Doe",
          date: "2022-12-15",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
        {
          id: "tx-302",
          studioName: "Design Hub Pro",
          studioOwner: "Jane Smith",
          date: "2022-11-14",
          amount: 200,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 150, description: "Large studio with premium equipment" },
            { name: "Storage", cost: 25, description: "Additional storage space" },
            { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
          ],
        },
        {
          id: "tx-303",
          studioName: "Art Space Beta",
          studioOwner: "Bob Johnson",
          date: "2022-10-12",
          amount: 150,
          status: "Failed",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 120, description: "Standard studio space" },
            { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
          ],
        },
      ],
    },
    "This Year": {
      totalRevenue: 141600,
      pendingPayments: 14400,
      failedPayments: 7200,
      successfulPayments: 120000,
      transactions: [
        {
          id: "tx-401",
          studioName: "Creative Studio A",
          studioOwner: "John Doe",
          date: "2023-01-15",
          amount: 150,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 100, description: "Monthly studio space rental" },
            { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
            { name: "Utilities", cost: 20, description: "Electricity and internet" },
          ],
        },
        {
          id: "tx-402",
          studioName: "Design Hub Pro",
          studioOwner: "Jane Smith",
          date: "2023-02-14",
          amount: 200,
          status: "Successful",
          type: "Monthly Payment",
          services: [
            { name: "Premium Studio", cost: 150, description: "Large studio with premium equipment" },
            { name: "Storage", cost: 25, description: "Additional storage space" },
            { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
          ],
        },
        {
          id: "tx-403",
          studioName: "Art Space Beta",
          studioOwner: "Bob Johnson",
          date: "2023-03-12",
          amount: 150,
          status: "Pending",
          type: "Monthly Payment",
          services: [
            { name: "Studio Rental", cost: 120, description: "Standard studio space" },
            { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
          ],
        },
      ],
    },
  }