export const studioMembersData = {
    1: [
        {
            id: 1,
            firstName: "John",
            lastName: "Doe",
            email: "john@example.com",
            phone: "+49123456789",
            street: "Hauptstraße 123",
            zipCode: "10115",
            city: "Berlin",
            dateOfBirth: "1990-05-15",
            about: "Regular gym member who enjoys weightlifting and cardio workouts.",
            note: "Prefers evening workout sessions",
            noteStartDate: "2023-01-15",
            noteEndDate: "2023-12-31",
            noteImportance: "unimportant",
            contractStart: "2023-01-15",
            contractEnd: "2024-01-15",
            membershipType: "Premium",
            joinDate: "2023-01-15",
            status: "active",
            image: "/default-avatar.avif",
        },
        // ... other members
    ],
    2: [
        {
            id: 4,
            firstName: "Sarah",
            lastName: "Wilson",
            email: "sarah@example.com",
            phone: "+49111222333",
            street: "Alexanderplatz 12",
            zipCode: "10178",
            city: "Berlin",
            dateOfBirth: "1988-04-17",
            about: "Dance instructor and fitness enthusiast. Specializes in Zumba and aerobics.",
            note: "Allergic to latex - use alternative equipment",
            noteStartDate: "2023-01-05",
            noteEndDate: "2024-01-05",
            noteImportance: "important",
            contractStart: "2023-01-05",
            contractEnd: "2024-01-05",
            membershipType: "Basic",
            joinDate: "2023-01-05",
            status: "active",
            image: "/default-avatar.avif",
        },
        // ... other members
    ],
};

export const studioStaffData = {
    1: [
        {
            id: 1,
            firstName: "Natalia",
            lastName: "Brown",
            role: "Telephone operator",
            email: "natalia.brown@example.com",
            phone: "+1234567890",
            description: "Experienced telephone operator with excellent communication skills.",
            img: null,
            userId: "natalia.telephone-operator",
            username: "natalia.brown",
            street: "123 Main St",
            zipCode: "12345",
            city: "Anytown",
            vacationEntitlement: 30,
            birthday: "1990-05-10",
        },
    ],
    2: [
        {
            id: 2,
            firstName: "Natalia",
            lastName: "Brown",
            role: "Telephone operator",
            email: "natalia.brown@example.com",
            phone: "+1234567890",
            description: "Experienced telephone operator with excellent communication skills.",
            img: null,
            userId: "natalia.telephone-operator",
            username: "natalia.brown",
            street: "123 Main St",
            zipCode: "12345",
            city: "Anytown",
            vacationEntitlement: 30,
            birthday: "1990-05-10",
        },
    ],
}

export const studioLeadData = {
    1: [
        {
              id: 1,
              firstName: "John",
              surname: "Smith",
              email: "john.smith@example.com",
              phoneNumber: "+1234567890",
              trialPeriod: "Trial Period",
              hasTrialTraining: true,
              avatar: "",
              source: "hardcoded",
              status: "active",
              about: "Software Engineer",
              createdAt: "2025-01-15T10:30:00Z",
              specialNote: {
                text: "Interested in personal training sessions twice a week.",
                isImportant: false,
                startDate: "2025-01-15",
                endDate: "2025-03-15",
              },
            },
    ],
    2: [
        {
              id: 2,
              firstName: "John",
              surname: "Smith",
              email: "john.smith@example.com",
              phoneNumber: "+1234567890",
              trialPeriod: "Trial Period",
              hasTrialTraining: true,
              avatar: "",
              source: "hardcoded",
              status: "active",
              about: "Software Engineer",
              createdAt: "2025-01-15T10:30:00Z",
              specialNote: {
                text: "Interested in personal training sessions twice a week.",
                isImportant: false,
                startDate: "2025-01-15",
                endDate: "2025-03-15",
              },
            },
    ],
}

export const studioContractsData = {
    1: [
        {
            id: 1,
            memberName: "John Doe",
            duration: "12 months",
            startDate: "2023-01-15",
            endDate: "2024-01-15",
            status: "active",
            files: ["contract_john.pdf", "terms_john.pdf"],
        },
        {
            id: 2,
            memberName: "Jane Smith",
            duration: "6 months",
            startDate: "2023-02-20",
            endDate: "2023-08-20",
            status: "paused",
            files: ["contract_jane.pdf"],
        },
        {
            id: 3,
            memberName: "Mike Johnson",
            duration: "12 months",
            startDate: "2023-03-10",
            endDate: "2024-03-10",
            status: "inactive",
            files: ["contract_mike.pdf", "cancellation_mike.pdf"],
        },
    ],
    2: [
        {
            id: 4,
            memberName: "Sarah Wilson",
            duration: "24 months",
            startDate: "2023-01-05",
            endDate: "2025-01-05",
            status: "active",
            files: ["contract_sarah.pdf"],
        },
        {
            id: 5,
            memberName: "Tom Brown",
            duration: "12 months",
            startDate: "2023-02-15",
            endDate: "2024-02-15",
            status: "active",
            files: ["contract_tom.pdf", "addendum_tom.pdf"],
        },
    ],
}

export const studioFinanceData = {
    1: {
        month: { totalRevenue: 45000, successfulPayments: 42000, pendingPayments: 2500, failedPayments: 500 },
        quarter: { totalRevenue: 135000, successfulPayments: 128000, pendingPayments: 5500, failedPayments: 1500 },
        year: { totalRevenue: 540000, successfulPayments: 515000, pendingPayments: 18000, failedPayments: 7000 },
        overall: { totalRevenue: 640000, successfulPayments: 215000, pendingPayments: 28000, failedPayments: 4000 },

    },
    2: {
        month: { totalRevenue: 32000, successfulPayments: 30000, pendingPayments: 1500, failedPayments: 500 },
        quarter: { totalRevenue: 96000, successfulPayments: 91000, pendingPayments: 3500, failedPayments: 1500 },
        year: { totalRevenue: 384000, successfulPayments: 365000, pendingPayments: 12000, failedPayments: 7000 },
        overall: { totalRevenue: 984000, successfulPayments: 165000, pendingPayments: 42000, failedPayments: 9000 },
    },
}

export const studioStatsData = {
    1: { members: 120, trainers: 8, classes: 15, leads: 4, contracts: 6 },
    2: { members: 85, trainers: 5, classes: 10, leads: 4, contracts: 6 },
}

export const FranchiseData = [
    {
        id: 1,
        name: "FitChain Franchise Group",
        email: "info@fitchain.com",
        phone: "+49123456789",
        street: "Franchise Straße 1",
        zipCode: "10115",
        city: "Berlin",
        website: "www.fitchain.com",
        about: "Leading fitness franchise with multiple studio locations across Germany.",
        ownerName: "Klaus Weber",
        ownerFirstName: "Klaus",
        ownerLastName: "Weber",
        taxId: "DE111222333",
        loginEmail: "admin@fitchain.com",
        loginPassword: "franchise123",
        createdDate: "2023-01-15",
        studioCount: 2,
    }
];


export const financialData = {
  "This Month": {
    totalRevenue: 12500,
    pendingPayments: 1800,
    failedPayments: 750,
    successfulPayments: 9950,
    transactions: [
      {
        id: "tx-001",
        memberName: "John Doe",
        date: "2023-05-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-002",
        memberName: "Jane Smith",
        date: "2023-05-14",
        amount: 200,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-003",
        memberName: "Bob Johnson",
        date: "2023-05-12",
        amount: 150,
        status: "Failed",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 120, description: "Monthly membership fee" },
          { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
        ],
      },
      {
        id: "tx-004",
        memberName: "Alice Williams",
        date: "2023-05-10",
        amount: 300,
        status: "Pending",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 200, description: "Premium membership with extra benefits" },
          { name: "Equipment Rental", cost: 50, description: "Specialized equipment rental" },
          { name: "Technical Support", cost: 50, description: "Dedicated technical support" },
        ],
      },
      {
        id: "tx-005",
        memberName: "Charlie Brown",
        date: "2023-05-08",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
    ],
  },
  "Last Month": {
    totalRevenue: 11800,
    pendingPayments: 1200,
    failedPayments: 600,
    successfulPayments: 10000,
    transactions: [
      {
        id: "tx-101",
        memberName: "John Doe",
        date: "2023-04-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-102",
        memberName: "Jane Smith",
        date: "2023-04-14",
        amount: 200,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-103",
        memberName: "Bob Johnson",
        date: "2023-04-12",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 120, description: "Monthly membership fee" },
          { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
        ],
      },
    ],
  },
  "Last 3 Months": {
    totalRevenue: 35400,
    pendingPayments: 3600,
    failedPayments: 1800,
    successfulPayments: 30000,
    transactions: [
      {
        id: "tx-201",
        memberName: "John Doe",
        date: "2023-03-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-202",
        memberName: "Jane Smith",
        date: "2023-02-14",
        amount: 200,
        status: "Failed",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-203",
        memberName: "Bob Johnson",
        date: "2023-01-12",
        amount: 150,
        status: "Pending",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 120, description: "Monthly membership fee" },
          { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
        ],
      },
    ],
  },
  "Last 6 Months": {
    totalRevenue: 70800,
    pendingPayments: 7200,
    failedPayments: 3600,
    successfulPayments: 60000,
    transactions: [
      {
        id: "tx-301",
        memberName: "John Doe",
        date: "2022-12-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-302",
        memberName: "Jane Smith",
        date: "2022-11-14",
        amount: 200,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-303",
        memberName: "Bob Johnson",
        date: "2022-10-12",
        amount: 150,
        status: "Failed",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 120, description: "Monthly membership fee" },
          { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
        ],
      },
    ],
  },
  "This Year": {
    totalRevenue: 141600,
    pendingPayments: 14400,
    failedPayments: 7200,
    successfulPayments: 120000,
    transactions: [
      {
        id: "tx-401",
        memberName: "John Doe",
        date: "2023-01-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-402",
        memberName: "Jane Smith",
        date: "2023-02-14",
        amount: 200,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-403",
        memberName: "Bob Johnson",
        date: "2023-03-12",
        amount: 150,
        status: "Pending",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 120, description: "Monthly membership fee" },
          { name: "Cleaning Service", cost: 30, description: "Weekly cleaning service" },
        ],
      },
    ],
  },
  Overall: {
    totalRevenue: 284100,
    pendingPayments: 28800,
    failedPayments: 14400,
    successfulPayments: 240900,
    transactions: [
      // Combined transactions from all periods
      {
        id: "tx-001",
        memberName: "John Doe",
        date: "2023-05-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-002",
        memberName: "Jane Smith",
        date: "2023-05-14",
        amount: 200,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Premium Membership", cost: 150, description: "Premium membership with extra benefits" },
          { name: "Storage", cost: 25, description: "Additional storage space" },
          { name: "Support Services", cost: 25, description: "Technical support and maintenance" },
        ],
      },
      {
        id: "tx-101",
        memberName: "John Doe",
        date: "2023-04-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
      {
        id: "tx-201",
        memberName: "John Doe",
        date: "2023-03-15",
        amount: 150,
        status: "Successful",
        type: "Monthly Payment",
        services: [
          { name: "Basic Membership", cost: 100, description: "Monthly membership fee" },
          { name: "Equipment Usage", cost: 30, description: "Professional equipment access" },
          { name: "Utilities", cost: 20, description: "Electricity and internet" },
        ],
      },
    ],
  },
}


export const appointmentsData = [
  {
    id: 1,
    name: "Yolanda",
    time: "09:00 - 09:30",
    date: "Mon | 07-02-2025",
    color: "bg-[#4169E1]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Strength Training",
    specialNote: { text: "Prefers morning sessions", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: true,
  },
  {
    id: 2,
    name: "Denis",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 3,
    name: "Nicole",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 4,
    name: "Melanie",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 5,
    name: "Angela",
    time: "09:30 - 10:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#ef4444]",
    startTime: "09:30",
    endTime: "10:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 6,
    name: "Kristina",
    time: "09:30 - 10:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "09:30",
    endTime: "10:00",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 7,
    name: "Melanie",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 8,
    name: "Annett",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#10b981]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 9,
    name: "Justin",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 10,
    name: "Michel",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 11,
    name: "Colin",
    time: "11:30 - 12:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "11:30",
    endTime: "12:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 12,
    name: "Yvonne",
    time: "11:30 - 12:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "11:30",
    endTime: "12:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 13,
    name: "Jennifer",
    time: "12:00 - 12:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#ef4444]",
    startTime: "12:00",
    endTime: "12:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 14,
    name: "Michael",
    time: "12:00 - 12:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "12:00",
    endTime: "12:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 15,
    name: "Furkan",
    time: "13:00 - 13:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "13:00",
    endTime: "13:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 16,
    name: "Heike",
    time: "12:30 - 13:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "12:30",
    endTime: "13:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 17,
    name: "Sandy",
    time: "12:30 - 13:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "12:30",
    endTime: "13:00",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 18,
    name: "Ann-Kathrin",
    time: "13:00 - 13:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "13:00",
    endTime: "13:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 19,
    name: "Katharina",
    time: "13:00 - 14:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "13:00",
    endTime: "14:00",
    type: "Probetraining",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: true,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 20,
    name: "Joanna",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 21,
    name: "Iris",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 22,
    name: "Jürgen",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 23,
    name: "Corinna",
    time: "14:30 - 15:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:30",
    endTime: "15:00",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 24,
    name: "Anzi",
    time: "14:30 - 15:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:30",
    endTime: "15:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 25,
    name: "Gabriela",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 26,
    name: "Stefanie",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 27,
    name: "Gabriele",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 28,
    name: "Aylin",
    time: "15:30 - 16:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "15:30",
    endTime: "16:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 29,
    name: "Conrad",
    time: "15:30 - 16:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "15:30",
    endTime: "16:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 30,
    name: "Michael",
    time: "16:00 - 16:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:00",
    endTime: "16:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 31,
    name: "Ralf",
    time: "16:00 - 16:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:00",
    endTime: "16:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 32,
    name: "Sarah",
    time: "16:30 - 17:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "16:30",
    endTime: "17:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 33,
    name: "Sabrina",
    time: "16:30 - 17:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:30",
    endTime: "17:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 34,
    name: "Nadine",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 35,
    name: "Jana",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 36,
    name: "Andreas",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 37,
    name: "Nicole",
    time: "17:30 - 18:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "17:30",
    endTime: "18:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 38,
    name: "Irene",
    time: "17:30 - 18:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "17:30",
    endTime: "18:00",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 39,
    name: "Past User 1",
    time: "08:00 - 08:30",
    date: "Sun | 02-02-2025", // Example past date
    color: "bg-[#4169E1]",
    startTime: "08:00",
    endTime: "08:30",
    type: "Strength Training",
    specialNote: { text: "Completed session", startDate: null, endDate: null, isImportant: false },
    status: "completed",
    isTrial: false,
    isCancelled: false,
    isPast: true, // Marked as past
  },
  {
    id: 40,
    name: "Past User 2",
    time: "09:00 - 09:30",
    date: "Sun | 02-02-2025", // Example past date
    color: "bg-[#22c55e]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Cardio",
    specialNote: { text: "Completed session", startDate: null, endDate: null, isImportant: false },
    status: "completed",
    isTrial: false,
    isCancelled: false,
    isPast: true, // Marked as past
  },
  {
    id: 41,
    name: "Cancelled User 1",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025", // Example current/future date for cancellation
    color: "bg-[#f97316]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Yoga",
    specialNote: { text: "Client cancelled due to illness", startDate: null, endDate: null, isImportant: true },
    status: "cancelled",
    isTrial: false,
    isCancelled: true, // Marked as cancelled
    isPast: false,
  },
  {
    id: 42,
    name: "Cancelled User 2",
    time: "11:00 - 11:30",
    date: "Tue | 04-02-2025", // Example current/future date for cancellation
    color: "bg-[#8b5cf6]",
    startTime: "11:00",
    endTime: "11:30",
    type: "Personal Training",
    specialNote: { text: "Trainer unavailable", startDate: null, endDate: null, isImportant: true },
    status: "cancelled",
    isTrial: false,
    isCancelled: true, // Marked as cancelled
    isPast: false,
  },
  {
    id: 43,
    name: "Blocked Slot",
    time: "14:00 - 15:00",
    date: "Wed | 05-02-2025",
    color: "bg-[#FF4D4F]", // Red color for blocked slots
    startTime: "14:00",
    endTime: "15:00",
    type: "Blocked Time",
    specialNote: { text: "Facility maintenance", startDate: null, endDate: null, isImportant: true },
    status: "blocked",
    isTrial: false,
    isCancelled: false,
    isPast: false,
    isBlocked: true, // Explicitly mark as blocked
  },
  // New future appointments to ensure more colorful events are visible by default
  {
    id: 44,
    name: "Alice",
    time: "09:00 - 09:45",
    date: "Mon | 08-05-2025",
    color: "bg-[#3F74FF]",
    startTime: "09:00",
    endTime: "09:45",
    type: "Cardio",
    specialNote: { text: "First session with new trainer", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 45,
    name: "Bob",
    time: "10:00 - 11:00",
    date: "Tue | 08-06-2025",
    color: "bg-[#FF843E]",
    startTime: "10:00",
    endTime: "11:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 46,
    name: "Charlie",
    time: "11:30 - 12:30",
    date: "Wed | 08-07-2025",
    color: "bg-[#50C878]",
    startTime: "11:30",
    endTime: "12:30",
    type: "Yoga",
    specialNote: { text: "Advanced poses focus", startDate: null, endDate: null, isImportant: true },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 47,
    name: "Diana",
    time: "14:00 - 14:30",
    date: "Thu | 08-08-2025",
    color: "bg-[#8b5cf6]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 48,
    name: "Eve",
    time: "15:00 - 15:30",
    date: "Fri | 08-09-2025",
    color: "bg-[#06b6d4]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Cardio",
    specialNote: { text: "Treadmill interval training", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 49,
    name: "Frank",
    time: "16:00 - 17:00",
    date: "Mon | 08-12-2025",
    color: "bg-[#f59e0b]",
    startTime: "16:00",
    endTime: "17:00",
    type: "Strength Training",
    specialNote: { text: "Upper body focus", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 50,
    name: "Grace",
    time: "17:30 - 18:30",
    date: "Tue | 08-13-2025",
    color: "bg-[#ef4444]",
    startTime: "17:30",
    endTime: "18:30",
    type: "Yoga",
    specialNote: { text: "Restorative yoga", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
]

export const membersData = [
  {
    id: 1,
    firstName: "Yolanda",
    lastName: "Martinez",
    title: "Yolanda",
    email: "yolanda@example.com",
    phone: "+1234567890",
    street: "123 Main St",
    zipCode: "12345",
    city: "New York",
    image: null,
    isActive: true,
    note: "Prefers morning sessions",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1990-05-15",
    about: "Fitness enthusiast with a passion for strength training.",
    joinDate: "2022-03-01",
    contractStart: "2022-03-01",
    contractEnd: "2025-03-01",
  },
  {
    id: 2,
    firstName: "Denis",
    lastName: "Johnson",
    title: "Denis",
    email: "denis@example.com",
    phone: "+1234567891",
    street: "456 Oak St",
    zipCode: "67890",
    city: "Los Angeles",
    image: null,
    isActive: true,
    note: "Loves cardio workouts",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1985-08-22",
    about: "Marathon runner and cardio specialist.",
    joinDate: "2021-11-15",
    contractStart: "2021-11-15",
    contractEnd: "2025-04-15",
  },
  {
    id: 3,
    firstName: "Nicole",
    lastName: "Smith",
    title: "Nicole",
    email: "nicole@example.com",
    phone: "+1234567892",
    street: "789 Pine St",
    zipCode: "54321",
    city: "Chicago",
    image: null,
    isActive: true,
    note: "Yoga instructor background",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1992-03-10",
    about: "Certified yoga instructor with 5 years experience.",
    joinDate: "2022-01-01",
    contractStart: "2022-01-01",
    contractEnd: "2025-01-01",
  },
  {
    id: 4,
    firstName: "Melanie",
    lastName: "Brown",
    title: "Melanie",
    email: "melanie@example.com",
    phone: "+1234567893",
    street: "321 Elm St",
    zipCode: "98765",
    city: "Miami",
    image: null,
    isActive: true,
    note: "Personal training focused",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-07-25",
    about: "Dedicated to personal fitness goals.",
    joinDate: "2022-06-01",
    contractStart: "2022-06-01",
    contractEnd: "2025-06-01",
  },
  {
    id: 5,
    firstName: "Angela",
    lastName: "Davis",
    title: "Angela",
    email: "angela@example.com",
    phone: "+1234567894",
    street: "654 Maple Ave",
    zipCode: "13579",
    city: "Seattle",
    image: null,
    isActive: true,
    note: "Strength training enthusiast",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1991-12-05",
    about: "Powerlifter and strength training coach.",
    joinDate: "2022-02-15",
    contractStart: "2022-02-15",
    contractEnd: "2025-02-15",
  },
  {
    id: 6,
    firstName: "Kristina",
    lastName: "Wilson",
    title: "Kristina",
    email: "kristina@example.com",
    phone: "+1234567895",
    street: "987 Cedar Rd",
    zipCode: "24680",
    city: "Denver",
    image: null,
    isActive: true,
    note: "Cardio specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1989-04-18",
    about: "Cardio enthusiast and fitness model.",
    joinDate: "2022-04-01",
    contractStart: "2022-04-01",
    contractEnd: "2025-04-01",
  },
  {
    id: 7,
    firstName: "Annett",
    lastName: "Taylor",
    title: "Annett",
    email: "annett@example.com",
    phone: "+1234567896",
    street: "147 Birch St",
    zipCode: "36912",
    city: "Boston",
    image: null,
    isActive: true,
    note: "Personal training focused",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1987-09-30",
    about: "Personal trainer with nutrition background.",
    joinDate: "2022-05-01",
    contractStart: "2022-05-01",
    contractEnd: "2025-05-01",
  },
  {
    id: 8,
    firstName: "Justin",
    lastName: "Miller",
    title: "Justin",
    email: "justin@example.com",
    phone: "+1234567897",
    street: "258 Spruce Ave",
    zipCode: "47103",
    city: "Phoenix",
    image: null,
    isActive: true,
    note: "Strength training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1993-11-12",
    about: "Bodybuilder and strength athlete.",
    joinDate: "2022-07-01",
    contractStart: "2022-07-01",
    contractEnd: "2025-07-01",
  },
  {
    id: 9,
    firstName: "Michel",
    lastName: "Garcia",
    title: "Michel",
    email: "michel@example.com",
    phone: "+1234567898",
    street: "369 Willow Dr",
    zipCode: "58214",
    city: "Portland",
    image: null,
    isActive: true,
    note: "Cardio and endurance",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1986-02-28",
    about: "Endurance athlete and triathlete.",
    joinDate: "2022-08-01",
    contractStart: "2022-08-01",
    contractEnd: "2025-08-01",
  },
  {
    id: 10,
    firstName: "Colin",
    lastName: "Anderson",
    title: "Colin",
    email: "colin@example.com",
    phone: "+1234567899",
    street: "741 Poplar St",
    zipCode: "69325",
    city: "Austin",
    image: null,
    isActive: true,
    note: "Strength training specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1990-06-14",
    about: "Powerlifting competitor and coach.",
    joinDate: "2022-09-01",
    contractStart: "2022-09-01",
    contractEnd: "2025-09-01",
  },
  {
    id: 11,
    firstName: "Yvonne",
    lastName: "Thomas",
    title: "Yvonne",
    email: "yvonne@example.com",
    phone: "+1234567800",
    street: "852 Ash Ave",
    zipCode: "70436",
    city: "Nashville",
    image: null,
    isActive: true,
    note: "Yoga and flexibility",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1984-10-07",
    about: "Yoga instructor and flexibility coach.",
    joinDate: "2022-10-01",
    contractStart: "2022-10-01",
    contractEnd: "2025-10-01",
  },
  {
    id: 12,
    firstName: "Jennifer",
    lastName: "Jackson",
    title: "Jennifer",
    email: "jennifer@example.com",
    phone: "+1234567801",
    street: "963 Hickory Rd",
    zipCode: "81547",
    city: "San Diego",
    image: null,
    isActive: true,
    note: "Personal training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1991-01-20",
    about: "Certified personal trainer and nutritionist.",
    joinDate: "2022-11-01",
    contractStart: "2022-11-01",
    contractEnd: "2025-11-01",
  },
  {
    id: 13,
    firstName: "Michael",
    lastName: "White",
    title: "Michael",
    email: "michael@example.com",
    phone: "+1234567802",
    street: "174 Walnut St",
    zipCode: "92658",
    city: "Las Vegas",
    image: null,
    isActive: true,
    note: "Cardio enthusiast",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1987-05-03",
    about: "Marathon runner and cardio specialist.",
    joinDate: "2022-12-01",
    contractStart: "2022-12-01",
    contractEnd: "2025-12-01",
  },
  {
    id: 14,
    firstName: "Furkan",
    lastName: "Ozkan",
    title: "Furkan",
    email: "furkan@example.com",
    phone: "+1234567803",
    street: "285 Cherry Ave",
    zipCode: "03769",
    city: "Salt Lake City",
    image: null,
    isActive: true,
    note: "Strength training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1994-08-16",
    about: "Bodybuilder and fitness enthusiast.",
    joinDate: "2023-01-01",
    contractStart: "2023-01-01",
    contractEnd: "2026-01-01",
  },
  {
    id: 15,
    firstName: "Heike",
    lastName: "Mueller",
    title: "Heike",
    email: "heike@example.com",
    phone: "+1234567804",
    street: "396 Peach Dr",
    zipCode: "14870",
    city: "Minneapolis",
    image: null,
    isActive: true,
    note: "Yoga specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1983-12-29",
    about: "Advanced yoga practitioner and teacher.",
    joinDate: "2023-02-01",
    contractStart: "2023-02-01",
    contractEnd: "2026-02-01",
  }, // Add more members as needed for other appointment names
  {
    id: 16,
    firstName: "Sandy",
    lastName: "Rodriguez",
    title: "Sandy",
    email: "sandy@example.com",
    phone: "+1234567805",
    street: "507 Orange St",
    zipCode: "25981",
    city: "Tampa",
    image: null,
    isActive: true,
    note: "Personal training specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1989-03-22",
    about: "Certified personal trainer with sports background.",
    joinDate: "2023-03-01",
    contractStart: "2023-03-01",
    contractEnd: "2026-03-01",
  },
  {
    id: 17,
    firstName: "Ann-Kathrin",
    lastName: "Schmidt",
    title: "Ann-Kathrin",
    email: "ann-kathrin@example.com",
    phone: "+1234567806",
    street: "618 Lemon Ave",
    zipCode: "36092",
    city: "Orlando",
    image: null,
    isActive: true,
    note: "Cardio and fitness",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1992-07-08",
    about: "Fitness instructor and cardio specialist.",
    joinDate: "2023-04-01",
    contractStart: "2023-04-01",
    contractEnd: "2026-04-01",
  },
  {
    id: 18,
    firstName: "Katharina",
    lastName: "Weber",
    title: "Katharina",
    email: "katharina@example.com",
    phone: "+1234567807",
    street: "729 Grape Dr",
    zipCode: "47103",
    city: "Jacksonville",
    image: null,
    isActive: true,
    note: "Trial training participant",
    noteStartDate: "2023-01-01",
    noteNoteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1995-11-15",
    about: "New member interested in comprehensive fitness program.",
    joinDate: "2023-05-01",
    contractStart: "2023-05-01",
    contractEnd: "2026-05-01",
  },
  // New members for the new future appointments
  {
    id: 19,
    firstName: "Alice",
    lastName: "Wonder",
    title: "Alice",
    email: "alice@example.com",
    phone: "+1234567808",
    street: "101 Wonderland Rd",
    zipCode: "10101",
    city: "Fairyland",
    image: null,
    isActive: true,
    note: "Loves morning workouts",
    noteStartDate: "2024-01-01",
    noteEndDate: "2025-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1998-01-01",
    about: "Enthusiastic about fitness and healthy living.",
    joinDate: "2024-01-01",
    contractStart: "2024-01-01",
    contractEnd: "2027-01-01",
  },
  {
    id: 20,
    firstName: "Bob",
    lastName: "Builder",
    title: "Bob",
    email: "bob@example.com",
    phone: "+1234567809",
    street: "202 Construction St",
    zipCode: "20202",
    city: "Buildville",
    image: null,
    isActive: true,
    note: "Focus on strength gains",
    noteStartDate: "2024-02-01",
    noteEndDate: "2026-02-28",
    noteImportance: "important",
    dateOfBirth: "1980-02-02",
    about: "Dedicated to building muscle and endurance.",
    joinDate: "2024-02-01",
    contractStart: "2024-02-01",
    contractEnd: "2027-02-01",
  },
  {
    id: 21,
    firstName: "Charlie",
    lastName: "Chaplin",
    title: "Charlie",
    email: "charlie@example.com",
    phone: "+1234567810",
    street: "303 Silent Film Ave",
    zipCode: "30303",
    city: "Hollywood",
    image: null,
    isActive: true,
    note: "Prefers evening yoga",
    noteStartDate: "2024-03-01",
    noteEndDate: "2025-03-31",
    noteImportance: "unimportant",
    dateOfBirth: "1995-03-03",
    about: "Enjoys flexibility and mindfulness through yoga.",
    joinDate: "2024-03-01",
    contractStart: "2024-03-01",
    contractEnd: "2027-03-01",
  },
  {
    id: 22,
    firstName: "Diana",
    lastName: "Prince",
    title: "Diana",
    email: "diana@example.com",
    phone: "+1234567811",
    street: "404 Amazonian Way",
    zipCode: "40404",
    city: "Themyscira",
    image: null,
    isActive: true,
    note: "Personal training for combat readiness",
    noteStartDate: "2024-04-01",
    noteEndDate: "2026-04-30",
    noteImportance: "important",
    dateOfBirth: "1984-04-04",
    about: "Seeking to maintain peak physical condition.",
    joinDate: "2024-04-01",
    contractStart: "2024-04-01",
    contractEnd: "2027-04-01",
  },
  {
    id: 23,
    firstName: "Eve",
    lastName: "Adams",
    title: "Eve",
    email: "eve@example.com",
    phone: "+1234567812",
    street: "505 Garden of Eden",
    zipCode: "50505",
    city: "Paradise",
    image: null,
    isActive: true,
    note: "Loves outdoor cardio",
    noteStartDate: "2024-05-01",
    noteEndDate: "2025-05-31",
    noteImportance: "unimportant",
    dateOfBirth: "1992-05-05",
    about: "Enjoys running and high-intensity cardio.",
    joinDate: "2024-05-01",
    contractStart: "2024-05-01",
    contractEnd: "2027-05-01",
  },
  {
    id: 24,
    firstName: "Frank",
    lastName: "Sinatra",
    title: "Frank",
    email: "frank@example.com",
    phone: "+1234567813",
    street: "606 Crooner's Lane",
    zipCode: "60606",
    city: "Las Vegas",
    image: null,
    isActive: true,
    note: "Strength training for stage presence",
    noteStartDate: "2024-06-01",
    noteEndDate: "2026-06-30",
    noteImportance: "important",
    dateOfBirth: "1970-06-06",
    about: "Keeping fit for performances.",
    joinDate: "2024-06-01",
    contractStart: "2024-06-01",
    contractEnd: "2027-06-01",
  },
  {
    id: 25,
    firstName: "Grace",
    lastName: "Kelly",
    title: "Grace",
    email: "grace@example.com",
    phone: "+1234567814",
    street: "707 Royal Palace",
    zipCode: "70707",
    city: "Monaco",
    image: null,
    isActive: true,
    note: "Gentle yoga for relaxation",
    noteStartDate: "2024-07-01",
    noteEndDate: "2025-07-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-07-07",
    about: "Seeks balance and tranquility through yoga.",
    joinDate: "2024-07-01",
    contractStart: "2024-07-01",
    contractEnd: "2027-07-01",
  },
]


export const studioHistoryMainData = {
  1: {
    general: [
      {
        id: 1,
        date: "2025-02-01",
        action: "Studio name updated",
        details: "Changed from 'Old Studio' to 'New Studio Elite'",
        user: "Admin",
      },
    ],
    contract: [
      {
        id: 1,
        date: "2025-01-18",
        action: "New Contract Signed",
        details: "3-year partnership renewal with vendor",
        user: "Legal Team",
      },
      {
        id: 2,
        date: "2025-02-10",
        action: "Contract Terminated",
        details: "Terminated contract with old cleaning service",
        user: "Admin",
      },
    ],
    finance: [
      {
        id: 1,
        date: "2025-01-10",
        type: "Expense",
        amount: "$500",
        description: "Equipment repair cost",
        status: "completed",
      },
      {
        id: 2,
        date: "2025-01-05",
        type: "Revenue",
        amount: "$1500",
        description: "Membership sales",
        status: "completed",
      },
    ],
    tickets: [
      {
        id: 1,
        date: "2025-01-12",
        title: "AC not cooling properly",
        description: "Reported by staff, resolved next day",
        status: "Resolved",
      },
      {
        id: 2,
        date: "2025-01-20",
        title: "Treadmill malfunction",
        description: "Motor issue under service warranty",
        status: "In Progress",
      },
    ],
  },
  2: {
    general: [],
    contract: [],
    finance: [],
    tickets: [],
  },
};

export const studioDataNew = [
  {
    id: 1,
    name: "Fitness for Life GmbH",
    email: "info@fitnessforlife.de",
    phone: "+49123456789",
    street: "Hauptstraße 123",
    zipCode: "10115",
    city: "Berlin",
    country: "Germany",
    iban: "DE89 3704 0044 0532 0130 00",
    taxId: "DE123456789",
    image: null,
    isActive: true,
    note: "Premium partner, VIP treatment",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    website: "www.fitnessforlife.de",
    about: "Premium fitness studio with state-of-the-art equipment and certified trainers.",
    joinDate: "2022-03-01",
    contractStart: "2022-03-01",
    contractEnd: "2023-03-01",
    ownerName: "Hans Mueller",
    franchiseId: 1,
    openingHours: {
      monday: "6:00 - 22:00",
      tuesday: "6:00 - 22:00",
      wednesday: "6:00 - 22:00",
      thursday: "6:00 - 22:00",
      friday: "6:00 - 22:00",
      saturday: "8:00 - 20:00",
      sunday: "10:00 - 18:00",
    },
    closingDays: "Christmas Day, New Year's Day",
  },
  {
    id: 2,
    name: "PowerGym AG",
    email: "contact@powergym.com",
    phone: "+49987654321",
    street: "Friedrichstraße 45",
    zipCode: "20354",
    city: "Hamburg",
    country: "Germany",
    iban: "DE12 5001 0517 0648 4898 90",
    taxId: "DE987654321",
    image: null,
    isActive: false,
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    website: "www.powergym.com",
    about: "Specialized in strength training and bodybuilding with professional coaching.",
    joinDate: "2021-11-15",
    contractStart: "2021-11-15",
    contractEnd: "2024-04-15",
    ownerName: "Maria Schmidt",
    franchiseId: 1,
    openingHours: {
      monday: "5:00 - 23:00",
      tuesday: "5:00 - 23:00",
      wednesday: "5:00 - 23:00",
      thursday: "5:00 - 23:00",
      friday: "5:00 - 23:00",
      saturday: "7:00 - 21:00",
      sunday: "9:00 - 19:00",
    },
    closingDays: "Easter Sunday, Christmas Day",
  },
  {
    id: 3,
    name: "FlexFit Studio",
    email: "info@flexfit.com",
    phone: "+49555123456",
    street: "Sportstraße 10",
    zipCode: "80331",
    city: "Munich",
    country: "Germany",
    iban: "DE89 7005 0000 0000 1234 56",
    taxId: "DE555123456",
    image: null,
    isActive: true,
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    website: "www.flexfit.com",
    about: "Modern fitness studio focusing on flexibility and wellness.",
    joinDate: "2023-01-15",
    contractStart: "2023-01-15",
    contractEnd: "2024-01-15",
    ownerName: "Anna Weber",
    franchiseId: null,
    openingHours: {
      monday: "7:00 - 21:00",
      tuesday: "7:00 - 21:00",
      wednesday: "7:00 - 21:00",
      thursday: "7:00 - 21:00",
      friday: "7:00 - 21:00",
      saturday: "9:00 - 18:00",
      sunday: "Closed",
    },
    closingDays: "Public holidays",
  },
  {
    id: 4,
    name: "StrengthZone",
    email: "contact@strengthzone.de",
    phone: "+49666789012",
    street: "Kraftstraße 25",
    zipCode: "50667",
    city: "Cologne",
    country: "Germany",
    iban: "DE44 5001 0517 5407 3249 31",
    taxId: "DE666789012",
    image: null,
    isActive: true,
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    website: "www.strengthzone.de",
    about: "Specialized in strength training and powerlifting.",
    joinDate: "2023-02-01",
    contractStart: "2023-02-01",
    contractEnd: "2024-02-01",
    ownerName: "Michael Klein",
    franchiseId: null,
    openingHours: {
      monday: "6:00 - 22:00",
      tuesday: "6:00 - 22:00",
      wednesday: "6:00 - 22:00",
      thursday: "6:00 - 22:00",
      friday: "6:00 - 22:00",
      saturday: "8:00 - 20:00",
      sunday: "10:00 - 16:00",
    },
    closingDays: "Christmas Eve, Christmas Day, New Year's Day",
  },
]


export const studiomemberHistoryNew = {
  1: {
      general: [
          {
              id: 1,
              date: "2025-01-15",
              action: "Email updated",
              details: "Changed from old@email.com to jennifer@example.com",
              user: "Admin",
          },
          { id: 2, date: "2025-01-10", action: "Phone updated", details: "Updated phone number", user: "Admin" },
      ],
      checkins: [
          { id: 1, date: "2025-01-20T09:30", type: "Check-in", location: "Main Entrance", user: "Jennifer Markus" },
          { id: 2, date: "2025-01-20T11:45", type: "Check-out", location: "Main Entrance", user: "Jennifer Markus" },
      ],
      appointments: [
          { id: 1, date: "2025-01-18T10:00", title: "Personal Training", status: "completed", trainer: "Mike Johnson" },
          { id: 2, date: "2025-01-15T14:30", title: "Consultation", status: "completed", trainer: "Sarah Wilson" },
      ],
      finance: [
          {
              id: 1,
              date: "2025-01-01",
              type: "Payment",
              amount: "$99.99",
              description: "Monthly membership fee",
              status: "completed",
          },
          {
              id: 2,
              date: "2024-12-01",
              type: "Payment",
              amount: "$99.99",
              description: "Monthly membership fee",
              status: "completed",
          },
      ],
      contracts: [
          {
              id: 1,
              date: "2024-03-01",
              action: "Contract signed",
              details: "Initial 12-month membership contract",
              user: "Admin",
          },
          { id: 2, date: "2024-02-28", action: "Contract updated", details: "Extended contract duration", user: "Admin" },
      ],
  },
  2: {
      general: [
          {
              id: 1,
              date: "2025-01-12",
              action: "Profile updated",
              details: "Updated personal information",
              user: "Admin",
          },
      ],
      checkins: [
          { id: 1, date: "2025-01-19T08:00", type: "Check-in", location: "Main Entrance", user: "Jerry Haffer" },
          { id: 2, date: "2025-01-19T10:30", type: "Check-out", location: "Main Entrance", user: "Jerry Haffer" },
      ],
      appointments: [
          { id: 1, date: "2025-01-17T14:00", title: "Cardio Session", status: "completed", trainer: "Lisa Davis" },
      ],
      finance: [
          {
              id: 1,
              date: "2025-01-01",
              type: "Payment",
              amount: "$89.99",
              description: "Monthly membership fee",
              status: "completed",
          },
      ],
      contracts: [
          {
              id: 1,
              date: "2021-11-15",
              action: "Contract signed",
              details: "Initial membership contract",
              user: "Admin",
          },
      ],
  },
  3: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
  4: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
  5: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
  100: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
};

export const studioappointmentsMainData = [
  {
    id: 1,
    title: "Initial Consultation",
    date: "2025-03-15T10:00",
    status: "upcoming",
    type: "Consultation",
    memberId: 1,
    specialNote: {
      text: "First time client, needs introduction to equipment",
      isImportant: true,
      startDate: "2025-03-15",
      endDate: "2025-03-20",
    },
  },
  {
    id: 2,
    title: "Follow-up Meeting",
    date: "2025-03-20T14:30",
    status: "upcoming",
    type: "Follow-up",
    memberId: 1,
  },
  {
    id: 3,
    title: "Annual Review",
    date: "2025-04-05T11:00",
    status: "upcoming",
    type: "Annual Review",
    memberId: 2,
  },
]

export const studioappointmentTypeMainData = [
  { name: "Consultation", duration: 30, color: "bg-blue-700" },
  { name: "Follow-up", duration: 45, color: "bg-green-700" },
  { name: "Annual Review", duration: 60, color: "bg-purple-600" },
  { name: "Training", duration: 60, color: "bg-orange-600" },
  { name: "Assessment", duration: 90, color: "bg-red-600" },
]

export const studiofreeAppointmentsMainData = [
  { id: 1, date: "2025-03-15", time: "9:00 AM" },
  { id: 2, date: "2025-03-15", time: "11:00 AM" },
  { id: 3, date: "2025-03-15", time: "2:00 PM" },
  { id: 4, date: "2025-03-20", time: "10:00 AM" },
  { id: 5, date: "2025-03-20", time: "1:30 PM" },
  { id: 6, date: "2025-04-05", time: "9:30 AM" },
  { id: 7, date: "2025-04-05", time: "3:00 PM" },
]
