// Design templates organized by category
// Following the design concept: Clean, professional, fitness-studio focused
// Only using: Lines, Gradients, Geometric Shapes, Text Blocks
// NO: Photos, Illustrations with people, Decorative elements without function

export const templateCategories = [
  { id: "all", name: "All Templates", icon: "Grid3X3" },
  { id: "custom", name: "My Templates", icon: "Bookmark" },
  { id: "announcement", name: "Announcements", icon: "Bell" },
  { id: "notice", name: "Important Notices", icon: "AlertTriangle" },
  { id: "event", name: "Events & Challenges", icon: "Calendar" },
  { id: "minimal", name: "Minimal", icon: "Minus" },
  { id: "promotion", name: "Promotions", icon: "Megaphone" },
  { id: "staff", name: "Internal / Staff", icon: "Lock" },
  { id: "ems", name: "EMS Special", icon: "Zap" },
  { id: "reminder", name: "Reminders", icon: "Clock" }
];

// Pre-designed templates with elements
// All templates use isBackground: true for the background layer
// Design rules: Primary color for accents, Secondary for backgrounds
// Contrast through: White/Light gray, Opacity, Gradients, Lines & Shapes

export const templates = [
  // ============================================
  // ANNOUNCEMENT / INFO TEMPLATES
  // ============================================
  {
    id: "announcement-light-1",
    name: "Announcement Light",
    category: "announcement",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#FAFAFA"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FAFAFA",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "gradient-accent",
        type: "gradient",
        gradientColors: ["#F97316", "#EA580C"],
        gradientAngle: 135,
        x: 0,
        y: 0,
        width: 1080,
        height: 8,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "ANNOUNCEMENT",
        color: "#1A1A1A",
        size: 64,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 180,
        width: 960,
        height: 80,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 60,
        y: 280,
        width: 120,
        height: 4,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Here is your important\ninformation for all\nmembers.",
        color: "#404040",
        size: 36,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 340,
        width: 960,
        height: 200,
        zIndex: 3
      },
      {
        id: "footer-line",
        type: "shape",
        shape: "rectangle",
        color: "#E5E5E5",
        x: 60,
        y: 920,
        width: 960,
        height: 2,
        zIndex: 1
      },
      {
        id: "footer-text",
        type: "text",
        content: "More info at the front desk",
        color: "#737373",
        size: 18,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 950,
        width: 960,
        height: 30,
        zIndex: 3
      }
    ]
  },
  {
    id: "announcement-dark-1",
    name: "Announcement Dark",
    category: "announcement",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#0A0A0A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#0A0A0A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "gradient-accent",
        type: "gradient",
        gradientColors: ["#F97316", "#DC2626"],
        gradientAngle: 90,
        x: 0,
        y: 0,
        width: 8,
        height: 1080,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "ANNOUNCEMENT",
        color: "#FFFFFF",
        size: 64,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 180,
        width: 920,
        height: 80,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 80,
        y: 280,
        width: 120,
        height: 4,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Here is your important\ninformation for all\nmembers.",
        color: "#D4D4D4",
        size: 36,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 340,
        width: 920,
        height: 200,
        zIndex: 3
      },
      {
        id: "footer-text",
        type: "text",
        content: "More info at the front desk",
        color: "#737373",
        size: 18,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 950,
        width: 920,
        height: 30,
        zIndex: 3
      }
    ]
  },
  {
    id: "announcement-centered",
    name: "Announcement Centered",
    category: "announcement",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#FFFFFF"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "top-gradient",
        type: "gradient",
        gradientColors: ["#F97316", "#F59E0B"],
        gradientAngle: 90,
        x: 0,
        y: 0,
        width: 1080,
        height: 200,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "INFO",
        color: "#FFFFFF",
        size: 48,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 70,
        width: 900,
        height: 60,
        zIndex: 2
      },
      {
        id: "main-text",
        type: "text",
        content: "Important\nNotice",
        color: "#1A1A1A",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 450,
        width: 900,
        height: 200,
        zIndex: 2
      },
      {
        id: "center-line",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 440,
        y: 680,
        width: 200,
        height: 4,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Details and more information\ncan be found here.",
        color: "#525252",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 740,
        width: 900,
        height: 100,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // IMPORTANT NOTICE TEMPLATES
  // ============================================
  {
    id: "notice-urgent",
    name: "Urgent Notice",
    category: "notice",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#DC2626",
      secondary: "#1A1A1A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#DC2626",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "side-line",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 60,
        y: 200,
        width: 6,
        height: 400,
        zIndex: 1
      },
      {
        id: "badge",
        type: "text",
        content: "IMPORTANT",
        color: "#FFFFFF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 100,
        y: 200,
        width: 200,
        height: 40,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "PLEASE\nNOTE",
        color: "#FFFFFF",
        size: 96,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 100,
        y: 280,
        width: 900,
        height: 250,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Here is important information\nthat all members should note.",
        color: "rgba(255,255,255,0.9)",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 100,
        y: 560,
        width: 880,
        height: 120,
        zIndex: 3
      }
    ]
  },
  {
    id: "notice-info",
    name: "Info Notice",
    category: "notice",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#2563EB",
      secondary: "#EFF6FF"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#EFF6FF",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "left-accent",
        type: "shape",
        shape: "rectangle",
        color: "#2563EB",
        x: 0,
        y: 0,
        width: 12,
        height: 1080,
        zIndex: 1
      },
      {
        id: "info-badge",
        type: "shape",
        shape: "circle",
        color: "#2563EB",
        x: 80,
        y: 180,
        width: 80,
        height: 80,
        zIndex: 1
      },
      {
        id: "info-icon",
        type: "text",
        content: "i",
        color: "#FFFFFF",
        size: 48,
        font: "'Playfair Display', serif",
        bold: true,
        italic: true,
        underline: false,
        align: "center",
        x: 80,
        y: 192,
        width: 80,
        height: 60,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "GOOD TO KNOW",
        color: "#1E3A8A",
        size: 56,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 320,
        width: 920,
        height: 70,
        zIndex: 2
      },
      {
        id: "underline",
        type: "shape",
        shape: "rectangle",
        color: "#2563EB",
        x: 80,
        y: 400,
        width: 100,
        height: 4,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Here is helpful information\nfor our members.",
        color: "#1E40AF",
        size: 32,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 460,
        width: 920,
        height: 150,
        zIndex: 3
      }
    ]
  },
  {
    id: "notice-warning-dark",
    name: "Warning Dark",
    category: "notice",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#F59E0B",
      secondary: "#1C1917"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#1C1917",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "warning-triangle",
        type: "shape",
        shape: "triangle",
        color: "#F59E0B",
        x: 440,
        y: 200,
        width: 200,
        height: 180,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "ATTENTION",
        color: "#F59E0B",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 450,
        width: 900,
        height: 90,
        zIndex: 2
      },
      {
        id: "subline",
        type: "shape",
        shape: "rectangle",
        color: "#F59E0B",
        x: 390,
        y: 560,
        width: 300,
        height: 3,
        zIndex: 2
      },
      {
        id: "body-text",
        type: "text",
        content: "Important safety information\nfor all gym members.\n\nPlease read carefully.",
        color: "#FAFAF9",
        size: 32,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 620,
        width: 900,
        height: 250,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // EVENT & CHALLENGE TEMPLATES
  // ============================================
  {
    id: "event-challenge-1",
    name: "Challenge",
    category: "event",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#10B981",
      secondary: "#064E3B"
    },
    elements: [
      {
        id: "background",
        type: "gradient",
        gradientColors: ["#064E3B", "#022C22"],
        gradientAngle: 180,
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "diagonal-accent",
        type: "shape",
        shape: "rectangle",
        color: "#10B981",
        x: -100,
        y: 200,
        width: 1300,
        height: 8,
        zIndex: 1
      },
      {
        id: "diagonal-accent-2",
        type: "shape",
        shape: "rectangle",
        color: "rgba(16,185,129,0.3)",
        x: -100,
        y: 240,
        width: 1300,
        height: 4,
        zIndex: 1
      },
      {
        id: "badge",
        type: "text",
        content: "NEW",
        color: "#10B981",
        size: 20,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 300,
        width: 100,
        height: 30,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "30-DAY\nCHALLENGE",
        color: "#FFFFFF",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 350,
        width: 920,
        height: 220,
        zIndex: 2
      },
      {
        id: "date-info",
        type: "text",
        content: "JAN 1 - JAN 30, 2025",
        color: "#10B981",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 600,
        width: 500,
        height: 40,
        zIndex: 3
      },
      {
        id: "description",
        type: "text",
        content: "Start your transformation now.\nOne step closer every day.",
        color: "#A7F3D0",
        size: 24,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 700,
        width: 800,
        height: 80,
        zIndex: 3
      },
      {
        id: "cta",
        type: "text",
        content: "SIGN UP NOW →",
        color: "#FFFFFF",
        size: 20,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 920,
        width: 300,
        height: 30,
        zIndex: 3
      }
    ]
  },
  {
    id: "event-grand-opening",
    name: "Event Announcement",
    category: "event",
    size: "1080x1920",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#1A1A1A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#1A1A1A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "top-gradient",
        type: "gradient",
        gradientColors: ["#F97316", "#EA580C"],
        gradientAngle: 180,
        x: 0,
        y: 0,
        width: 1080,
        height: 400,
        zIndex: 1
      },
      {
        id: "date-display",
        type: "text",
        content: "15\nJAN",
        color: "#FFFFFF",
        size: 96,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 390,
        y: 100,
        width: 300,
        height: 200,
        zIndex: 2
      },
      {
        id: "event-title",
        type: "text",
        content: "GRAND\nOPENING",
        color: "#FFFFFF",
        size: 96,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 650,
        width: 900,
        height: 250,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 340,
        y: 940,
        width: 400,
        height: 4,
        zIndex: 2
      },
      {
        id: "event-details",
        type: "text",
        content: "Join us for the opening!\n\n6:00 PM - 10:00 PM\nFree trial workouts\nDrinks & Snacks",
        color: "#D4D4D4",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 1020,
        width: 900,
        height: 300,
        zIndex: 3
      },
      {
        id: "cta-button-bg",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 290,
        y: 1600,
        width: 500,
        height: 70,
        zIndex: 2,
        borderRadius: 8
      },
      {
        id: "cta-text",
        type: "text",
        content: "REGISTER NOW",
        color: "#FFFFFF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 290,
        y: 1618,
        width: 500,
        height: 40,
        zIndex: 3
      }
    ]
  },
  {
    id: "event-fitness-week",
    name: "Fitness Week",
    category: "event",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#8B5CF6",
      secondary: "#1E1B4B"
    },
    elements: [
      {
        id: "background",
        type: "gradient",
        gradientColors: ["#1E1B4B", "#312E81"],
        gradientAngle: 135,
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "geometric-1",
        type: "shape",
        shape: "circle",
        color: "rgba(139,92,246,0.15)",
        x: -150,
        y: -150,
        width: 400,
        height: 400,
        zIndex: 1
      },
      {
        id: "geometric-2",
        type: "shape",
        shape: "circle",
        color: "rgba(139,92,246,0.1)",
        x: 800,
        y: 1000,
        width: 500,
        height: 500,
        zIndex: 1
      },
      {
        id: "tag",
        type: "text",
        content: "SPECIAL EVENT",
        color: "#8B5CF6",
        size: 18,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 300,
        width: 200,
        height: 30,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "FITNESS\nWEEK",
        color: "#FFFFFF",
        size: 96,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 360,
        width: 920,
        height: 250,
        zIndex: 2
      },
      {
        id: "date-range",
        type: "text",
        content: "FEBRUARY 10 - 17",
        color: "#C4B5FD",
        size: 28,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 640,
        width: 400,
        height: 40,
        zIndex: 3
      },
      {
        id: "description",
        type: "text",
        content: "• Free classes for members\n• Bring a friend promotion\n• Nutrition workshops\n• Prizes & giveaways",
        color: "#E0E7FF",
        size: 26,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 740,
        width: 800,
        height: 200,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // MINIMAL TEXT TEMPLATES
  // ============================================
  {
    id: "minimal-clean-white",
    name: "Minimal White",
    category: "minimal",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#1A1A1A",
      secondary: "#FFFFFF"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "main-text",
        type: "text",
        content: "Simple.\nClear.\nEffective.",
        color: "#1A1A1A",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 320,
        width: 900,
        height: 350,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#1A1A1A",
        x: 440,
        y: 720,
        width: 200,
        height: 3,
        zIndex: 1
      },
      {
        id: "subtext",
        type: "text",
        content: "Your training. Your success.",
        color: "#737373",
        size: 22,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 780,
        width: 900,
        height: 40,
        zIndex: 2
      }
    ]
  },
  {
    id: "minimal-clean-dark",
    name: "Minimal Dark",
    category: "minimal",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#FFFFFF",
      secondary: "#0A0A0A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#0A0A0A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "main-text",
        type: "text",
        content: "No\nExcuses.",
        color: "#FFFFFF",
        size: 96,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 380,
        width: 900,
        height: 250,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 440,
        y: 680,
        width: 200,
        height: 2,
        zIndex: 1
      },
      {
        id: "subtext",
        type: "text",
        content: "Only results.",
        color: "#737373",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 730,
        width: 900,
        height: 40,
        zIndex: 2
      }
    ]
  },
  {
    id: "minimal-statement",
    name: "Statement",
    category: "minimal",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#FAFAFA"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FAFAFA",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "main-text",
        type: "text",
        content: "TRAIN\nHARD",
        color: "#1A1A1A",
        size: 140,
        font: "'Archivo Black', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 450,
        width: 900,
        height: 350,
        zIndex: 2
      },
      {
        id: "accent-dot",
        type: "shape",
        shape: "circle",
        color: "#F97316",
        x: 920,
        y: 760,
        width: 60,
        height: 60,
        zIndex: 2
      }
    ]
  },
  {
    id: "minimal-quote",
    name: "Minimal Quote",
    category: "minimal",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#1A1A1A",
      secondary: "#F5F5F5"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#F5F5F5",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "quote-mark",
        type: "text",
        content: "\"",
        color: "#E5E5E5",
        size: 300,
        font: "'Playfair Display', serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 40,
        y: 100,
        width: 200,
        height: 300,
        zIndex: 1
      },
      {
        id: "quote-text",
        type: "text",
        content: "The pain of today\nis the strength\nof tomorrow.",
        color: "#1A1A1A",
        size: 48,
        font: "'Playfair Display', serif",
        bold: false,
        italic: true,
        underline: false,
        align: "center",
        x: 90,
        y: 380,
        width: 900,
        height: 220,
        zIndex: 2
      },
      {
        id: "author",
        type: "text",
        content: "— Arnold Schwarzenegger",
        color: "#737373",
        size: 18,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 650,
        width: 900,
        height: 30,
        zIndex: 2
      }
    ]
  },

  // ============================================
  // PROMOTION / OFFER TEMPLATES
  // ============================================
  {
    id: "promo-discount",
    name: "Discount Promo",
    category: "promotion",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#DC2626",
      secondary: "#1A1A1A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#1A1A1A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "left-panel",
        type: "shape",
        shape: "rectangle",
        color: "#DC2626",
        x: 0,
        y: 0,
        width: 540,
        height: 1080,
        zIndex: 1
      },
      {
        id: "discount-amount",
        type: "text",
        content: "50%",
        color: "#FFFFFF",
        size: 180,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 20,
        y: 350,
        width: 500,
        height: 200,
        zIndex: 2
      },
      {
        id: "off-text",
        type: "text",
        content: "OFF",
        color: "#FFFFFF",
        size: 48,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 20,
        y: 540,
        width: 500,
        height: 60,
        zIndex: 2
      },
      {
        id: "promo-title",
        type: "text",
        content: "NEW YEAR\nSALE",
        color: "#FFFFFF",
        size: 64,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 580,
        y: 380,
        width: 460,
        height: 180,
        zIndex: 2
      },
      {
        id: "validity",
        type: "text",
        content: "Valid until Jan 31, 2025",
        color: "#737373",
        size: 18,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 580,
        y: 580,
        width: 460,
        height: 30,
        zIndex: 3
      }
    ]
  },
  {
    id: "promo-special-offer",
    name: "Special Offer",
    category: "promotion",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#F97316",
      secondary: "#FFFFFF"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "top-bar",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 0,
        y: 0,
        width: 1080,
        height: 120,
        zIndex: 1
      },
      {
        id: "badge-text",
        type: "text",
        content: "LIMITED OFFER",
        color: "#FFFFFF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 45,
        width: 900,
        height: 40,
        zIndex: 2
      },
      {
        id: "main-offer",
        type: "text",
        content: "3 MONTHS\nFOR THE\nPRICE OF 2",
        color: "#1A1A1A",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 400,
        width: 900,
        height: 300,
        zIndex: 2
      },
      {
        id: "price-line",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 340,
        y: 740,
        width: 400,
        height: 4,
        zIndex: 2
      },
      {
        id: "details",
        type: "text",
        content: "New members only\nOffer valid until end of month",
        color: "#525252",
        size: 22,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 800,
        width: 900,
        height: 80,
        zIndex: 3
      },
      {
        id: "cta-bg",
        type: "shape",
        shape: "rectangle",
        color: "#F97316",
        x: 290,
        y: 1100,
        width: 500,
        height: 70,
        zIndex: 2,
        borderRadius: 8
      },
      {
        id: "cta-text",
        type: "text",
        content: "CLAIM NOW",
        color: "#FFFFFF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 290,
        y: 1118,
        width: 500,
        height: 40,
        zIndex: 3
      }
    ]
  },
  {
    id: "promo-free-trial",
    name: "Free Trial",
    category: "promotion",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#10B981",
      secondary: "#ECFDF5"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#ECFDF5",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "accent-circle",
        type: "shape",
        shape: "circle",
        color: "#10B981",
        x: 340,
        y: 150,
        width: 400,
        height: 400,
        zIndex: 1
      },
      {
        id: "free-text",
        type: "text",
        content: "FREE",
        color: "#FFFFFF",
        size: 64,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 340,
        y: 300,
        width: 400,
        height: 80,
        zIndex: 2
      },
      {
        id: "main-text",
        type: "text",
        content: "TRIAL\nWORKOUT",
        color: "#065F46",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 620,
        width: 900,
        height: 220,
        zIndex: 2
      },
      {
        id: "subtext",
        type: "text",
        content: "Book your appointment now",
        color: "#059669",
        size: 24,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 880,
        width: 900,
        height: 40,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // STAFF / INTERNAL TEMPLATES
  // ============================================
  {
    id: "staff-meeting",
    name: "Team Meeting",
    category: "staff",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#6366F1",
      secondary: "#1E1B4B"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#1E1B4B",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "staff-badge",
        type: "shape",
        shape: "rectangle",
        color: "#6366F1",
        x: 60,
        y: 60,
        width: 140,
        height: 40,
        zIndex: 1,
        borderRadius: 4
      },
      {
        id: "badge-text",
        type: "text",
        content: "INTERNAL",
        color: "#FFFFFF",
        size: 16,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 65,
        y: 70,
        width: 130,
        height: 24,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "TEAM\nMEETING",
        color: "#FFFFFF",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 280,
        width: 960,
        height: 220,
        zIndex: 2
      },
      {
        id: "accent-line",
        type: "shape",
        shape: "rectangle",
        color: "#6366F1",
        x: 60,
        y: 520,
        width: 100,
        height: 4,
        zIndex: 2
      },
      {
        id: "details",
        type: "text",
        content: "Date: Monday, January 15\nTime: 9:00 AM\nLocation: Meeting Room",
        color: "#C7D2FE",
        size: 26,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 580,
        width: 960,
        height: 150,
        zIndex: 3
      },
      {
        id: "footer",
        type: "text",
        content: "Attendance required",
        color: "#818CF8",
        size: 18,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 920,
        width: 400,
        height: 30,
        zIndex: 3
      }
    ]
  },
  {
    id: "staff-notice",
    name: "Staff Notice",
    category: "staff",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#475569",
      secondary: "#0F172A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#0F172A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "top-border",
        type: "shape",
        shape: "rectangle",
        color: "#475569",
        x: 0,
        y: 0,
        width: 1080,
        height: 6,
        zIndex: 1
      },
      {
        id: "tag",
        type: "text",
        content: "STAFF ONLY",
        color: "#64748B",
        size: 14,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 60,
        width: 300,
        height: 24,
        zIndex: 2
      },
      {
        id: "headline",
        type: "text",
        content: "IMPORTANT\nINFORMATION",
        color: "#F1F5F9",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 350,
        width: 960,
        height: 200,
        zIndex: 2
      },
      {
        id: "divider",
        type: "shape",
        shape: "rectangle",
        color: "#334155",
        x: 60,
        y: 580,
        width: 960,
        height: 1,
        zIndex: 1
      },
      {
        id: "content",
        type: "text",
        content: "Here is internal information\nfor the team.\n\nPlease keep confidential.",
        color: "#94A3B8",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 640,
        width: 960,
        height: 200,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // EMS SPECIAL TEMPLATES
  // ============================================
  {
    id: "ems-intro",
    name: "EMS Introduction",
    category: "ems",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#00D9FF",
      secondary: "#0A0A0A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#0A0A0A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "grid-line-1",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 0,
        y: 270,
        width: 1080,
        height: 1,
        zIndex: 1
      },
      {
        id: "grid-line-2",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 0,
        y: 540,
        width: 1080,
        height: 1,
        zIndex: 1
      },
      {
        id: "grid-line-3",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 0,
        y: 810,
        width: 1080,
        height: 1,
        zIndex: 1
      },
      {
        id: "grid-line-v1",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 270,
        y: 0,
        width: 1,
        height: 1080,
        zIndex: 1
      },
      {
        id: "grid-line-v2",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 540,
        y: 0,
        width: 1,
        height: 1080,
        zIndex: 1
      },
      {
        id: "grid-line-v3",
        type: "shape",
        shape: "rectangle",
        color: "rgba(0,217,255,0.1)",
        x: 810,
        y: 0,
        width: 1,
        height: 1080,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "EMS",
        color: "#00D9FF",
        size: 180,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 320,
        width: 900,
        height: 200,
        zIndex: 2
      },
      {
        id: "subline",
        type: "text",
        content: "TRAINING",
        color: "#FFFFFF",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 510,
        width: 900,
        height: 90,
        zIndex: 2
      },
      {
        id: "tagline",
        type: "text",
        content: "20 minutes. Maximum efficiency.",
        color: "#00D9FF",
        size: 24,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 640,
        width: 900,
        height: 40,
        zIndex: 3
      }
    ]
  },
  {
    id: "ems-benefits",
    name: "EMS Benefits",
    category: "ems",
    size: "1080x1350",
    thumbnail: null,
    colors: {
      primary: "#00D9FF",
      secondary: "#111827"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#111827",
        x: 0,
        y: 0,
        width: 1080,
        height: 1350,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "top-accent",
        type: "gradient",
        gradientColors: ["#00D9FF", "#0077B6"],
        gradientAngle: 90,
        x: 0,
        y: 0,
        width: 1080,
        height: 8,
        zIndex: 1
      },
      {
        id: "headline",
        type: "text",
        content: "WHY EMS?",
        color: "#FFFFFF",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 120,
        width: 960,
        height: 90,
        zIndex: 2
      },
      {
        id: "benefit-1",
        type: "text",
        content: "01  TIME EFFICIENT",
        color: "#00D9FF",
        size: 32,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 320,
        width: 960,
        height: 50,
        zIndex: 2
      },
      {
        id: "benefit-1-desc",
        type: "text",
        content: "20 min workout = 3 hours gym",
        color: "#9CA3AF",
        size: 22,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 380,
        width: 960,
        height: 40,
        zIndex: 3
      },
      {
        id: "line-1",
        type: "shape",
        shape: "rectangle",
        color: "#1F2937",
        x: 60,
        y: 460,
        width: 960,
        height: 1,
        zIndex: 1
      },
      {
        id: "benefit-2",
        type: "text",
        content: "02  JOINT FRIENDLY",
        color: "#00D9FF",
        size: 32,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 500,
        width: 960,
        height: 50,
        zIndex: 2
      },
      {
        id: "benefit-2-desc",
        type: "text",
        content: "No additional weight needed",
        color: "#9CA3AF",
        size: 22,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 560,
        width: 960,
        height: 40,
        zIndex: 3
      },
      {
        id: "line-2",
        type: "shape",
        shape: "rectangle",
        color: "#1F2937",
        x: 60,
        y: 640,
        width: 960,
        height: 1,
        zIndex: 1
      },
      {
        id: "benefit-3",
        type: "text",
        content: "03  FULL BODY",
        color: "#00D9FF",
        size: 32,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 680,
        width: 960,
        height: 50,
        zIndex: 2
      },
      {
        id: "benefit-3-desc",
        type: "text",
        content: "Over 300 muscles activated simultaneously",
        color: "#9CA3AF",
        size: 22,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 740,
        width: 960,
        height: 40,
        zIndex: 3
      },
      {
        id: "cta",
        type: "text",
        content: "TRY IT NOW →",
        color: "#00D9FF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 60,
        y: 1200,
        width: 300,
        height: 40,
        zIndex: 3
      }
    ]
  },

  // ============================================
  // REMINDER / SHORT UPDATE TEMPLATES
  // ============================================
  {
    id: "reminder-simple",
    name: "Simple Reminder",
    category: "reminder",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#F59E0B",
      secondary: "#FFFBEB"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FFFBEB",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "accent-bar",
        type: "shape",
        shape: "rectangle",
        color: "#F59E0B",
        x: 0,
        y: 0,
        width: 12,
        height: 1080,
        zIndex: 1
      },
      {
        id: "reminder-badge",
        type: "text",
        content: "REMINDER",
        color: "#B45309",
        size: 20,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 280,
        width: 200,
        height: 30,
        zIndex: 2
      },
      {
        id: "main-text",
        type: "text",
        content: "Don't\nForget!",
        color: "#78350F",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 340,
        width: 920,
        height: 220,
        zIndex: 2
      },
      {
        id: "detail-text",
        type: "text",
        content: "Your important reminder goes here.",
        color: "#92400E",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "left",
        x: 80,
        y: 600,
        width: 920,
        height: 50,
        zIndex: 3
      }
    ]
  },
  {
    id: "reminder-today",
    name: "Today Reminder",
    category: "reminder",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#EF4444",
      secondary: "#0A0A0A"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#0A0A0A",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "today-badge",
        type: "shape",
        shape: "rectangle",
        color: "#EF4444",
        x: 60,
        y: 60,
        width: 160,
        height: 50,
        zIndex: 1,
        borderRadius: 4
      },
      {
        id: "badge-text",
        type: "text",
        content: "TODAY",
        color: "#FFFFFF",
        size: 24,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 65,
        y: 72,
        width: 150,
        height: 30,
        zIndex: 2
      },
      {
        id: "main-text",
        type: "text",
        content: "Class at\n6:00 PM",
        color: "#FFFFFF",
        size: 84,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 380,
        width: 900,
        height: 220,
        zIndex: 2
      },
      {
        id: "detail",
        type: "text",
        content: "Spots available • Sign up now",
        color: "#EF4444",
        size: 24,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 640,
        width: 900,
        height: 40,
        zIndex: 3
      }
    ]
  },
  {
    id: "reminder-compact",
    name: "Compact Reminder",
    category: "reminder",
    size: "1080x1080",
    thumbnail: null,
    colors: {
      primary: "#059669",
      secondary: "#FFFFFF"
    },
    elements: [
      {
        id: "background",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        zIndex: -1,
        isBackground: true,
        name: "Background"
      },
      {
        id: "border",
        type: "shape",
        shape: "rectangle",
        color: "#059669",
        x: 40,
        y: 40,
        width: 1000,
        height: 1000,
        zIndex: 1
      },
      {
        id: "inner-bg",
        type: "shape",
        shape: "rectangle",
        color: "#FFFFFF",
        x: 48,
        y: 48,
        width: 984,
        height: 984,
        zIndex: 2
      },
      {
        id: "checkmark",
        type: "text",
        content: "✓",
        color: "#059669",
        size: 120,
        font: "Inter, sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 280,
        width: 900,
        height: 140,
        zIndex: 3
      },
      {
        id: "main-text",
        type: "text",
        content: "DONE?",
        color: "#059669",
        size: 72,
        font: "'Bebas Neue', sans-serif",
        bold: true,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 450,
        width: 900,
        height: 90,
        zIndex: 3
      },
      {
        id: "task-text",
        type: "text",
        content: "Pick up your training plan this week",
        color: "#374151",
        size: 28,
        font: "Inter, sans-serif",
        bold: false,
        italic: false,
        underline: false,
        align: "center",
        x: 90,
        y: 580,
        width: 900,
        height: 50,
        zIndex: 3
      }
    ]
  }
];

// Blank templates for starting fresh
export const blankTemplates = [
  { id: "blank-square", name: "Blank Square", size: "1080x1080", category: "blank" },
  { id: "blank-portrait", name: "Blank Portrait", size: "1080x1350", category: "blank" },
  { id: "blank-story", name: "Blank Story", size: "1080x1920", category: "blank" },
  { id: "blank-landscape", name: "Blank Landscape", size: "1920x1080", category: "blank" }
];

export default {
  templateCategories,
  templates,
  blankTemplates
};
