export const analyticsData = {
    overview: {
      totalRevenue: 125420,
      revenueGrowth: 12.5,
      totalMembers: 1247,
      memberGrowth: 8.3,
      totalAppointments: 892,
      appointmentGrowth: -2.1,
      averageSessionDuration: 65,
      sessionGrowth: 5.2,
    },
    revenueByMonth: [
      { month: "Jan", revenue: 8500, appointments: 120 },
      { month: "Feb", revenue: 9200, appointments: 135 },
      { month: "Mar", revenue: 10100, appointments: 142 },
      { month: "Apr", revenue: 11300, appointments: 158 },
      { month: "May", revenue: 10800, appointments: 151 },
      { month: "Jun", revenue: 12400, appointments: 167 },
      { month: "Jul", revenue: 13200, appointments: 178 },
      { month: "Aug", revenue: 12800, appointments: 172 },
      { month: "Sep", revenue: 14100, appointments: 189 },
      { month: "Oct", revenue: 13600, appointments: 183 },
      { month: "Nov", revenue: 15200, appointments: 201 },
      { month: "Dec", revenue: 14200, appointments: 195 },
    ],
    membershipTypes: [
      { name: "Premium", count: 423, percentage: 34, revenue: 52800 },
      { name: "Standard", count: 512, percentage: 41, revenue: 38400 },
      { name: "Basic", count: 312, percentage: 25, revenue: 18720 },
    ],
    topServices: [
      { name: "Personal Training", revenue: 45200, sessions: 312, avgPrice: 145 },
      { name: "Group Classes", revenue: 28900, sessions: 578, avgPrice: 50 },
      { name: "Nutrition Consulting", revenue: 18600, sessions: 124, avgPrice: 150 },
      { name: "Physiotherapy", revenue: 15400, sessions: 88, avgPrice: 175 },
      { name: "Yoga Classes", revenue: 12300, sessions: 246, avgPrice: 50 },
    ],
    peakHours: [
      { hour: "6 AM", appointments: 45 },
      { hour: "7 AM", appointments: 78 },
      { hour: "8 AM", appointments: 92 },
      { hour: "9 AM", appointments: 65 },
      { hour: "10 AM", appointments: 58 },
      { hour: "11 AM", appointments: 42 },
      { hour: "12 PM", appointments: 38 },
      { hour: "1 PM", appointments: 35 },
      { hour: "2 PM", appointments: 48 },
      { hour: "3 PM", appointments: 52 },
      { hour: "4 PM", appointments: 68 },
      { hour: "5 PM", appointments: 85 },
      { hour: "6 PM", appointments: 95 },
      { hour: "7 PM", appointments: 88 },
      { hour: "8 PM", appointments: 72 },
      { hour: "9 PM", appointments: 45 },
    ],
    staffPerformance: [
      { name: "John Smith", appointments: 156, revenue: 23400, rating: 4.8 },
      { name: "Sarah Johnson", appointments: 142, revenue: 21300, rating: 4.9 },
      { name: "Mike Wilson", revenue: 18900, appointments: 126, rating: 4.7 },
      { name: "Emma Davis", appointments: 134, revenue: 20100, rating: 4.8 },
    ],
    memberRetention: [
      { month: "Jan", retained: 92, new: 45, churned: 12 },
      { month: "Feb", retained: 94, new: 52, churned: 8 },
      { month: "Mar", retained: 91, new: 48, churned: 15 },
      { month: "Apr", retained: 95, new: 58, churned: 7 },
      { month: "May", retained: 93, new: 42, churned: 11 },
      { month: "Jun", retained: 96, new: 65, churned: 5 },
    ],
    checkedInMembers: [
      { name: "Alice Cooper", checkInTime: "08:30 AM", service: "Personal Training" },
      { name: "Bob Johnson", checkInTime: "09:15 AM", service: "Group Classes" },
      { name: "Carol Smith", checkInTime: "10:00 AM", service: "Yoga Classes" },
      { name: "David Wilson", checkInTime: "11:30 AM", service: "Physiotherapy" },
    ],
    cancelledAppointments: [
      { name: "Emma Brown", service: "Personal Training", cancelTime: "2 hours ago", reason: "Emergency" },
      { name: "Frank Davis", service: "Nutrition Consulting", cancelTime: "4 hours ago", reason: "Illness" },
      { name: "Grace Miller", service: "Group Classes", cancelTime: "1 day ago", reason: "Schedule conflict" },
    ],
    leads: [
      { name: "Henry Taylor", source: "Website", interest: "Personal Training", score: 85 },
      { name: "Ivy Anderson", source: "Referral", interest: "Group Classes", score: 92 },
      { name: "Jack Thompson", source: "Social Media", interest: "Yoga Classes", score: 78 },
      { name: "Kate Wilson", source: "Walk-in", interest: "Nutrition", score: 88 },
    ],
  }