// appointmentsData.js
export const appointmentsData = [
  {
    id: 1,
    memberId: 1,
    name: "Yolanda",
    lastName: "Martinez",
    time: "09:00 - 09:30",
    date: "Mon | 07-02-2025",
    color: "bg-[#4169E1]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Strength Training",
    specialNote: { text: "Prefers morning sessions", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: true,
  },
  {
    id: 2,
    memberId: 2,
    name: "Denis",
    lastName: "Schmidt",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 3,
    memberId: 3,
    name: "Nicole",
    lastName: "Weber",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 4,
    memberId: 4,
    name: "Melanie",
    lastName: "Fischer",
    time: "09:00 - 09:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 5,
    memberId: 5,
    name: "Angela",
    lastName: "Hoffmann",
    time: "09:30 - 10:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#ef4444]",
    startTime: "09:30",
    endTime: "10:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 6,
    memberId: 6,
    name: "Kristina",
    lastName: "Becker",
    time: "09:30 - 10:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "09:30",
    endTime: "10:00",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 7,
    memberId: 7,
    name: "Melanie",
    lastName: "Schulz",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 8,
    memberId: 8,
    name: "Annett",
    lastName: "Koch",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#10b981]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 9,
    memberId: 9,
    name: "Justin",
    lastName: "Bauer",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 10,
    memberId: 10,
    name: "Michel",
    lastName: "Wagner",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 11,
    memberId: 11,
    name: "Colin",
    lastName: "Richter",
    time: "11:30 - 12:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "11:30",
    endTime: "12:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 12,
    memberId: 12,
    name: "Yvonne",
    lastName: "Klein",
    time: "11:30 - 12:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "11:30",
    endTime: "12:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 13,
    memberId: 13,
    name: "Jennifer",
    lastName: "Wolf",
    time: "12:00 - 12:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#ef4444]",
    startTime: "12:00",
    endTime: "12:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 14,
    memberId: 14,
    name: "Michael",
    lastName: "Schröder",
    time: "12:00 - 12:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "12:00",
    endTime: "12:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 15,
    memberId: 15,
    name: "Furkan",
    lastName: "Yilmaz",
    time: "13:00 - 13:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "13:00",
    endTime: "13:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 16,
    memberId: 16,
    name: "Heike",
    lastName: "Neumann",
    time: "12:30 - 13:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "12:30",
    endTime: "13:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 17,
    memberId: 17,
    name: "Sandy",
    lastName: "Schwarz",
    time: "12:30 - 13:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "12:30",
    endTime: "13:00",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 18,
    memberId: 18,
    name: "Ann-Kathrin",
    lastName: "Braun",
    time: "13:00 - 13:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "13:00",
    endTime: "13:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 19,
    memberId: 19,
    name: "Katharina",
    lastName: "Zimmermann",
    time: "13:00 - 14:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#06b6d4]",
    startTime: "13:00",
    endTime: "14:00",
    type: "Probetraining",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: true,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 20,
    memberId: 20,
    name: "Joanna",
    lastName: "Krüger",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 21,
    memberId: 21,
    name: "Iris",
    lastName: "Hartmann",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 22,
    memberId: 22,
    name: "Jürgen",
    lastName: "Lange",
    time: "14:00 - 14:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 23,
    memberId: 23,
    name: "Corinna",
    lastName: "Werner",
    time: "14:30 - 15:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:30",
    endTime: "15:00",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 24,
    memberId: 24,
    name: "Anzi",
    lastName: "Pfeiffer",
    time: "14:30 - 15:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "14:30",
    endTime: "15:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 25,
    memberId: 25,
    name: "Gabriela",
    lastName: "Herrmann",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 26,
    memberId: 26,
    name: "Stefanie",
    lastName: "König",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 27,
    memberId: 27,
    name: "Gabriele",
    lastName: "Meyer",
    time: "15:00 - 15:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f59e0b]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 28,
    memberId: 28,
    name: "Aylin",
    lastName: "Öztürk",
    time: "15:30 - 16:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "15:30",
    endTime: "16:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 29,
    memberId: 29,
    name: "Conrad",
    lastName: "Lehmann",
    time: "15:30 - 16:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "15:30",
    endTime: "16:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 30,
    memberId: 30,
    name: "Michael",
    lastName: "Müller",
    time: "16:00 - 16:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:00",
    endTime: "16:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 31,
    memberId: 31,
    name: "Ralf",
    lastName: "Schneider",
    time: "16:00 - 16:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:00",
    endTime: "16:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 32,
    memberId: 32,
    name: "Sarah",
    lastName: "Zimmermann",
    time: "16:30 - 17:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "16:30",
    endTime: "17:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 33,
    memberId: 33,
    name: "Sabrina",
    lastName: "Krause",
    time: "16:30 - 17:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "16:30",
    endTime: "17:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 34,
    memberId: 34,
    name: "Nadine",
    lastName: "Schmitt",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 35,
    memberId: 35,
    name: "Jana",
    lastName: "Becker",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Cardio",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 36,
    memberId: 36,
    name: "Andreas",
    lastName: "Fischer",
    time: "17:00 - 17:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "17:00",
    endTime: "17:30",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 37,
    memberId: 37,
    name: "Nicole",
    lastName: "Schmidt",
    time: "17:30 - 18:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#22c55e]",
    startTime: "17:30",
    endTime: "18:00",
    type: "Yoga",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 38,
    memberId: 38,
    name: "Irene",
    lastName: "Wagner",
    time: "17:30 - 18:00",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "17:30",
    endTime: "18:00",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 39,
    memberId: 39,
    name: "Past User 1",
    lastName: "Thompson",
    time: "08:00 - 08:30",
    date: "Sun | 02-02-2025",
    color: "bg-[#4169E1]",
    startTime: "08:00",
    endTime: "08:30",
    type: "Strength Training",
    specialNote: { text: "Completed session", startDate: null, endDate: null, isImportant: false },
    status: "completed",
    isTrial: false,
    isCancelled: false,
    isPast: true,
  },
  {
    id: 40,
    memberId: 40,
    name: "Past User 2",
    lastName: "Anderson",
    time: "09:00 - 09:30",
    date: "Sun | 02-02-2025",
    color: "bg-[#22c55e]",
    startTime: "09:00",
    endTime: "09:30",
    type: "Cardio",
    specialNote: { text: "Completed session", startDate: null, endDate: null, isImportant: false },
    status: "completed",
    isTrial: false,
    isCancelled: false,
    isPast: true,
  },
  {
    id: 41,
    memberId: 41,
    name: "Cancelled User 1",
    lastName: "Roberts",
    time: "10:00 - 10:30",
    date: "Mon | 03-02-2025",
    color: "bg-[#f97316]",
    startTime: "10:00",
    endTime: "10:30",
    type: "Yoga",
    specialNote: { text: "Client cancelled due to illness", startDate: null, endDate: null, isImportant: true },
    status: "cancelled",
    isTrial: false,
    isCancelled: true,
    isPast: false,
  },
  {
    id: 42,
    memberId: 42,
    name: "Cancelled User 2",
    lastName: "Martinez",
    time: "11:00 - 11:30",
    date: "Tue | 04-02-2025",
    color: "bg-[#8b5cf6]",
    startTime: "11:00",
    endTime: "11:30",
    type: "Personal Training",
    specialNote: { text: "Trainer unavailable", startDate: null, endDate: null, isImportant: true },
    status: "cancelled",
    isTrial: false,
    isCancelled: true,
    isPast: false,
  },
  {
    id: 43,
    memberId: null,
    name: "Blocked Slot",
    lastName: "",
    time: "14:00 - 15:00",
    date: "Wed | 05-02-2025",
    color: "bg-[#FF4D4F]",
    startTime: "14:00",
    endTime: "15:00",
    type: "Blocked Time",
    specialNote: { text: "Facility maintenance", startDate: null, endDate: null, isImportant: true },
    status: "blocked",
    isTrial: false,
    isCancelled: false,
    isPast: false,
    isBlocked: true,
  },
  {
    id: 44,
    memberId: 44,
    name: "Alice",
    lastName: "Johnson",
    time: "09:00 - 09:45",
    date: "Mon | 08-05-2025",
    color: "bg-[#3F74FF]",
    startTime: "09:00",
    endTime: "09:45",
    type: "Cardio",
    specialNote: { text: "First session with new trainer", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 45,
    memberId: 45,
    name: "Bob",
    lastName: "Williams",
    time: "10:00 - 11:00",
    date: "Tue | 08-06-2025",
    color: "bg-[#FF843E]",
    startTime: "10:00",
    endTime: "11:00",
    type: "Strength Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 46,
    memberId: 46,
    name: "Charlie",
    lastName: "Brown",
    time: "11:30 - 12:30",
    date: "Wed | 08-07-2025",
    color: "bg-[#50C878]",
    startTime: "11:30",
    endTime: "12:30",
    type: "Yoga",
    specialNote: { text: "Advanced poses focus", startDate: null, endDate: null, isImportant: true },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 47,
    memberId: 47,
    name: "Diana",
    lastName: "Davis",
    time: "14:00 - 14:30",
    date: "Thu | 08-08-2025",
    color: "bg-[#8b5cf6]",
    startTime: "14:00",
    endTime: "14:30",
    type: "Personal Training",
    specialNote: { text: "", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 48,
    memberId: 48,
    name: "Eve",
    lastName: "Miller",
    time: "15:00 - 15:30",
    date: "Fri | 08-09-2025",
    color: "bg-[#06b6d4]",
    startTime: "15:00",
    endTime: "15:30",
    type: "Cardio",
    specialNote: { text: "Treadmill interval training", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 49,
    memberId: 49,
    name: "Frank",
    lastName: "Wilson",
    time: "16:00 - 17:00",
    date: "Mon | 08-12-2025",
    color: "bg-[#f59e0b]",
    startTime: "16:00",
    endTime: "17:00",
    type: "Strength Training",
    specialNote: { text: "Upper body focus", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 50,
    memberId: 50,
    name: "Grace",
    lastName: "Moore",
    time: "17:30 - 18:30",
    date: "Tue | 08-13-2025",
    color: "bg-[#ef4444]",
    startTime: "17:30",
    endTime: "18:30",
    type: "Yoga",
    specialNote: { text: "Restorative yoga", startDate: null, endDate: null, isImportant: false },
    status: "pending",
    isTrial: false,
    isCancelled: false,
    isPast: false,
  },
];

// membersData.js
export const membersData = [
  {
    id: 1,
    firstName: "Yolanda",
    lastName: "Martinez",
    title: "Yolanda",
    email: "yolanda@example.com",
    phone: "+1234567890",
    street: "123 Main St",
    zipCode: "12345",
    city: "New York",
    image: null,
    isActive: true,
    note: "Prefers morning sessions",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1990-05-15",
    about: "Fitness enthusiast with a passion for strength training.",
    joinDate: "2022-03-01",
    contractStart: "2022-03-01",
    contractEnd: "2025-03-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M001",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-1-1",
        name: "Medical Clearance Certificate.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadDate: "2023-01-15",
        category: "medical",
      }
    ],
  },
  {
    id: 2,
    firstName: "Denis",
    lastName: "Schmidt",
    title: "Denis",
    email: "denis.schmidt@example.com",
    phone: "+1234567891",
    street: "456 Oak St",
    zipCode: "67890",
    city: "Los Angeles",
    image: null,
    isActive: true,
    note: "Loves cardio workouts",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1985-08-22",
    about: "Marathon runner and cardio specialist.",
    joinDate: "2021-11-15",
    contractStart: "2021-11-15",
    contractEnd: "2025-04-15",
    // Added missing fields
    country: "United States",
    memberNumber: "M002",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-2-1",
        name: "Health Declaration.pdf",
        type: "pdf",
        size: "0.7 MB",
        uploadDate: "2021-11-20",
        category: "medical",
      }
    ],
  },
  {
    id: 3,
    firstName: "Nicole",
    lastName: "Weber",
    title: "Nicole",
    email: "nicole.weber@example.com",
    phone: "+1234567892",
    street: "789 Pine St",
    zipCode: "54321",
    city: "Chicago",
    image: null,
    isActive: true,
    note: "Yoga instructor background",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1992-03-10",
    about: "Certified yoga instructor with 5 years experience.",
    joinDate: "2022-01-01",
    contractStart: "2022-01-01",
    contractEnd: "2025-01-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M003",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-3-1",
        name: "Marathon Training Plan.pdf",
        type: "pdf",
        size: "3.2 MB",
        uploadDate: "2022-07-01",
        category: "fitness",
      }
    ],
  },
  {
    id: 4,
    firstName: "Melanie",
    lastName: "Fischer",
    title: "Melanie",
    email: "melanie.fischer@example.com",
    phone: "+1234567893",
    street: "321 Elm St",
    zipCode: "98765",
    city: "Miami",
    image: null,
    isActive: true,
    note: "Personal training focused",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-07-25",
    about: "Dedicated to personal fitness goals.",
    joinDate: "2022-06-01",
    contractStart: "2022-06-01",
    contractEnd: "2025-06-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M004",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 5,
    firstName: "Angela",
    lastName: "Hoffmann",
    title: "Angela",
    email: "angela.hoffmann@example.com",
    phone: "+1234567894",
    street: "654 Maple Ave",
    zipCode: "13579",
    city: "Seattle",
    image: null,
    isActive: true,
    note: "Strength training enthusiast",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1991-12-05",
    about: "Powerlifter and strength training coach.",
    joinDate: "2022-02-15",
    contractStart: "2022-02-15",
    contractEnd: "2025-02-15",
    // Added missing fields
    country: "United States",
    memberNumber: "M005",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 6,
    firstName: "Kristina",
    lastName: "Becker",
    title: "Kristina",
    email: "kristina.becker@example.com",
    phone: "+1234567895",
    street: "987 Cedar Rd",
    zipCode: "24680",
    city: "Denver",
    image: null,
    isActive: true,
    note: "Cardio specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1989-04-18",
    about: "Cardio enthusiast and fitness model.",
    joinDate: "2022-04-01",
    contractStart: "2022-04-01",
    contractEnd: "2025-04-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M006",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 7,
    firstName: "Melanie",
    lastName: "Schulz",
    title: "Melanie",
    email: "melanie.schulz@example.com",
    phone: "+1234567896",
    street: "147 Birch St",
    zipCode: "36912",
    city: "Boston",
    image: null,
    isActive: true,
    note: "Yoga practitioner",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1987-09-30",
    about: "Yoga instructor with meditation expertise.",
    joinDate: "2022-05-01",
    contractStart: "2022-05-01",
    contractEnd: "2025-05-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M007",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 8,
    firstName: "Annett",
    lastName: "Koch",
    title: "Annett",
    email: "annett.koch@example.com",
    phone: "+1234567897",
    street: "258 Spruce Ave",
    zipCode: "47103",
    city: "Phoenix",
    image: null,
    isActive: true,
    note: "Personal training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1993-11-12",
    about: "Personal trainer and fitness coach.",
    joinDate: "2022-07-01",
    contractStart: "2022-07-01",
    contractEnd: "2025-07-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M008",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 9,
    firstName: "Justin",
    lastName: "Bauer",
    title: "Justin",
    email: "justin.bauer@example.com",
    phone: "+1234567898",
    street: "369 Willow Dr",
    zipCode: "58214",
    city: "Portland",
    image: null,
    isActive: true,
    note: "Strength training",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1986-02-28",
    about: "Strength and conditioning specialist.",
    joinDate: "2022-08-01",
    contractStart: "2022-08-01",
    contractEnd: "2025-08-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M009",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 10,
    firstName: "Michel",
    lastName: "Wagner",
    title: "Michel",
    email: "michel.wagner@example.com",
    phone: "+1234567899",
    street: "741 Poplar St",
    zipCode: "69325",
    city: "Austin",
    image: null,
    isActive: true,
    note: "Cardio and endurance",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1990-06-14",
    about: "Endurance athlete and marathon runner.",
    joinDate: "2022-09-01",
    contractStart: "2022-09-01",
    contractEnd: "2025-09-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M010",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 11,
    firstName: "Colin",
    lastName: "Richter",
    title: "Colin",
    email: "colin.richter@example.com",
    phone: "+1234567800",
    street: "852 Ash Ave",
    zipCode: "70436",
    city: "Nashville",
    image: null,
    isActive: true,
    note: "Strength training specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1984-10-07",
    about: "Powerlifting competitor and coach.",
    joinDate: "2022-10-01",
    contractStart: "2022-10-01",
    contractEnd: "2025-10-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M011",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 12,
    firstName: "Yvonne",
    lastName: "Klein",
    title: "Yvonne",
    email: "yvonne.klein@example.com",
    phone: "+1234567801",
    street: "963 Hickory Rd",
    zipCode: "81547",
    city: "San Diego",
    image: null,
    isActive: true,
    note: "Yoga and flexibility",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1991-01-20",
    about: "Yoga instructor and flexibility coach.",
    joinDate: "2022-11-01",
    contractStart: "2022-11-01",
    contractEnd: "2025-11-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M012",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 13,
    firstName: "Jennifer",
    lastName: "Wolf",
    title: "Jennifer",
    email: "jennifer.wolf@example.com",
    phone: "+1234567802",
    street: "174 Walnut St",
    zipCode: "92658",
    city: "Las Vegas",
    image: null,
    isActive: true,
    note: "Personal training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1987-05-03",
    about: "Certified personal trainer and nutritionist.",
    joinDate: "2022-12-01",
    contractStart: "2022-12-01",
    contractEnd: "2025-12-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M013",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 14,
    firstName: "Michael",
    lastName: "Schröder",
    title: "Michael",
    email: "michael.schroder@example.com",
    phone: "+1234567803",
    street: "285 Cherry Ave",
    zipCode: "03769",
    city: "Salt Lake City",
    image: null,
    isActive: true,
    note: "Cardio enthusiast",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1994-08-16",
    about: "Marathon runner and cardio specialist.",
    joinDate: "2023-01-01",
    contractStart: "2023-01-01",
    contractEnd: "2026-01-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M014",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 15,
    firstName: "Furkan",
    lastName: "Yilmaz",
    title: "Furkan",
    email: "furkan.yilmaz@example.com",
    phone: "+1234567804",
    street: "396 Peach Dr",
    zipCode: "14870",
    city: "Minneapolis",
    image: null,
    isActive: true,
    note: "Strength training focus",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1983-12-29",
    about: "Bodybuilder and fitness enthusiast.",
    joinDate: "2023-02-01",
    contractStart: "2023-02-01",
    contractEnd: "2026-02-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M015",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 16,
    firstName: "Heike",
    lastName: "Neumann",
    title: "Heike",
    email: "heike.neumann@example.com",
    phone: "+1234567805",
    street: "507 Orange St",
    zipCode: "25981",
    city: "Tampa",
    image: null,
    isActive: true,
    note: "Yoga specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1989-03-22",
    about: "Advanced yoga practitioner and teacher.",
    joinDate: "2023-03-01",
    contractStart: "2023-03-01",
    contractEnd: "2026-03-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M016",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 17,
    firstName: "Sandy",
    lastName: "Schwarz",
    title: "Sandy",
    email: "sandy.schwarz@example.com",
    phone: "+1234567806",
    street: "618 Lemon Ave",
    zipCode: "36092",
    city: "Orlando",
    image: null,
    isActive: true,
    note: "Personal training specialist",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1992-07-08",
    about: "Certified personal trainer with sports background.",
    joinDate: "2023-04-01",
    contractStart: "2023-04-01",
    contractEnd: "2026-04-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M017",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 18,
    firstName: "Ann-Kathrin",
    lastName: "Braun",
    title: "Ann-Kathrin",
    email: "annkathrin.braun@example.com",
    phone: "+1234567807",
    street: "729 Grape Dr",
    zipCode: "47103",
    city: "Jacksonville",
    image: null,
    isActive: true,
    note: "Cardio and fitness",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1995-11-15",
    about: "Fitness instructor and cardio specialist.",
    joinDate: "2023-05-01",
    contractStart: "2023-05-01",
    contractEnd: "2026-05-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M018",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 19,
    firstName: "Katharina",
    lastName: "Zimmermann",
    title: "Katharina",
    email: "katharina.zimmermann@example.com",
    phone: "+1234567808",
    street: "101 Wonderland Rd",
    zipCode: "10101",
    city: "Fairyland",
    image: null,
    isActive: true,
    note: "Trial training participant",
    noteStartDate: "2024-01-01",
    noteEndDate: "2025-12-31",
    noteImportance: "important",
    dateOfBirth: "1998-01-01",
    about: "New member interested in comprehensive fitness program.",
    joinDate: "2024-01-01",
    contractStart: "2024-01-01",
    contractEnd: "2027-01-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M019",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 20,
    firstName: "Joanna",
    lastName: "Krüger",
    title: "Joanna",
    email: "joanna.krueger@example.com",
    phone: "+1234567809",
    street: "202 Construction St",
    zipCode: "20202",
    city: "Buildville",
    image: null,
    isActive: true,
    note: "Focus on strength gains",
    noteStartDate: "2024-02-01",
    noteEndDate: "2026-02-28",
    noteImportance: "important",
    dateOfBirth: "1980-02-02",
    about: "Dedicated to building muscle and endurance.",
    joinDate: "2024-02-01",
    contractStart: "2024-02-01",
    contractEnd: "2027-02-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M020",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 21,
    firstName: "Iris",
    lastName: "Hartmann",
    title: "Iris",
    email: "iris.hartmann@example.com",
    phone: "+1234567810",
    street: "303 Silent Film Ave",
    zipCode: "30303",
    city: "Hollywood",
    image: null,
    isActive: true,
    note: "Prefers evening yoga",
    noteStartDate: "2024-03-01",
    noteEndDate: "2025-03-31",
    noteImportance: "unimportant",
    dateOfBirth: "1995-03-03",
    about: "Enjoys flexibility and mindfulness through yoga.",
    joinDate: "2024-03-01",
    contractStart: "2024-03-01",
    contractEnd: "2027-03-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M021",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 22,
    firstName: "Jürgen",
    lastName: "Lange",
    title: "Jürgen",
    email: "jurgen.lange@example.com",
    phone: "+1234567811",
    street: "404 Amazonian Way",
    zipCode: "40404",
    city: "Themyscira",
    image: null,
    isActive: true,
    note: "Personal training for combat readiness",
    noteStartDate: "2024-04-01",
    noteEndDate: "2026-04-30",
    noteImportance: "important",
    dateOfBirth: "1984-04-04",
    about: "Seeking to maintain peak physical condition.",
    joinDate: "2024-04-01",
    contractStart: "2024-04-01",
    contractEnd: "2027-04-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M022",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 23,
    firstName: "Corinna",
    lastName: "Werner",
    title: "Corinna",
    email: "corinna.werner@example.com",
    phone: "+1234567812",
    street: "505 Garden of Eden",
    zipCode: "50505",
    city: "Paradise",
    image: null,
    isActive: true,
    note: "Loves outdoor cardio",
    noteStartDate: "2024-05-01",
    noteEndDate: "2025-05-31",
    noteImportance: "unimportant",
    dateOfBirth: "1992-05-05",
    about: "Enjoys running and high-intensity cardio.",
    joinDate: "2024-05-01",
    contractStart: "2024-05-01",
    contractEnd: "2027-05-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M023",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 24,
    firstName: "Anzi",
    lastName: "Pfeiffer",
    title: "Anzi",
    email: "anzi.pfeiffer@example.com",
    phone: "+1234567813",
    street: "606 Crooner's Lane",
    zipCode: "60606",
    city: "Las Vegas",
    image: null,
    isActive: true,
    note: "Strength training for stage presence",
    noteStartDate: "2024-06-01",
    noteEndDate: "2026-06-30",
    noteImportance: "important",
    dateOfBirth: "1970-06-06",
    about: "Keeping fit for performances.",
    joinDate: "2024-06-01",
    contractStart: "2024-06-01",
    contractEnd: "2027-06-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M024",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 25,
    firstName: "Gabriela",
    lastName: "Herrmann",
    title: "Gabriela",
    email: "gabriela.herrmann@example.com",
    phone: "+1234567814",
    street: "707 Royal Palace",
    zipCode: "70707",
    city: "Monaco",
    image: null,
    isActive: true,
    note: "Gentle yoga for relaxation",
    noteStartDate: "2024-07-01",
    noteEndDate: "2025-07-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-07-07",
    about: "Seeks balance and tranquility through yoga.",
    joinDate: "2024-07-01",
    contractStart: "2024-07-01",
    contractEnd: "2027-07-01",
    // Added missing fields
    country: "Monaco",
    memberNumber: "M025",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 26,
    firstName: "Stefanie",
    lastName: "König",
    title: "Stefanie",
    email: "stefanie.koenig@example.com",
    phone: "+1234567815",
    street: "808 König St",
    zipCode: "80808",
    city: "Berlin",
    image: null,
    isActive: true,
    note: "Personal training enthusiast",
    noteStartDate: "2024-08-01",
    noteEndDate: "2025-08-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-03-15",
    about: "Enjoys personal training sessions.",
    joinDate: "2024-08-01",
    contractStart: "2024-08-01",
    contractEnd: "2027-08-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M026",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 27,
    firstName: "Gabriele",
    lastName: "Meyer",
    title: "Gabriele",
    email: "gabriele.meyer@example.com",
    phone: "+1234567816",
    street: "909 Meyer St",
    zipCode: "90909",
    city: "Hamburg",
    image: null,
    isActive: true,
    note: "Cardio lover",
    noteStartDate: "2024-09-01",
    noteEndDate: "2025-09-30",
    noteImportance: "unimportant",
    dateOfBirth: "1990-07-20",
    about: "Enjoys running and cardio exercises.",
    joinDate: "2024-09-01",
    contractStart: "2024-09-01",
    contractEnd: "2027-09-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M027",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 28,
    firstName: "Aylin",
    lastName: "Öztürk",
    title: "Aylin",
    email: "aylin.ozturk@example.com",
    phone: "+1234567817",
    street: "1010 Öztürk St",
    zipCode: "101010",
    city: "Istanbul",
    image: null,
    isActive: true,
    note: "Strength training focus",
    noteStartDate: "2024-10-01",
    noteEndDate: "2025-10-31",
    noteImportance: "important",
    dateOfBirth: "1993-09-12",
    about: "Strength training enthusiast.",
    joinDate: "2024-10-01",
    contractStart: "2024-10-01",
    contractEnd: "2027-10-01",
    // Added missing fields
    country: "Turkey",
    memberNumber: "M028",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 29,
    firstName: "Conrad",
    lastName: "Lehmann",
    title: "Conrad",
    email: "conrad.lehmann@example.com",
    phone: "+1234567818",
    street: "1111 Lehmann St",
    zipCode: "111111",
    city: "Munich",
    image: null,
    isActive: true,
    note: "Yoga practitioner",
    noteStartDate: "2024-11-01",
    noteEndDate: "2025-11-30",
    noteImportance: "unimportant",
    dateOfBirth: "1985-04-18",
    about: "Yoga and meditation enthusiast.",
    joinDate: "2024-11-01",
    contractStart: "2024-11-01",
    contractEnd: "2027-11-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M029",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 30,
    firstName: "Michael",
    lastName: "Müller",
    title: "Michael",
    email: "michael.mueller@example.com",
    phone: "+1234567819",
    street: "1212 Müller St",
    zipCode: "121212",
    city: "Frankfurt",
    image: null,
    isActive: true,
    note: "Personal training focus",
    noteStartDate: "2024-12-01",
    noteEndDate: "2025-12-31",
    noteImportance: "important",
    dateOfBirth: "1982-11-25",
    about: "Personal training for fitness goals.",
    joinDate: "2024-12-01",
    contractStart: "2024-12-01",
    contractEnd: "2027-12-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M030",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 31,
    firstName: "Ralf",
    lastName: "Schneider",
    title: "Ralf",
    email: "ralf.schneider@example.com",
    phone: "+1234567820",
    street: "1313 Schneider St",
    zipCode: "131313",
    city: "Cologne",
    image: null,
    isActive: true,
    note: "Cardio specialist",
    noteStartDate: "2025-01-01",
    noteEndDate: "2026-01-31",
    noteImportance: "unimportant",
    dateOfBirth: "1978-08-08",
    about: "Marathon runner and cardio coach.",
    joinDate: "2025-01-01",
    contractStart: "2025-01-01",
    contractEnd: "2028-01-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M031",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 32,
    firstName: "Sarah",
    lastName: "Zimmermann",
    title: "Sarah",
    email: "sarah.zimmermann@example.com",
    phone: "+1234567821",
    street: "1414 Zimmermann St",
    zipCode: "141414",
    city: "Dresden",
    image: null,
    isActive: true,
    note: "Strength training",
    noteStartDate: "2025-02-01",
    noteEndDate: "2026-02-28",
    noteImportance: "important",
    dateOfBirth: "1991-02-14",
    about: "Strength and conditioning coach.",
    joinDate: "2025-02-01",
    contractStart: "2025-02-01",
    contractEnd: "2028-02-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M032",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 33,
    firstName: "Sabrina",
    lastName: "Krause",
    title: "Sabrina",
    email: "sabrina.krause@example.com",
    phone: "+1234567822",
    street: "1515 Krause St",
    zipCode: "151515",
    city: "Leipzig",
    image: null,
    isActive: true,
    note: "Yoga instructor",
    noteStartDate: "2025-03-01",
    noteEndDate: "2026-03-31",
    noteImportance: "unimportant",
    dateOfBirth: "1989-06-30",
    about: "Certified yoga instructor.",
    joinDate: "2025-03-01",
    contractStart: "2025-03-01",
    contractEnd: "2028-03-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M033",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 34,
    firstName: "Nadine",
    lastName: "Schmitt",
    title: "Nadine",
    email: "nadine.schmitt@example.com",
    phone: "+1234567823",
    street: "1616 Schmitt St",
    zipCode: "161616",
    city: "Stuttgart",
    image: null,
    isActive: true,
    note: "Personal training",
    noteStartDate: "2025-04-01",
    noteEndDate: "2026-04-30",
    noteImportance: "important",
    dateOfBirth: "1990-12-10",
    about: "Personal trainer specializing in weight loss.",
    joinDate: "2025-04-01",
    contractStart: "2025-04-01",
    contractEnd: "2028-04-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M034",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 35,
    firstName: "Jana",
    lastName: "Becker",
    title: "Jana",
    email: "jana.becker@example.com",
    phone: "+1234567824",
    street: "1717 Becker St",
    zipCode: "171717",
    city: "Düsseldorf",
    image: null,
    isActive: true,
    note: "Cardio enthusiast",
    noteStartDate: "2025-05-01",
    noteEndDate: "2026-05-31",
    noteImportance: "unimportant",
    dateOfBirth: "1987-05-22",
    about: "Running and cycling enthusiast.",
    joinDate: "2025-05-01",
    contractStart: "2025-05-01",
    contractEnd: "2028-05-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M035",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 36,
    firstName: "Andreas",
    lastName: "Fischer",
    title: "Andreas",
    email: "andreas.fischer@example.com",
    phone: "+1234567825",
    street: "1818 Fischer St",
    zipCode: "181818",
    city: "Hannover",
    image: null,
    isActive: true,
    note: "Strength training",
    noteStartDate: "2025-06-01",
    noteEndDate: "2026-06-30",
    noteImportance: "important",
    dateOfBirth: "1984-03-17",
    about: "Bodybuilding competitor.",
    joinDate: "2025-06-01",
    contractStart: "2025-06-01",
    contractEnd: "2028-06-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M036",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 37,
    firstName: "Nicole",
    lastName: "Schmidt",
    title: "Nicole",
    email: "nicole.schmidt@example.com",
    phone: "+1234567826",
    street: "1919 Schmidt St",
    zipCode: "191919",
    city: "Nuremberg",
    image: null,
    isActive: true,
    note: "Yoga and meditation",
    noteStartDate: "2025-07-01",
    noteEndDate: "2026-07-31",
    noteImportance: "unimportant",
    dateOfBirth: "1992-08-25",
    about: "Mindfulness and yoga practitioner.",
    joinDate: "2025-07-01",
    contractStart: "2025-07-01",
    contractEnd: "2028-07-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M037",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 38,
    firstName: "Irene",
    lastName: "Wagner",
    title: "Irene",
    email: "irene.wagner@example.com",
    phone: "+1234567827",
    street: "2020 Wagner St",
    zipCode: "202020",
    city: "Bremen",
    image: null,
    isActive: true,
    note: "Personal training",
    noteStartDate: "2025-08-01",
    noteEndDate: "2026-08-31",
    noteImportance: "important",
    dateOfBirth: "1980-10-05",
    about: "Senior fitness trainer.",
    joinDate: "2025-08-01",
    contractStart: "2025-08-01",
    contractEnd: "2028-08-01",
    // Added missing fields
    country: "Germany",
    memberNumber: "M038",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 39,
    firstName: "Past User 1",
    lastName: "Thompson",
    title: "Past User 1",
    email: "pastuser1@example.com",
    phone: "+1234567828",
    street: "2121 Past St",
    zipCode: "212121",
    city: "Old City",
    image: null,
    isActive: false,
    note: "Completed sessions",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1980-01-01",
    about: "Former member who has completed sessions.",
    joinDate: "2022-01-01",
    contractStart: "2022-01-01",
    contractEnd: "2023-12-31",
    // Added missing fields
    country: "United States",
    memberNumber: "M039",
    gender: "male",
    reason: "Completed contract",
    isArchived: true,
    memberType: "full",
    autoArchiveDate: "2023-12-31",
    documents: [],
  },
  {
    id: 40,
    firstName: "Past User 2",
    lastName: "Anderson",
    title: "Past User 2",
    email: "pastuser2@example.com",
    phone: "+1234567829",
    street: "2222 Past St",
    zipCode: "222222",
    city: "Old Town",
    image: null,
    isActive: false,
    note: "Completed sessions",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1982-02-02",
    about: "Former member who has completed sessions.",
    joinDate: "2022-02-01",
    contractStart: "2022-02-01",
    contractEnd: "2023-12-31",
    // Added missing fields
    country: "United States",
    memberNumber: "M040",
    gender: "male",
    reason: "Completed contract",
    isArchived: true,
    memberType: "full",
    autoArchiveDate: "2023-12-31",
    documents: [],
  },
  {
    id: 41,
    firstName: "Cancelled User 1",
    lastName: "Roberts",
    title: "Cancelled User 1",
    email: "cancelled1@example.com",
    phone: "+1234567830",
    street: "2323 Cancel St",
    zipCode: "232323",
    city: "Cancel City",
    image: null,
    isActive: false,
    note: "Client cancelled due to illness",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1985-05-15",
    about: "Former member who cancelled membership.",
    joinDate: "2022-03-01",
    contractStart: "2022-03-01",
    contractEnd: "2023-03-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M041",
    gender: "female",
    reason: "Illness",
    isArchived: true,
    memberType: "full",
    autoArchiveDate: "2023-03-01",
    documents: [],
  },
  {
    id: 42,
    firstName: "Cancelled User 2",
    lastName: "Martinez",
    title: "Cancelled User 2",
    email: "cancelled2@example.com",
    phone: "+1234567831",
    street: "2424 Cancel St",
    zipCode: "242424",
    city: "Cancel Town",
    image: null,
    isActive: false,
    note: "Trainer unavailable",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1990-08-20",
    about: "Former member who cancelled due to trainer issues.",
    joinDate: "2022-04-01",
    contractStart: "2022-04-01",
    contractEnd: "2023-04-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M042",
    gender: "female",
    reason: "Trainer unavailable",
    isArchived: true,
    memberType: "full",
    autoArchiveDate: "2023-04-01",
    documents: [],
  },
  {
    id: 43,
    firstName: "Blocked Slot",
    lastName: "",
    title: "Blocked Slot",
    email: "",
    phone: "",
    street: "",
    zipCode: "",
    city: "",
    image: null,
    isActive: false,
    note: "Facility maintenance",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "",
    about: "Blocked time slot for maintenance.",
    joinDate: "",
    contractStart: "",
    contractEnd: "",
    // Added missing fields
    country: "",
    memberNumber: "BLOCK001",
    gender: "",
    reason: "Maintenance",
    isArchived: false,
    memberType: "blocked",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 44,
    firstName: "Alice",
    lastName: "Johnson",
    title: "Alice",
    email: "alice.johnson@example.com",
    phone: "+1234567832",
    street: "2525 Johnson St",
    zipCode: "252525",
    city: "New York",
    image: null,
    isActive: true,
    note: "First session with new trainer",
    noteStartDate: "2024-01-01",
    noteEndDate: "2025-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1995-04-10",
    about: "New member starting cardio training.",
    joinDate: "2024-01-01",
    contractStart: "2024-01-01",
    contractEnd: "2027-01-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M044",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 45,
    firstName: "Bob",
    lastName: "Williams",
    title: "Bob",
    email: "bob.williams@example.com",
    phone: "+1234567833",
    street: "2626 Williams St",
    zipCode: "262626",
    city: "Chicago",
    image: null,
    isActive: true,
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1988-09-18",
    about: "Strength training enthusiast.",
    joinDate: "2024-02-01",
    contractStart: "2024-02-01",
    contractEnd: "2027-02-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M045",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 46,
    firstName: "Charlie",
    lastName: "Brown",
    title: "Charlie",
    email: "charlie.brown@example.com",
    phone: "+1234567834",
    street: "2727 Brown St",
    zipCode: "272727",
    city: "Los Angeles",
    image: null,
    isActive: true,
    note: "Advanced poses focus",
    noteStartDate: "2024-03-01",
    noteEndDate: "2025-03-31",
    noteImportance: "important",
    dateOfBirth: "1992-11-30",
    about: "Advanced yoga practitioner.",
    joinDate: "2024-03-01",
    contractStart: "2024-03-01",
    contractEnd: "2027-03-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M046",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 47,
    firstName: "Diana",
    lastName: "Davis",
    title: "Diana",
    email: "diana.davis@example.com",
    phone: "+1234567835",
    street: "2828 Davis St",
    zipCode: "282828",
    city: "Miami",
    image: null,
    isActive: true,
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1990-06-15",
    about: "Personal training client.",
    joinDate: "2024-04-01",
    contractStart: "2024-04-01",
    contractEnd: "2027-04-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M047",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 48,
    firstName: "Eve",
    lastName: "Miller",
    title: "Eve",
    email: "eve.miller@example.com",
    phone: "+1234567836",
    street: "2929 Miller St",
    zipCode: "292929",
    city: "Seattle",
    image: null,
    isActive: true,
    note: "Treadmill interval training",
    noteStartDate: "2024-05-01",
    noteEndDate: "2025-05-31",
    noteImportance: "unimportant",
    dateOfBirth: "1987-12-05",
    about: "Cardio training specialist.",
    joinDate: "2024-05-01",
    contractStart: "2024-05-01",
    contractEnd: "2027-05-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M048",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 49,
    firstName: "Frank",
    lastName: "Wilson",
    title: "Frank",
    email: "frank.wilson@example.com",
    phone: "+1234567837",
    street: "3030 Wilson St",
    zipCode: "303030",
    city: "Denver",
    image: null,
    isActive: true,
    note: "Upper body focus",
    noteStartDate: "2024-06-01",
    noteEndDate: "2025-06-30",
    noteImportance: "unimportant",
    dateOfBirth: "1983-03-22",
    about: "Strength training for upper body.",
    joinDate: "2024-06-01",
    contractStart: "2024-06-01",
    contractEnd: "2027-06-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M049",
    gender: "male",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 50,
    firstName: "Grace",
    lastName: "Moore",
    title: "Grace",
    email: "grace.moore@example.com",
    phone: "+1234567838",
    street: "3131 Moore St",
    zipCode: "313131",
    city: "Phoenix",
    image: null,
    isActive: true,
    note: "Restorative yoga",
    noteStartDate: "2024-07-01",
    noteEndDate: "2025-07-31",
    noteImportance: "unimportant",
    dateOfBirth: "1991-07-19",
    about: "Restorative yoga practitioner.",
    joinDate: "2024-07-01",
    contractStart: "2024-07-01",
    contractEnd: "2027-07-01",
    // Added missing fields
    country: "United States",
    memberNumber: "M050",
    gender: "female",
    reason: "",
    isArchived: false,
    memberType: "full",
    autoArchiveDate: null,
    documents: [],
  }
];