const img1 = "/Rectangle 1.png"
const img2 = "/avatar3.png"

export const emailListNew = {
    inbox: [
        {
            id: 1,
            sender: "support@example.com",
            subject: "Your recent inquiry",
            body: "Dear user, thank you for contacting us. We have received your inquiry and will get back to you within 24 hours. Best regards, Support Team",
            time: "2025-07-18T10:00:00Z",
            isRead: false,
            isPinned: false,
            isArchived: false,
        },
        {
            id: 2,
            sender: "marketing@example.com",
            subject: "New product launch!",
            body: "Exciting news! Our new product is now available. Check it out here: [link]",
            time: "2025-07-17T15:30:00Z",
            isRead: true,
            isPinned: false,
            isArchived: false,
        },
    ],
    sent: [
        {
            id: 3,
            recipient: "jennifer@example.com",
            subject: "Meeting Reminder",
            body: "Hi Jennifer, just a friendly reminder about our meeting tomorrow at 10 AM. Please be prepared to discuss the project milestones. Thanks!",
            status: "Delivered",
            time: "2025-07-16T09:00:00Z",
            isRead: true,
            isPinned: false,
            isArchived: false,
        },
        {
            id: 4,
            recipient: "jerry@example.com",
            subject: "Event Announcement",
            body: "Hi Jerry, We're excited to announce our upcoming event! It will be held on August 1st at the community center. More details to follow soon.",
            status: "Read",
            time: "2025-07-15T14:30:00Z",
            isRead: true,
            isPinned: false,
            isArchived: false,
        },
    ],
    draft: [
        {
            id: 5,
            recipient: "draft@example.com",
            subject: "Draft Email Subject",
            body: "This is a draft email. I'll finish it later.",
            status: "Draft",
            time: "2025-07-19T11:00:00Z",
            isRead: true,
            isPinned: false,
            isArchived: false,
        },
    ],
    outbox: [],
    archive: [],
    error: [],
};

export const preConfiguredMessagesNew = [
    {
        id: 1,
        title: "Meeting Reminder",
        message: "This is a reminder about our upcoming meeting.",
        folderId: 1,
    },
    {
        id: 2,
        title: "Event Announcement",
        message: "We're excited to announce our upcoming event!",
        folderId: 2,
    },
    {
        id: 3,
        title: "Important Update",
        message: "There has been an important update to our policies.",
        folderId: 2,
    },
    {
        id: 4,
        title: "Welcome Message",
        message: "Welcome to our platform! We're glad to have you here.",
        folderId: 1,
    },
];

export const emailTemplatesNew = [
    {
        id: 1,
        name: "Welcome Email",
        subject: "Welcome to our fitness community!",
        body: "Dear {name},\n\nWelcome to our fitness community! We're excited to have you on board.\n\nBest regards,\nThe Team",
    },
    {
        id: 2,
        name: "Appointment Reminder",
        subject: "Appointment Reminder",
        body: "Dear {name},\n\nThis is a reminder about your upcoming appointment on {date} at {time}.\n\nSee you soon!",
    },
    {
        id: 3,
        name: "Class Cancellation",
        subject: "Class Cancellation Notice",
        body: "Dear {name},\n\nWe regret to inform you that the class scheduled for {date} has been cancelled.\n\nWe apologize for any inconvenience.",
    },
];

export const appointmentNotificationTypesNew = {
    confirmation: {
        enabled: true,
        template: "Hello {Member_First_Name} {Member_Last_Name}, your {Appointment_Type} has been booked for {Booked_Time}. Best wishes from {Studio_Name}!",
    },
    cancellation: {
        enabled: true,
        template: "Hello {Member_First_Name} {Member_Last_Name}, your {Appointment_Type} has been cancelled. Please contact {Studio_Name} for rescheduling.",
    },
    rescheduled: {
        enabled: true,
        template: "Hello {Member_First_Name} {Member_Last_Name}, your {Appointment_Type} has been rescheduled to {Booked_Time}. Thank you, {Studio_Name}!",
    },
};

export const settingsNew = {
    autoArchiveDuration: 30, // days
    emailNotifications: true,
    chatNotifications: true,
    studioChatNotifications: true,
    memberChatNotifications: true,
    emailSignature: "Best regards,\nYour Team",
    broadcastEmail: true,
    broadcastChat: true,
    smtpHost: "smtp.example.com",
    smtpPort: 587,
    smtpUser: "user@example.com",
    smtpPass: "password",
    birthdayMessageEnabled: true,
    birthdayMessageTemplate: "Happy Birthday, {name}!",
    appointmentNotificationEnabled: true,
    appointmentNotificationTemplate: "Reminder: You have an appointment on {date} at {time}.",
};

export const appointmentsNew = [
    {
        id: 1,
        title: "Initial Consultation",
        date: "2025-03-15T10:00",
        status: "upcoming",
        type: "Consultation",
        memberId: 1,
    },
    {
        id: 2,
        title: "Follow-up Meeting",
        date: "2025-03-20T14:30",
        status: "upcoming",
        type: "Follow-up",
        memberId: 1,
    },
    {
        id: 3,
        title: "Annual Review",
        date: "2025-04-05T11:00",
        status: "upcoming",
        type: "Annual Review",
        memberId: 2,
    },
];

export const memberContingentDataNew = {
    1: {
        current: { used: 2, total: 7 },
        future: {
            "05.14.25 - 05.18.2025": { used: 0, total: 8 },
            "06.14.25 - 06.18.2025": { used: 0, total: 8 },
            "07.14.25 - 07.18.2025": { used: 0, total: 8 },
            "08.14.25 - 08.18.2025": { used: 0, total: 8 },
            "09.14.25 - 09.18.2025": { used: 0, total: 8 },
        },
    },
    2: {
        current: { used: 1, total: 8 },
        future: {
            "05.14.25 - 05.18.2025": { used: 0, total: 8 },
            "06.14.25 - 06.18.2025": { used: 0, total: 8 },
        },
    },
    3: { current: { used: 0, total: 5 }, future: {} },
    4: { current: { used: 3, total: 10 }, future: {} },
    5: { current: { used: 0, total: 6 }, future: {} },
    100: {
        current: { used: 0, total: 0 }, // Company chat has no contingent
        future: {},
    },
};

export const membersNew = [
    {
        id: 1,
        firstName: "Jennifer",
        lastName: "Markus",
        title: "Jennifer Markus",
        email: "jennifer@example.com",
        phone: "+1234567890",
        street: "123 Main St",
        zipCode: "12345",
        city: "New York",
        // image: img1,
        isActive: true,
        isArchived: false,
        memberType: "full",
        note: "Allergic to peanuts. Prefers morning sessions.",
        noteStartDate: "2023-01-01",
        noteEndDate: "2023-12-31",
        noteImportance: "important",
        dateOfBirth: "1990-05-15",
        about: "Experienced developer with a passion for clean code.",
        joinDate: "2022-03-01",
        contractStart: "2022-03-01",
        contractEnd: "2025-03-01",
    },
    {
        id: 2,
        firstName: "Jerry",
        lastName: "Haffer",
        title: "Jerry Haffer",
        email: "jerry@example.com",
        phone: "+1234567891",
        street: "456 Oak St",
        zipCode: "67890",
        city: "Los Angeles",
        // image: img1,
        isActive: true,
        isArchived: false,
        memberType: "full",
        note: "Loves cardio workouts.",
        noteStartDate: "2023-01-01",
        noteEndDate: "2023-12-31",
        noteImportance: "unimportant",
        dateOfBirth: "1985-08-22",
        about: "Certified PMP with 10 years of experience in IT project management.",
        joinDate: "2021-11-15",
        contractStart: "2021-11-15",
        contractEnd: "2025-04-15",
    },
    {
        id: 3,
        firstName: "Group",
        lastName: "1",
        title: "Group 1",
        email: "group1@example.com",
        phone: null,
        street: null,
        zipCode: null,
        city: null,
        // image: img2,
        isActive: true,
        isArchived: false,
        memberType: "group",
        note: "General group chat for project updates.",
        noteStartDate: null,
        noteEndDate: null,
        noteImportance: "unimportant",
        dateOfBirth: null,
        about: "A group of members working on Project X.",
        joinDate: "2023-01-01",
        contractStart: null,
        contractEnd: null,
    },
    {
        id: 4,
        firstName: "David",
        lastName: "Eison",
        title: "David Eison",
        email: "david@example.com",
        phone: "+1234567893",
        street: "321 Elm St",
        zipCode: "98765",
        city: "Miami",
        // image: img2,
        isActive: true,
        isArchived: false,
        memberType: "full",
        note: "Personal training focused.",
        noteStartDate: "2023-01-01",
        noteEndDate: "2023-12-31",
        noteImportance: "unimportant",
        dateOfBirth: "1988-07-25",
        about: "Dedicated to personal fitness goals.",
        joinDate: "2022-06-01",
        contractStart: "2022-06-01",
        contractEnd: "2025-06-01",
    },
    {
        id: 5,
        firstName: "Mary",
        lastName: "Freund",
        title: "Mary Freund",
        email: "mary@example.com",
        phone: "+1234567894",
        street: "654 Maple Ave",
        zipCode: "13579",
        city: "Seattle",
        // image: img1,
        isActive: true,
        isArchived: false,
        memberType: "full",
        note: "Strength training enthusiast.",
        noteStartDate: "2023-01-01",
        noteEndDate: "2023-12-31",
        noteImportance: "important",
        dateOfBirth: "1991-12-05",
        about: "Powerlifter and strength training coach.",
        joinDate: "2022-02-15",
        contractStart: "2022-02-15",
        contractEnd: "2025-02-15",
    },
    {
        id: 100,
        firstName: "Fit Chain",
        lastName: "GmbH",
        title: "Fit Chain GmbH",
        email: "studio@fitchain.com",
        phone: null,
        street: null,
        zipCode: null,
        city: null,
        // image: img1,
        isActive: true,
        isArchived: false,
        memberType: "company",
        note: "Official studio communication channel.",
        noteStartDate: null,
        noteEndDate: null,
        noteImportance: "unimportant",
        dateOfBirth: null,
        about: "The main communication channel for Fit Chain GmbH.",
        joinDate: "2020-01-01",
        contractStart: null,
        contractEnd: null,
    },
];

export const memberRelationsNew = {
    1: {
        family: [
            { name: "Anna Doe", relation: "Mother", id: 101, type: "member" },
            { name: "Peter Doe", relation: "Father", id: 102, type: "lead" },
        ],
        friendship: [{ name: "Max Miller", relation: "Best Friend", id: 201, type: "member" }],
        relationship: [{ name: "Marie Smith", relation: "Partner", id: 301, type: "member" }],
        work: [{ name: "Tom Wilson", relation: "Colleague", id: 401, type: "lead" }],
        other: [{ name: "Mrs. Smith", relation: "Neighbor", id: 501, type: "manual" }],
    },
    2: { family: [], friendship: [], relationship: [], work: [], other: [] },
    3: { family: [], friendship: [], relationship: [], work: [], other: [] },
    4: { family: [], friendship: [], relationship: [], work: [], other: [] },
    5: { family: [], friendship: [], relationship: [], work: [], other: [] },
    100: { family: [], friendship: [], relationship: [], work: [], other: [] },
};

export const memberHistoryNew = {
    1: {
        general: [
            {
                id: 1,
                date: "2025-01-15",
                action: "Email updated",
                details: "Changed from old@email.com to jennifer@example.com",
                user: "Admin",
            },
            { id: 2, date: "2025-01-10", action: "Phone updated", details: "Updated phone number", user: "Admin" },
        ],
        checkins: [
            { id: 1, date: "2025-01-20T09:30", type: "Check-in", location: "Main Entrance", user: "Jennifer Markus" },
            { id: 2, date: "2025-01-20T11:45", type: "Check-out", location: "Main Entrance", user: "Jennifer Markus" },
        ],
        appointments: [
            { id: 1, date: "2025-01-18T10:00", title: "Personal Training", status: "completed", trainer: "Mike Johnson" },
            { id: 2, date: "2025-01-15T14:30", title: "Consultation", status: "completed", trainer: "Sarah Wilson" },
        ],
        finance: [
            {
                id: 1,
                date: "2025-01-01",
                type: "Payment",
                amount: "$99.99",
                description: "Monthly membership fee",
                status: "completed",
            },
            {
                id: 2,
                date: "2024-12-01",
                type: "Payment",
                amount: "$99.99",
                description: "Monthly membership fee",
                status: "completed",
            },
        ],
        contracts: [
            {
                id: 1,
                date: "2024-03-01",
                action: "Contract signed",
                details: "Initial 12-month membership contract",
                user: "Admin",
            },
            { id: 2, date: "2024-02-28", action: "Contract updated", details: "Extended contract duration", user: "Admin" },
        ],
    },
    2: {
        general: [
            {
                id: 1,
                date: "2025-01-12",
                action: "Profile updated",
                details: "Updated personal information",
                user: "Admin",
            },
        ],
        checkins: [
            { id: 1, date: "2025-01-19T08:00", type: "Check-in", location: "Main Entrance", user: "Jerry Haffer" },
            { id: 2, date: "2025-01-19T10:30", type: "Check-out", location: "Main Entrance", user: "Jerry Haffer" },
        ],
        appointments: [
            { id: 1, date: "2025-01-17T14:00", title: "Cardio Session", status: "completed", trainer: "Lisa Davis" },
        ],
        finance: [
            {
                id: 1,
                date: "2025-01-01",
                type: "Payment",
                amount: "$89.99",
                description: "Monthly membership fee",
                status: "completed",
            },
        ],
        contracts: [
            {
                id: 1,
                date: "2021-11-15",
                action: "Contract signed",
                details: "Initial membership contract",
                user: "Admin",
            },
        ],
    },
    3: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
    4: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
    5: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
    100: { general: [], checkins: [], appointments: [], finance: [], contracts: [] },
};

export const staffChatListNew = [
    {
        id: 1,
        name: "Jennifer Markus",
        time: "Today | 05:30 PM",
        active: true,
        message: "Hey! Did you finish the Hi-Fi wireframes for Beta app design?",
        logo: img1,
        isBirthday: true,
        isRead: false,
        unreadCount: 2,
        messageStatus: "read",
        messages: [
            {
                id: 1,
                sender: "Jennifer",
                content: "Oh, hello! All perfectly. I will check it and get back to you soon.",
                time: "04:45 PM",
                isUnread: false,
                status: "read",
            },
            {
                id: 2,
                sender: "You",
                content: "Yes, hello! All perfectly. I will check it and get back to you soon.",
                time: "04:45 PM",
                isUnread: false,
                status: "read",
            },
        ],
    },
    {
        id: 2,
        name: "Jerry Haffer",
        time: "Today | 05:30 PM",
        verified: true,
        message: "Hey! Did you finish the Hi-Fi wireframes for Beta app design?",
        logo: img1,
        isRead: true,
        unreadCount: 0,
        messageStatus: "delivered",
        messages: [
            {
                id: 1,
                sender: "Jerry",
                content: "Have you seen the latest design updates?",
                time: "03:30 PM",
                isUnread: false,
                status: "delivered",
            },
            {
                id: 2,
                sender: "You",
                content: "Not yet, I'll take a look right away.",
                time: "03:32 PM",
                isUnread: false,
                status: "sent",
            },
        ],
    },
];

export const memberChatListNew = [
    {
        id: 3,
        name: "Group 1",
        time: "Today | 05:30 PM",
        message: "Hey! Did you finish the Hi-Fi wireframes for Beta app design?",
        logo: img2,
        isRead: true,
        unreadCount: 0,
        messageStatus: "read",
        messages: [
            {
                id: 1,
                sender: "Alex",
                content: "When is our next meeting scheduled?",
                time: "02:15 PM",
                isUnread: false,
                status: "read",
            },
            {
                id: 2,
                sender: "You",
                content: "Tomorrow at 10 AM.",
                time: "02:17 PM",
                isUnread: false,
                status: "read",
            },
        ],
    },
    {
        id: 4,
        name: "David Eison",
        time: "Today | 05:30 PM",
        message: "Hey! Did you finish the Hi-Fi wireframes for Beta app design?",
        logo: img2,
        isBirthday: true,
        isRead: false,
        unreadCount: 5,
        messageStatus: "sent",
        messages: [
            {
                id: 1,
                sender: "David",
                content: "Can we discuss the project timeline?",
                time: "01:45 PM",
                isUnread: false,
                status: "sent",
            },
            {
                id: 2,
                sender: "You",
                content: "Sure, I'm available this afternoon.",
                time: "01:50 PM",
                isUnread: false,
                status: "delivered",
            },
        ],
    },
    {
        id: 5,
        name: "Mary Freund",
        time: "Today | 05:30 PM",
        message: "Hey! Did you finish the Hi-Fi wireframes for Beta app design?",
        logo: img1,
        isRead: true,
        unreadCount: 0,
        messageStatus: "delivered",
        messages: [
            {
                id: 1,
                sender: "Mary",
                content: "Did you review the latest feedback?",
                time: "11:20 AM",
                isUnread: false,
                status: "delivered",
            },
            {
                id: 2,
                sender: "You",
                content: "Yes, I've incorporated the changes.",
                time: "11:25 AM",
                isUnread: false,
                status: "read",
            },
        ],
    },
];

export const companyChatListNew = [
    {
        id: 100,
        name: "Fit Chain GmbH",
        time: "Today | 05:30 PM",
        message: "Welcome to Fit Chain GmbH communications",
        logo: img1,
        isRead: false,
        unreadCount: 1,
        messageStatus: "read",
        messages: [
            {
                id: 1,
                sender: "System",
                content: "Welcome to Fit Chain GmbH internal communications.",
                time: "09:00 AM",
                isUnread: false,
                status: "read",
            },
        ],
    },
];