export const PERMISSION_GROUPS = [
    {
      group: "Appointments",
      icon: "CalendarOutlined",
      items: [
        "appointments.view",
        "appointments.create",
        "appointments.edit",
        "appointments.cancel",
        "appointments.manage_contingent",
      ],
    },
    {
      group: "Communication",
      icon: "MailOutlined",
      items: [
        "communication.view",
        "emails.send",
        "chat.member_send",
        "chat.studio_send",
        "broadcasts.send",
        "bulletin_board.view",
        "bulletin_board.posts_create",
        "bulletin_board.posts_edit",
        "bulletin_board.posts_delete",
      ],
    },
    {
      group: "Activity Monitor",
      icon: "FileSearchOutlined",
      items: ["activity_monitor.view", "activity_monitor.take_actions"],
    },
    {
      group: "To-Do & Tags",
      icon: "CheckSquareOutlined",
      items: ["todos.view", "todos.create", "todos.edit", "todos.delete", "tags.manage"],
    },
    {
      group: "Notes",
      icon: "FileTextOutlined",
      items: ["notes.view", "notes.personal_create", "notes.studio_create", "notes.studio_delete"],
    },
    {
      group: "Members",
      icon: "TeamOutlined",
      items: ["members.view", "members.create", "members.edit", "members.history_view", "members.documents_manage"],
    },
    {
      group: "Staff",
      icon: "TeamOutlined",
      items: [
        "staff.view",
        "staff.create",
        "staff.edit",
        "staff.history_view",
        "staff.vacation_calendar_view",
        "staff.planning_view",
        "staff.shifts_manage",
      ],
    },
    {
      group: "Leads",
      icon: "UserAddOutlined",
      items: ["leads.view", "leads.create", "leads.edit", "leads.columns_edit"],
    },
    {
      group: "Contracts",
      icon: "FileProtectOutlined",
      items: [
        "contracts.view",
        "contracts.create",
        "contracts.edit",
        "contracts.cancel",
        "contracts.view_details",
        "contracts.documents_manage",
      ],
    },
    {
      group: "Selling & Products",
      icon: "ShoppingCartOutlined",
      items: ["selling.view", "products.manage", "services.manage", "sales_journal.view", "sales_journal.take_actions"],
    },
    {
      group: "Finances",
      icon: "DollarOutlined",
      items: ["finances.view", "payments.run"],
    },
    {
      group: "Training",
      icon: "ReadOutlined",
      items: ["training.view", "training_plans.create", "training_plans.assign"],
    },
    {
      group: "Analytics",
      icon: "LineChartOutlined",
      items: [
        "analytics.view",
        "analytics.finance_view",
        "analytics.members_view",
        "analytics.leads_view",
        "analytics.appointments_view",
      ],
    },
    {
      group: "Configuration",
      icon: "SettingOutlined",
      items: [
        "profile.edit_own",
        "studio.config_manage",
        "appointments.config_manage",
        "staff.config_manage",
        "leads.sources_manage",
        "contracts.config_manage",
        "documents.config_manage",
        "communication.config_manage",
        "finance.config_manage",
        "appearance.manage",
      ],
    },
  ]