import Avatar from "../../../public/gray-avatar-fotor-20250912192528.png"

export const hardcodedLeads = [
  {
    id: "h1",
    firstName: "John",
    lastName: "Smith", // Changed from 'surname' to 'lastName' for consistency
    surname: "Smith", // Keep for backwards compatibility
    email: "john.smith@example.com",
    phoneNumber: "+1234567890",
    telephoneNumber: "+1234567890", // Added for forms
    trialPeriod: "Trial Period",
    hasTrialTraining: true,
    avatar: Avatar,
    source: "Social Media Ads",
    leadSource: "Social Media Ads", // Added for consistency
    status: "active",
    gender: "male",
    birthday: "1990-05-20",
    about: "Software Engineer",
    details: "Software Engineer interested in strength training and cardio workouts.", // Added
    createdAt: "2025-01-15T10:30:00Z",
    notes: [
      {
        id: 1001,
        status: "interest",
        text: "Interested in personal training sessions, 2x per week would be ideal.",
        isImportant: true,
        startDate: "2025-01-15",
        endDate: "2025-03-15",
        createdAt: "2025-01-15T10:30:00Z",
      },
      {
        id: 1002,
        status: "contact_attempt",
        text: "Reached by phone, trial training appointment scheduled.",
        isImportant: false,
        startDate: "",
        endDate: "",
        createdAt: "2025-01-16T14:20:00Z",
      },
      {
        id: 1003,
        status: "personal_info",
        text: "Works as a software engineer, flexible working hours. Prefers morning training.",
        isImportant: false,
        startDate: "",
        endDate: "",
        createdAt: "2025-01-17T09:15:00Z",
      },
    ],
    specialNote: {
      text: "Interested in personal training sessions twice a week.",
      isImportant: false,
      startDate: "2025-01-15",
      endDate: "2025-03-15",
    },
    columnId: "active",
    company: "Fitness Pro",
    interestedIn: "Premium",
    // Address fields
    street: "123 Main St",
    zipCode: "12345",
    city: "Anytown",
    country: "USA",
    leadId: "LEAD-001",
  },
  {
    id: "h2",
    firstName: "Sarah",
    lastName: "Wilson",
    surname: "Wilson",
    email: "sarah.wilson@example.com",
    phoneNumber: "+1987654321",
    telephoneNumber: "+1987654321",
    trialPeriod: "Trial Period",
    hasTrialTraining: false,
    avatar: Avatar,
    gender: "female",
    source: "Google Ads",
    leadSource: "Google Ads",
    status: "passive",
    birthday: "1988-11-10",
    details: "Interested in group fitness classes and nutrition guidance.",
    createdAt: "2025-01-20T14:45:00Z",
    notes: [
      {
        id: 2001,
        status: "health",
        text: "Has dietary restrictions - needs specialized nutrition plan. Lactose intolerant.",
        isImportant: true,
        startDate: "2025-01-20",
        endDate: "2025-04-20",
        createdAt: "2025-01-20T14:45:00Z",
      },
      {
        id: 2002,
        status: "callback_requested",
        text: "Wants to be called back next week, currently on vacation.",
        isImportant: false,
        startDate: "",
        endDate: "",
        createdAt: "2025-01-21T10:00:00Z",
      },
    ],
    specialNote: {
      text: "Has dietary restrictions - needs specialized nutrition plan.",
      isImportant: false,
      startDate: "2025-01-20",
      endDate: "2025-04-20",
    },
    columnId: "passive",
    company: "Wellness Hub",
    interestedIn: "Basic",
    street: "456 Oak Ave",
    zipCode: "54321",
    city: "Otherville",
    country: "USA",
    leadId: "LEAD-002",
  },
  {
    id: "h3",
    firstName: "Michael",
    lastName: "Brown",
    surname: "Brown",
    email: "michael.brown@example.com",
    phoneNumber: "+1122334455",
    telephoneNumber: "+1122334455",
    trialPeriod: "Trial Period",
    hasTrialTraining: true,
    avatar: Avatar,
    source: "Email Campaign",
    leadSource: "Email Campaign",
    status: "trial",
    gender: "male",
    birthday: "1995-03-01",
    details: "Former athlete looking for high-intensity workouts and strength training.",
    createdAt: "2025-01-25T09:15:00Z",
    notes: [
      {
        id: 3001,
        status: "personal_info",
        text: "Former athlete (track and field), looking for high-intensity workouts and strength training.",
        isImportant: false,
        startDate: "2025-01-25",
        endDate: "2025-02-25",
        createdAt: "2025-01-25T09:15:00Z",
      },
      {
        id: 3002,
        status: "follow_up",
        text: "Call after trial training to get feedback.",
        isImportant: true,
        startDate: "",
        endDate: "",
        createdAt: "2025-01-26T16:30:00Z",
      },
      {
        id: 3003,
        status: "interest",
        text: "Interested in the premium package with personal trainer.",
        isImportant: false,
        startDate: "",
        endDate: "",
        createdAt: "2025-01-27T11:00:00Z",
      },
    ],
    specialNote: {
      text: "Former athlete, looking for high-intensity workouts.",
      isImportant: false,
      startDate: "2025-01-25",
      endDate: "2025-02-25",
    },
    columnId: "trial",
    company: "Gym Central",
    interestedIn: "Bronze",
    street: "789 Pine Ln",
    zipCode: "67890",
    city: "Anycity",
    country: "USA",
    leadId: "LEAD-003",
  },
  {
    id: "h4",
    firstName: "Emma",
    lastName: "Davis",
    surname: "Davis",
    email: "emma.davis@example.com",
    phoneNumber: "+1555666777",
    telephoneNumber: "+1555666777",
    trialPeriod: "Trial Period",
    hasTrialTraining: false,
    avatar: Avatar,
    source: "Website",
    leadSource: "Website",
    status: "uninterested",
    gender: "female",
    birthday: "1992-07-18",
    details: "Interested but not ready to commit. Follow up in 3 months.",
    createdAt: "2025-02-01T11:20:00Z",
    notes: [
      {
        id: 4001,
        status: "objection",
        text: "Price concerns - finds membership too expensive. Maybe offer discount?",
        isImportant: true,
        startDate: "",
        endDate: "",
        createdAt: "2025-02-01T11:20:00Z",
      },
      {
        id: 4002,
        status: "follow_up",
        text: "Contact again in 3 months - not ready to commit right now.",
        isImportant: true,
        startDate: "2025-02-01",
        endDate: "2025-05-01",
        createdAt: "2025-02-01T15:00:00Z",
      },
      {
        id: 4003,
        status: "contact_attempt",
        text: "Tried calling 2x, not reached. SMS sent.",
        isImportant: false,
        startDate: "",
        endDate: "",
        createdAt: "2025-02-03T09:30:00Z",
      },
    ],
    specialNote: {
      text: "Requested follow-up in 3 months - not ready to commit now.",
      isImportant: true,
      startDate: "2025-02-01",
      endDate: "2025-05-01",
    },
    columnId: "uninterested",
    company: "Active Life",
    interestedIn: "Basic",
    street: "101 Elm St",
    zipCode: "11111",
    city: "Smalltown",
    country: "USA",
    leadId: "LEAD-004",
  },
  {
    id: "h5",
    firstName: "Justin",
    lastName: "Test",
    surname: "Test",
    email: "justintest@beispiel.com",
    phoneNumber: "+4915512345678",
    telephoneNumber: "+4915512345678",
    trialPeriod: "Trial Period",
    hasTrialTraining: false,
    avatar: Avatar,
    source: "Website",
    leadSource: "Website",
    status: "missed",
    gender: "male", // Fixed - was "female"
    birthday: "1992-07-18",
    details: "Test lead for development purposes.",
    createdAt: "2025-02-01T11:20:00Z",
    columnId: "missed",
    company: "Test Studio",
    interestedIn: "Basic",
    street: "TeststraÃŸe 123",
    zipCode: "10115",
    city: "Berlin",
    country: "Germany",
    leadId: "LEAD-005",
  },
]

export const memberRelationsLeadNew = {
  h1: {
    family: [
      { name: "Anna Doe", relation: "Mother", id: 101, type: "member" },
      { name: "Peter Doe", relation: "Father", id: 102, type: "lead" },
    ],
    friendship: [{ name: "Max Miller", relation: "Best Friend", id: 201, type: "member" }],
    relationship: [],
    work: [{ name: "Tom Wilson", relation: "Colleague", id: 401, type: "lead" }],
    other: [],
  },
  h2: {
    family: [],
    friendship: [],
    relationship: [{ name: "Marie Smith", relation: "Partner", id: 301, type: "member" }],
    work: [],
    other: [],
  },
  h3: {
    family: [
      { name: "Lisa Brown", relation: "Sister", id: 103, type: "member" },
    ],
    friendship: [
      { name: "David Chen", relation: "Close Friend", id: 202, type: "member" }
    ],
    relationship: [],
    work: [],
    other: [],
  },
  h4: {
    family: [],
    friendship: [],
    relationship: [],
    work: [
      { name: "Robert Johnson", relation: "Business Partner", id: 402, type: "lead" }
    ],
    other: [],
  },
  h5: {
    family: [],
    friendship: [],
    relationship: [],
    work: [],
    other: [],
  },
}

// Sample Trial Appointments for testing
// These will be stored in localStorage when the app initializes
export const sampleTrialAppointments = [
  {
    id: 1001,
    leadId: "h1", // John Smith
    leadName: "John Smith",
    leadEmail: "john.smith@example.com",
    date: "2025-02-15",
    timeSlot: "09:00 - 09:45",
    trialType: "Strength",
    status: "scheduled",
    isTrial: true,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 1002,
    leadId: "h3", // Michael Brown
    leadName: "Michael Brown",
    leadEmail: "michael.brown@example.com",
    date: "2025-02-07",
    timeSlot: "09:00 - 09:30",
    trialType: "Cardio",
    status: "scheduled",
    isTrial: true,
    isCancelled: false,
    isPast: false,
  },
  {
    id: 1003,
    leadId: "h3", // Michael Brown
    leadName: "Michael Brown",
    leadEmail: "michael.brown@example.com",
    date: "2025-02-08",
    timeSlot: "10:00 - 10:45",
    trialType: "Flexibility",
    status: "scheduled",
    isTrial: true,
    isCancelled: false,
    isPast: false,
  },
]

// Available Time Slots for Trial Training Bookings
// Date: 27.09.2025 with 30-minute intervals
export const availableTimeSlots = [
  // Morning slots (8:00 - 12:00)
  { id: "slot1", date: "2025-09-27", time: "08:00", timeSlot: "08:00 - 08:30" },
  { id: "slot2", date: "2025-09-27", time: "08:30", timeSlot: "08:30 - 09:00" },
  { id: "slot3", date: "2025-09-27", time: "09:00", timeSlot: "09:00 - 09:30" },
  { id: "slot4", date: "2025-09-27", time: "09:30", timeSlot: "09:30 - 10:00" },
  { id: "slot5", date: "2025-09-27", time: "10:00", timeSlot: "10:00 - 10:30" },
  { id: "slot6", date: "2025-09-27", time: "10:30", timeSlot: "10:30 - 11:00" },
  { id: "slot7", date: "2025-09-27", time: "11:00", timeSlot: "11:00 - 11:30" },
  { id: "slot8", date: "2025-09-27", time: "11:30", timeSlot: "11:30 - 12:00" },
  
  // Afternoon slots (14:00 - 18:00)
  { id: "slot9", date: "2025-09-27", time: "14:00", timeSlot: "14:00 - 14:30" },
  { id: "slot10", date: "2025-09-27", time: "14:30", timeSlot: "14:30 - 15:00" },
  { id: "slot11", date: "2025-09-27", time: "15:00", timeSlot: "15:00 - 15:30" },
  { id: "slot12", date: "2025-09-27", time: "15:30", timeSlot: "15:30 - 16:00" },
  { id: "slot13", date: "2025-09-27", time: "16:00", timeSlot: "16:00 - 16:30" },
  { id: "slot14", date: "2025-09-27", time: "16:30", timeSlot: "16:30 - 17:00" },
  { id: "slot15", date: "2025-09-27", time: "17:00", timeSlot: "17:00 - 17:30" },
  { id: "slot16", date: "2025-09-27", time: "17:30", timeSlot: "17:30 - 18:00" },
  
  // Evening slots (18:00 - 20:00)
  { id: "slot17", date: "2025-09-27", time: "18:00", timeSlot: "18:00 - 18:30" },
  { id: "slot18", date: "2025-09-27", time: "18:30", timeSlot: "18:30 - 19:00" },
  { id: "slot19", date: "2025-09-27", time: "19:00", timeSlot: "19:00 - 19:30" },
  { id: "slot20", date: "2025-09-27", time: "19:30", timeSlot: "19:30 - 20:00" },
]
