export const membersData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    title: "John Doe",
    email: "john@example.com",
    phone: "+1234567890",
    street: "123 Main St",
    zipCode: "12345",
    city: "New York",
    country: "United States",
    memberNumber: "M001",
    gender: "male",
    image: null,
    reason: "",
    isActive: true,
    isArchived: false,
    memberType: "full",
    note: "Allergic to peanuts",
    noteStartDate: "2023-01-01",
    noteEndDate: "2023-12-31",
    noteImportance: "important",
    dateOfBirth: "1990-05-15",
    about: "Experienced developer with a passion for clean code.",
    joinDate: "2022-03-01",
    contractStart: "2022-03-01",
    contractEnd: "2023-03-01",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-1-1",
        name: "Medical Clearance Certificate.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadDate: "2023-01-15",
        category: "medical",
      },
      {
        id: "doc-1-2",
        name: "Emergency Contact Form.pdf",
        type: "pdf",
        size: "0.8 MB",
        uploadDate: "2023-01-16",
        category: "emergency",
      },
      {
        id: "doc-1-3",
        name: "Fitness Assessment Report.xlsx",
        type: "xlsx",
        size: "1.5 MB",
        uploadDate: "2023-02-01",
        category: "fitness",
      },
      {
        id: "doc-1-4",
        name: "Insurance Policy.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadDate: "2023-01-20",
        category: "legal",
      }
    ],
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    title: "Jane Smith",
    email: "jane@example.com",
    phone: "+1234567891",
    street: "456 Oak St",
    zipCode: "67890",
    city: "Los Angeles",
    country: "United States",
    memberNumber: "M002",
    gender: "female",
    image: null,
    isActive: false,
    reason: "Vacation Leaves",
    isArchived: false,
    memberType: "full",
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1985-08-22",
    about: "Certified PMP with 10 years of experience in IT project management.",
    joinDate: "2021-11-15",
    contractStart: "2021-11-15",
    contractEnd: "2024-04-15",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-2-1",
        name: "Health Declaration.pdf",
        type: "pdf",
        size: "0.7 MB",
        uploadDate: "2021-11-20",
        category: "medical",
      },
      {
        id: "doc-2-2",
        name: "Personal Training Goals.docx",
        type: "docx",
        size: "0.3 MB",
        uploadDate: "2021-12-01",
        category: "fitness",
      },
      {
        id: "doc-2-3",
        name: "Identification Copy.jpg",
        type: "jpg",
        size: "2.8 MB",
        uploadDate: "2021-11-18",
        category: "personal",
      }
    ],
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    title: "Michael Johnson",
    email: "michael@example.com",
    phone: "+1234567892",
    street: "789 Pine St",
    zipCode: "10112",
    city: "Chicago",
    country: "United States",
    memberNumber: "M003",
    image: null,
    isActive: true,
    gender: "male",
    isArchived: false,
    memberType: "full",
    note: "Prefers morning sessions",
    noteStartDate: "2023-03-01",
    noteEndDate: "2023-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1988-11-30",
    about: "Fitness enthusiast and marathon runner.",
    joinDate: "2022-06-15",
    contractStart: "2022-06-15",
    contractEnd: "2023-12-15",
    autoArchiveDate: null,
    documents: [
      {
        id: "doc-3-1",
        name: "Marathon Training Plan.pdf",
        type: "pdf",
        size: "3.2 MB",
        uploadDate: "2022-07-01",
        category: "fitness",
      },
      {
        id: "doc-3-2",
        name: "Injury History Report.docx",
        type: "docx",
        size: "0.6 MB",
        uploadDate: "2022-06-20",
        category: "medical",
      },
    ],
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Williams",
    title: "Sarah Williams",
    email: "sarah.w@example.com",
    phone: "+1234567893",
    street: "321 Elm Ave",
    zipCode: "54321",
    city: "Houston",
    country: "United States",
    memberNumber: "M004",
    gender: "female",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "premium",
    note: "VIP member - priority scheduling",
    noteStartDate: "2024-01-01",
    noteEndDate: "2024-12-31",
    noteImportance: "important",
    dateOfBirth: "1992-03-18",
    about: "Yoga instructor and wellness coach.",
    joinDate: "2023-01-10",
    contractStart: "2023-01-10",
    contractEnd: "2025-01-10",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    title: "David Brown",
    email: "david.brown@example.com",
    phone: "+1234567894",
    street: "555 Maple Dr",
    zipCode: "11223",
    city: "Phoenix",
    country: "United States",
    memberNumber: "M005",
    gender: "male",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "basic",
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1995-07-25",
    about: "Bodybuilding competitor.",
    joinDate: "2024-02-01",
    contractStart: "2024-02-01",
    contractEnd: "2025-02-01",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 6,
    firstName: "Emily",
    lastName: "Davis",
    title: "Emily Davis",
    email: "emily.d@example.com",
    phone: "+1234567895",
    street: "777 Cedar Ln",
    zipCode: "33445",
    city: "Philadelphia",
    country: "United States",
    memberNumber: "M006",
    gender: "female",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "full",
    note: "Recovering from knee surgery",
    noteStartDate: "2024-11-01",
    noteEndDate: "2025-03-01",
    noteImportance: "important",
    dateOfBirth: "1987-12-03",
    about: "Former professional tennis player.",
    joinDate: "2020-05-20",
    contractStart: "2020-05-20",
    contractEnd: "2025-05-20",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Miller",
    title: "Robert Miller",
    email: "robert.m@example.com",
    phone: "+1234567896",
    street: "888 Birch St",
    zipCode: "55667",
    city: "San Antonio",
    country: "United States",
    memberNumber: "M007",
    gender: "male",
    image: null,
    isActive: false,
    reason: "Medical Leave",
    isArchived: false,
    memberType: "full",
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1980-09-14",
    about: "CrossFit enthusiast.",
    joinDate: "2019-08-01",
    contractStart: "2019-08-01",
    contractEnd: "2024-08-01",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 8,
    firstName: "Lisa",
    lastName: "Garcia",
    title: "Lisa Garcia",
    email: "lisa.g@example.com",
    phone: "+1234567897",
    street: "999 Walnut Ave",
    zipCode: "77889",
    city: "San Diego",
    country: "United States",
    memberNumber: "M008",
    gender: "female",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "premium",
    note: "Prefers female trainers",
    noteStartDate: "2024-01-01",
    noteEndDate: "2025-12-31",
    noteImportance: "unimportant",
    dateOfBirth: "1993-04-28",
    about: "Pilates and dance fitness lover.",
    joinDate: "2023-06-15",
    contractStart: "2023-06-15",
    contractEnd: "2025-06-15",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 9,
    firstName: "Thomas",
    lastName: "Anderson",
    title: "Thomas Anderson",
    email: "thomas.a@example.com",
    phone: "+1234567898",
    street: "111 Oak Blvd",
    zipCode: "99001",
    city: "Dallas",
    country: "United States",
    memberNumber: "M009",
    gender: "male",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "basic",
    note: "",
    noteStartDate: "",
    noteEndDate: "",
    noteImportance: "unimportant",
    dateOfBirth: "1998-01-10",
    about: "Swimming and cardio focus.",
    joinDate: "2024-09-01",
    contractStart: "2024-09-01",
    contractEnd: "2025-09-01",
    autoArchiveDate: null,
    documents: [],
  },
  {
    id: 10,
    firstName: "Jennifer",
    lastName: "Martinez",
    title: "Jennifer Martinez",
    email: "jennifer.m@example.com",
    phone: "+1234567899",
    street: "222 Pine Circle",
    zipCode: "12012",
    city: "San Jose",
    country: "United States",
    memberNumber: "M010",
    gender: "female",
    image: null,
    isActive: true,
    isArchived: false,
    memberType: "full",
    note: "Group class regular",
    noteStartDate: "2024-06-01",
    noteEndDate: "2025-06-01",
    noteImportance: "unimportant",
    dateOfBirth: "1991-06-22",
    about: "Spin class enthusiast and weight training beginner.",
    joinDate: "2022-11-01",
    contractStart: "2022-11-01",
    contractEnd: "2025-11-01",
    autoArchiveDate: null,
    documents: [],
  },
]

export const appointmentsMainData = [
  {
    id: 1,
    title: "Initial Consultation",
    name: "John Doe",
    date: "2025-03-15",
    time: "10:00 AM",
    status: "upcoming",
    type: "Consultation",
    memberId: 1,
    specialNote: {
      text: "First time client, needs introduction to equipment",
      isImportant: true,
      startDate: "2025-03-15",
      endDate: "2025-03-20",
    },
  },
  {
    id: 2,
    title: "Follow-up Meeting",
    name: "John Doe",
    date: "2025-03-20",
    time: "2:30 PM",
    status: "upcoming",
    type: "Follow-up",
    memberId: 1,
  },
  {
    id: 3,
    title: "Annual Review",
    name: "Jane Smith",
    date: "2025-04-05",
    time: "11:00 AM",
    status: "upcoming",
    type: "Annual Review",
    memberId: 2,
  },
  {
    id: 4,
    title: "Training Session",
    name: "Michael Johnson",
    date: "2025-03-18",
    time: "9:00 AM",
    status: "upcoming",
    type: "Training",
    memberId: 3,
  },
  {
    id: 5,
    title: "Fitness Assessment",
    name: "Sarah Williams",
    date: "2025-03-22",
    time: "3:00 PM",
    status: "upcoming",
    type: "Assessment",
    memberId: 4,
  },
  {
    id: 6,
    title: "Weekly Training",
    name: "David Brown",
    date: "2025-03-19",
    time: "4:00 PM",
    status: "upcoming",
    type: "Training",
    memberId: 5,
    recurring: {
      frequency: "weekly",
      dayOfWeek: "3",
      startDate: "2025-03-19",
      occurrences: 12,
    },
  },
  {
    id: 7,
    title: "Rehabilitation Session",
    name: "Emily Davis",
    date: "2025-03-17",
    time: "10:30 AM",
    status: "upcoming",
    type: "Consultation",
    memberId: 6,
    specialNote: {
      text: "Focus on knee rehabilitation exercises",
      isImportant: true,
      startDate: "2025-03-17",
      endDate: "2025-04-17",
    },
  },
  {
    id: 8,
    title: "Group Training",
    name: "Lisa Garcia",
    date: "2025-03-21",
    time: "6:00 PM",
    status: "upcoming",
    type: "Training",
    memberId: 8,
  },
  {
    id: 9,
    title: "Consultation",
    name: "Thomas Anderson",
    date: "2025-03-16",
    time: "1:00 PM",
    status: "completed",
    type: "Consultation",
    memberId: 9,
  },
  {
    id: 10,
    title: "Monthly Review",
    name: "Jennifer Martinez",
    date: "2025-03-25",
    time: "11:30 AM",
    status: "upcoming",
    type: "Follow-up",
    memberId: 10,
  },
]

export const appointmentTypeMainData = [
  { name: "Consultation", duration: 30, color: "#3B82F6", slotsRequired: 1 },
  { name: "Follow-up", duration: 45, color: "#22C55E", slotsRequired: 1 },
  { name: "Annual Review", duration: 60, color: "#A855F7", slotsRequired: 2 },
  { name: "Training", duration: 60, color: "#F97316", slotsRequired: 2 },
  { name: "Assessment", duration: 90, color: "#EF4444", slotsRequired: 3 },
  { name: "Group Class", duration: 45, color: "#06B6D4", slotsRequired: 1 },
  { name: "Rehabilitation", duration: 60, color: "#EC4899", slotsRequired: 2 },
]

export const freeAppointmentsMainData = [
  // March 15
  { id: 1, date: "2025-03-15", time: "9:00 AM" },
  { id: 2, date: "2025-03-15", time: "10:00 AM" },
  { id: 3, date: "2025-03-15", time: "11:00 AM" },
  { id: 4, date: "2025-03-15", time: "2:00 PM" },
  { id: 5, date: "2025-03-15", time: "3:00 PM" },
  { id: 6, date: "2025-03-15", time: "4:00 PM" },
  // March 16
  { id: 7, date: "2025-03-16", time: "9:00 AM" },
  { id: 8, date: "2025-03-16", time: "10:30 AM" },
  { id: 9, date: "2025-03-16", time: "1:00 PM" },
  { id: 10, date: "2025-03-16", time: "2:30 PM" },
  // March 17
  { id: 11, date: "2025-03-17", time: "8:00 AM" },
  { id: 12, date: "2025-03-17", time: "9:30 AM" },
  { id: 13, date: "2025-03-17", time: "11:00 AM" },
  { id: 14, date: "2025-03-17", time: "3:00 PM" },
  { id: 15, date: "2025-03-17", time: "5:00 PM" },
  // March 18
  { id: 16, date: "2025-03-18", time: "9:00 AM" },
  { id: 17, date: "2025-03-18", time: "10:00 AM" },
  { id: 18, date: "2025-03-18", time: "2:00 PM" },
  { id: 19, date: "2025-03-18", time: "4:30 PM" },
  // March 19
  { id: 20, date: "2025-03-19", time: "8:30 AM" },
  { id: 21, date: "2025-03-19", time: "10:00 AM" },
  { id: 22, date: "2025-03-19", time: "1:30 PM" },
  { id: 23, date: "2025-03-19", time: "4:00 PM" },
  // March 20
  { id: 24, date: "2025-03-20", time: "9:00 AM" },
  { id: 25, date: "2025-03-20", time: "10:30 AM" },
  { id: 26, date: "2025-03-20", time: "1:30 PM" },
  { id: 27, date: "2025-03-20", time: "2:30 PM" },
  { id: 28, date: "2025-03-20", time: "4:00 PM" },
  // March 21
  { id: 29, date: "2025-03-21", time: "9:00 AM" },
  { id: 30, date: "2025-03-21", time: "11:00 AM" },
  { id: 31, date: "2025-03-21", time: "2:00 PM" },
  { id: 32, date: "2025-03-21", time: "6:00 PM" },
  // March 22
  { id: 33, date: "2025-03-22", time: "10:00 AM" },
  { id: 34, date: "2025-03-22", time: "12:00 PM" },
  { id: 35, date: "2025-03-22", time: "3:00 PM" },
  // March 25
  { id: 36, date: "2025-03-25", time: "9:00 AM" },
  { id: 37, date: "2025-03-25", time: "11:30 AM" },
  { id: 38, date: "2025-03-25", time: "2:00 PM" },
  // April 5
  { id: 39, date: "2025-04-05", time: "9:30 AM" },
  { id: 40, date: "2025-04-05", time: "11:00 AM" },
  { id: 41, date: "2025-04-05", time: "3:00 PM" },
]

export const memberHistoryMainData = {
  1: {
    general: [
      {
        id: 1,
        date: "2025-01-15",
        action: "Email updated",
        details: "Changed from old@email.com to john@example.com",
        user: "Admin",
      },
      {
        id: 2,
        date: "2025-01-10",
        action: "Phone updated",
        details: "Updated phone number",
        user: "Admin",
      },
    ],
    checkins: [
      {
        id: 1,
        date: "2025-01-20T09:30",
        type: "Check-in",
        location: "Main Entrance",
        user: "John Doe",
      },
      {
        id: 2,
        date: "2025-01-20T11:45",
        type: "Check-out",
        location: "Main Entrance",
        user: "John Doe",
      },
    ],
    appointments: [
      {
        id: 1,
        date: "2025-01-18T10:00",
        title: "Personal Training",
        status: "completed",
        trainer: "Mike Johnson",
      },
      {
        id: 2,
        date: "2025-01-15T14:30",
        title: "Consultation",
        status: "completed",
        trainer: "Sarah Wilson",
      },
    ],
    finance: [
      {
        id: 1,
        date: "2025-01-01",
        type: "Payment",
        amount: "$99.99",
        description: "Monthly membership fee",
        status: "completed",
      },
      {
        id: 2,
        date: "2024-12-01",
        type: "Payment",
        amount: "$99.99",
        description: "Monthly membership fee",
        status: "completed",
      },
    ],
    contracts: [
      {
        id: 1,
        date: "2024-03-01",
        action: "Contract signed",
        details: "Initial 12-month membership contract",
        user: "Admin",
      },
      {
        id: 2,
        date: "2024-02-28",
        action: "Contract updated",
        details: "Extended contract duration",
        user: "Admin",
      },
    ],
  },
  2: {
    general: [],
    checkins: [],
    appointments: [],
    finance: [],
    contracts: [],
  },
};


export const availableMembersLeadsMain = [
  // Members from membersData (for easy reference)
  { id: 1, firstName: "John", lastName: "Doe", name: "John Doe", email: "john@example.com", type: "member", image: null },
  { id: 2, firstName: "Jane", lastName: "Smith", name: "Jane Smith", email: "jane@example.com", type: "member", image: null },
  { id: 3, firstName: "Michael", lastName: "Johnson", name: "Michael Johnson", email: "michael@example.com", type: "member", image: null },
  { id: 4, firstName: "Sarah", lastName: "Williams", name: "Sarah Williams", email: "sarah.w@example.com", type: "member", image: null },
  { id: 5, firstName: "David", lastName: "Brown", name: "David Brown", email: "david.brown@example.com", type: "member", image: null },
  { id: 6, firstName: "Emily", lastName: "Davis", name: "Emily Davis", email: "emily.d@example.com", type: "member", image: null },
  { id: 7, firstName: "Robert", lastName: "Miller", name: "Robert Miller", email: "robert.m@example.com", type: "member", image: null },
  { id: 8, firstName: "Lisa", lastName: "Garcia", name: "Lisa Garcia", email: "lisa.g@example.com", type: "member", image: null },
  { id: 9, firstName: "Thomas", lastName: "Anderson", name: "Thomas Anderson", email: "thomas.a@example.com", type: "member", image: null },
  { id: 10, firstName: "Jennifer", lastName: "Martinez", name: "Jennifer Martinez", email: "jennifer.m@example.com", type: "member", image: null },
  // Additional leads
  { id: 101, firstName: "Anna", lastName: "Doe", name: "Anna Doe", email: "anna.d@example.com", type: "lead", image: null },
  { id: 102, firstName: "Peter", lastName: "Doe", name: "Peter Doe", email: "peter.d@example.com", type: "lead", image: null },
  { id: 103, firstName: "Max", lastName: "Wilson", name: "Max Wilson", email: "max.w@example.com", type: "lead", image: null },
  { id: 104, firstName: "Sophie", lastName: "Taylor", name: "Sophie Taylor", email: "sophie.t@example.com", type: "lead", image: null },
  { id: 105, firstName: "James", lastName: "Clark", name: "James Clark", email: "james.c@example.com", type: "lead", image: null },
]

export const relationOptionsMain = {
  family: ["Father", "Mother", "Brother", "Sister", "Uncle", "Aunt", "Cousin", "Grandfather", "Grandmother"],
  friendship: ["Best Friend", "Close Friend", "Friend", "Acquaintance"],
  relationship: ["Partner", "Spouse", "Ex-Partner", "Boyfriend", "Girlfriend"],
  work: ["Colleague", "Boss", "Employee", "Business Partner", "Client"],
  other: ["Neighbor", "Doctor", "Lawyer", "Trainer", "Other"],
}

export const memberRelationsMainData = {
  1: {
    family: [
      { name: "Anna Doe", relation: "Mother", id: 101, type: "member" },
      { name: "Peter Doe", relation: "Father", id: 102, type: "lead" },
      { name: "Lisa Doe", relation: "Sister", id: 103, type: "manual" },
    ],
    friendship: [
      { name: "Max Miller", relation: "Best Friend", id: 201, type: "member" },
    ],
    relationship: [
      { name: "Marie Smith", relation: "Partner", id: 301, type: "member" },
      { name: "Julia Brown", relation: "Ex-Partner", id: 302, type: "manual" },
    ],
    work: [
      { name: "Tom Wilson", relation: "Colleague", id: 401, type: "lead" },
      { name: "Mr. Johnson", relation: "Boss", id: 402, type: "manual" },
    ],
    other: [
      { name: "Mrs. Smith", relation: "Neighbor", id: 501, type: "manual" },
    ],
  },
  2: {
    family: [],
    friendship: [],
    relationship: [],
    work: [],
    other: [],
  },
};

// Billing periods for credits
export const billingPeriodsMainData = [
  { id: 1, name: "January 2025", startDate: "2025-01-01", endDate: "2025-01-31" },
  { id: 2, name: "February 2025", startDate: "2025-02-01", endDate: "2025-02-28" },
  { id: 3, name: "March 2025", startDate: "2025-03-01", endDate: "2025-03-31" },
  { id: 4, name: "April 2025", startDate: "2025-04-01", endDate: "2025-04-30" },
  { id: 5, name: "Q1 2025", startDate: "2025-01-01", endDate: "2025-03-31" },
  { id: 6, name: "Q2 2025", startDate: "2025-04-01", endDate: "2025-06-30" },
]

// Member credits data
export const memberCreditsMainData = {
  1: {
    "January 2025": { used: 3, total: 10 },
    "February 2025": { used: 5, total: 10 },
    "March 2025": { used: 2, total: 10 },
    "Q1 2025": { used: 10, total: 30 },
  },
  2: {
    "January 2025": { used: 8, total: 8 },
    "February 2025": { used: 6, total: 8 },
    "March 2025": { used: 4, total: 8 },
  },
  3: {
    "March 2025": { used: 1, total: 12 },
  },
  4: {
    "March 2025": { used: 0, total: 15 },
  },
  5: {
    "March 2025": { used: 5, total: 8 },
  },
}

// Training plans data
export const trainingPlansMainData = [
  {
    id: 1,
    name: "Beginner Strength",
    description: "Perfect for those new to weight training",
    duration: "8 weeks",
    difficulty: "Beginner",
    category: "Strength",
  },
  {
    id: 2,
    name: "HIIT Cardio Blast",
    description: "High-intensity interval training for maximum calorie burn",
    duration: "6 weeks",
    difficulty: "Intermediate",
    category: "Cardio",
  },
  {
    id: 3,
    name: "Marathon Prep",
    description: "Comprehensive marathon training program",
    duration: "16 weeks",
    difficulty: "Advanced",
    category: "Endurance",
  },
  {
    id: 4,
    name: "Flexibility & Mobility",
    description: "Improve range of motion and prevent injuries",
    duration: "4 weeks",
    difficulty: "Beginner",
    category: "Flexibility",
  },
  {
    id: 5,
    name: "Muscle Building Pro",
    description: "Advanced hypertrophy program for experienced lifters",
    duration: "12 weeks",
    difficulty: "Advanced",
    category: "Strength",
  },
]

// Member assigned training plans
export const memberTrainingPlansMainData = {
  1: [
    { planId: 1, assignedDate: "2025-01-15", status: "active", progress: 65 },
  ],
  2: [
    { planId: 2, assignedDate: "2025-02-01", status: "active", progress: 40 },
    { planId: 4, assignedDate: "2024-12-01", status: "completed", progress: 100 },
  ],
  3: [
    { planId: 3, assignedDate: "2025-01-01", status: "active", progress: 25 },
  ],
  4: [
    { planId: 4, assignedDate: "2025-03-01", status: "active", progress: 10 },
  ],
  5: [
    { planId: 5, assignedDate: "2025-02-15", status: "active", progress: 30 },
  ],
}


export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]
