export const membersData = [
    {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      title: "John Doe",
      email: "john@example.com",
      phone: "+1234567890",
      street: "123 Main St",
      zipCode: "12345",
      city: "New York",
      country: "United States",
      memberNumber: "M001",
      gender: "male",
      image: null,
      reason: "",
      isActive: true,
      isArchived: false,
      memberType: "full",
      note: "Allergic to peanuts",
      noteStartDate: "2023-01-01",
      noteEndDate: "2023-12-31",
      noteImportance: "important",
      dateOfBirth: "1990-05-15",
      about: "Experienced developer with a passion for clean code.",
      joinDate: "2022-03-01",
      contractStart: "2022-03-01",
      contractEnd: "2023-03-01",
      autoArchiveDate: null,
      documents: [
        {
          id: "doc-1-1",
          name: "Medical Clearance Certificate.pdf",
          type: "pdf",
          size: "1.2 MB",
          uploadDate: "2023-01-15",
          category: "medical",
        },
        {
          id: "doc-1-2",
          name: "Emergency Contact Form.pdf",
          type: "pdf",
          size: "0.8 MB",
          uploadDate: "2023-01-16",
          category: "emergency",
        },
        {
          id: "doc-1-3",
          name: "Fitness Assessment Report.xlsx",
          type: "xlsx",
          size: "1.5 MB",
          uploadDate: "2023-02-01",
          category: "fitness",
        },
        {
          id: "doc-1-4",
          name: "Insurance Policy.pdf",
          type: "pdf",
          size: "2.1 MB",
          uploadDate: "2023-01-20",
          category: "legal",
        }
      ],
    },
    {
      id: 2,
      firstName: "Jane",
      lastName: "Smith",
      title: "Jane Smith",
      email: "jane@example.com",
      phone: "+1234567891",
      street: "456 Oak St",
      zipCode: "67890",
      city: "Los Angeles",
      country: "United States",
      memberNumber: "M002",
      gender: "male",
      image: null,
      isActive: false,
      reason: "Vacation Leaves",
      isArchived: false,
      memberType: "full",
      note: "",
      noteStartDate: "",
      noteEndDate: "",
      noteImportance: "unimportant",
      dateOfBirth: "1985-08-22",
      about: "Certified PMP with 10 years of experience in IT project management.",
      joinDate: "2021-11-15",
      contractStart: "2021-11-15",
      contractEnd: "2024-04-15",
      autoArchiveDate: null,
      documents: [
        {
          id: "doc-2-1",
          name: "Health Declaration.pdf",
          type: "pdf",
          size: "0.7 MB",
          uploadDate: "2021-11-20",
          category: "medical",
        },
        {
          id: "doc-2-2",
          name: "Personal Training Goals.docx",
          type: "docx",
          size: "0.3 MB",
          uploadDate: "2021-12-01",
          category: "fitness",
        },
        {
          id: "doc-2-3",
          name: "Identification Copy.jpg",
          type: "jpg",
          size: "2.8 MB",
          uploadDate: "2021-11-18",
          category: "personal",
        }
      ],
    },
    {
      id: 3,
      firstName: "Michael",
      lastName: "Johnson",
      title: "Michael Johnson",
      email: "michael@example.com",
      phone: "+1234567892",
      street: "789 Pine St",
      zipCode: "10112",
      city: "Chicago",
      country: "United States",
      memberNumber: "M003",
      image: null,
      isActive: true,
      gender: "male",
      isArchived: false,
      memberType: "full",
      note: "Prefers morning sessions",
      noteStartDate: "2023-03-01",
      noteEndDate: "2023-12-31",
      noteImportance: "unimportant",
      dateOfBirth: "1988-11-30",
      about: "Fitness enthusiast and marathon runner.",
      joinDate: "2022-06-15",
      contractStart: "2022-06-15",
      contractEnd: "2023-12-15",
      autoArchiveDate: null,
      documents: [
        {
          id: "doc-3-1",
          name: "Marathon Training Plan.pdf",
          type: "pdf",
          size: "3.2 MB",
          uploadDate: "2022-07-01",
          category: "fitness",
        },
        {
          id: "doc-3-2",
          name: "Injury History Report.docx",
          type: "docx",
          size: "0.6 MB",
          uploadDate: "2022-06-20",
          category: "medical",
        },
        {
          id: "doc-3-3",
          name: "Emergency Contacts.txt",
          type: "txt",
          size: "0.1 MB",
          uploadDate: "2022-06-16",
          category: "emergency",
        },
        {
          id: "doc-3-4",
          name: "Nutrition Guidelines.xlsx",
          type: "xlsx",
          size: "1.8 MB",
          uploadDate: "2022-08-15",
          category: "fitness",
        },
        {
          id: "doc-3-5",
          name: "Waiver Form.pdf",
          type: "pdf",
          size: "0.4 MB",
          uploadDate: "2022-06-15",
          category: "legal",
        }
      ],
    },
  ]

  export const appointmentsMainData = [
    {
      id: 1,
      title: "Initial Consultation",
      date: "2025-03-15T10:00",
      status: "upcoming",
      type: "Consultation",
      memberId: 1,
      specialNote: {
        text: "First time client, needs introduction to equipment",
        isImportant: true,
        startDate: "2025-03-15",
        endDate: "2025-03-20",
      },
    },
    {
      id: 2,
      title: "Follow-up Meeting",
      date: "2025-03-20T14:30",
      status: "upcoming",
      type: "Follow-up",
      memberId: 1,
    },
    {
      id: 3,
      title: "Annual Review",
      date: "2025-04-05T11:00",
      status: "upcoming",
      type: "Annual Review",
      memberId: 2,
    },
  ]

  export const appointmentTypeMainData = [
    { name: "Consultation", duration: 30, color: "bg-blue-700" },
    { name: "Follow-up", duration: 45, color: "bg-green-700" },
    { name: "Annual Review", duration: 60, color: "bg-purple-600" },
    { name: "Training", duration: 60, color: "bg-orange-600" },
    { name: "Assessment", duration: 90, color: "bg-red-600" },
  ]

  export const freeAppointmentsMainData = [
    { id: 1, date: "2025-03-15", time: "9:00 AM" },
    { id: 2, date: "2025-03-15", time: "11:00 AM" },
    { id: 3, date: "2025-03-15", time: "2:00 PM" },
    { id: 4, date: "2025-03-20", time: "10:00 AM" },
    { id: 5, date: "2025-03-20", time: "1:30 PM" },
    { id: 6, date: "2025-04-05", time: "9:30 AM" },
    { id: 7, date: "2025-04-05", time: "3:00 PM" },
  ]

  export const memberHistoryMainData = {
    1: {
      general: [
        {
          id: 1,
          date: "2025-01-15",
          action: "Email updated",
          details: "Changed from old@email.com to john@example.com",
          user: "Admin",
        },
        {
          id: 2,
          date: "2025-01-10",
          action: "Phone updated",
          details: "Updated phone number",
          user: "Admin",
        },
      ],
      checkins: [
        {
          id: 1,
          date: "2025-01-20T09:30",
          type: "Check-in",
          location: "Main Entrance",
          user: "John Doe",
        },
        {
          id: 2,
          date: "2025-01-20T11:45",
          type: "Check-out",
          location: "Main Entrance",
          user: "John Doe",
        },
      ],
      appointments: [
        {
          id: 1,
          date: "2025-01-18T10:00",
          title: "Personal Training",
          status: "completed",
          trainer: "Mike Johnson",
        },
        {
          id: 2,
          date: "2025-01-15T14:30",
          title: "Consultation",
          status: "completed",
          trainer: "Sarah Wilson",
        },
      ],
      finance: [
        {
          id: 1,
          date: "2025-01-01",
          type: "Payment",
          amount: "$99.99",
          description: "Monthly membership fee",
          status: "completed",
        },
        {
          id: 2,
          date: "2024-12-01",
          type: "Payment",
          amount: "$99.99",
          description: "Monthly membership fee",
          status: "completed",
        },
      ],
      contracts: [
        {
          id: 1,
          date: "2024-03-01",
          action: "Contract signed",
          details: "Initial 12-month membership contract",
          user: "Admin",
        },
        {
          id: 2,
          date: "2024-02-28",
          action: "Contract updated",
          details: "Extended contract duration",
          user: "Admin",
        },
      ],
    },
    2: {
      general: [],
      checkins: [],
      appointments: [],
      finance: [],
      contracts: [],
    },
  };
  

  export const availableMembersLeadsMain = [
      { id: 101, name: "Anna Doe", type: "member" },
      { id: 102, name: "Peter Doe", type: "lead" },
      { id: 103, name: "Lisa Doe", type: "member" },
      { id: 201, name: "Max Miller", type: "member" },
      { id: 301, name: "Marie Smith", type: "member" },
      { id: 401, name: "Tom Wilson", type: "lead" },
    ]
  
    export const relationOptionsMain = {
      family: ["Father", "Mother", "Brother", "Sister", "Uncle", "Aunt", "Cousin", "Grandfather", "Grandmother"],
      friendship: ["Best Friend", "Close Friend", "Friend", "Acquaintance"],
      relationship: ["Partner", "Spouse", "Ex-Partner", "Boyfriend", "Girlfriend"],
      work: ["Colleague", "Boss", "Employee", "Business Partner", "Client"],
      other: ["Neighbor", "Doctor", "Lawyer", "Trainer", "Other"],
    }

    export const memberRelationsMainData = {
        1: {
          family: [
            { name: "Anna Doe", relation: "Mother", id: 101, type: "member" },
            { name: "Peter Doe", relation: "Father", id: 102, type: "lead" },
            { name: "Lisa Doe", relation: "Sister", id: 103, type: "manual" },
          ],
          friendship: [
            { name: "Max Miller", relation: "Best Friend", id: 201, type: "member" },
          ],
          relationship: [
            { name: "Marie Smith", relation: "Partner", id: 301, type: "member" },
            { name: "Julia Brown", relation: "Ex-Partner", id: 302, type: "manual" },
          ],
          work: [
            { name: "Tom Wilson", relation: "Colleague", id: 401, type: "lead" },
            { name: "Mr. Johnson", relation: "Boss", id: 402, type: "manual" },
          ],
          other: [
            { name: "Mrs. Smith", relation: "Neighbor", id: 501, type: "manual" },
          ],
        },
        2: {
          family: [],
          friendship: [],
          relationship: [],
          work: [],
          other: [],
        },
      };
      