export const productsMainData = [
    {
      id: 1,
      name: "Premium Orange Sneakers",
      brandName: "ORANGEWEAR",
      price: 129.99,
      image: "https://placehold.co/600x400/2563eb/white?text=Premium+Sneakers",
      articalNo: "ORG-001",
      paymentOption: "Card",
      type: "product",
      position: 0,
      link: "https://example.com/product1",
      vatRate: "19",
      vatSelectable: false,
    },
    {
      id: 2,
      name: "Orange Athletic Shoes",
      brandName: "ORANGEFIT",
      price: 189.5,
      image: "https://placehold.co/600x400/2563eb/white?text=Athletic+Shoes",
      articalNo: "ORG-002",
      paymentOption: "Card",
      type: "product",
      position: 1,
      link: "",
      vatRate: "7",
      vatSelectable: true,
    },
  ]

  export const serviceMainData = [
    {
      id: 101,
      name: "Personal Training Session",
      price: 75.0,
      image: "https://placehold.co/600x400/2563eb/white?text=Personal+Training",
      paymentOption: "Card",
      type: "service",
      position: 0,
      link: "https://example.com/training",
      vatRate: "19",
      vatSelectable: false,
    },
    {
      id: 102,
      name: "Nutrition Consultation",
      price: 50.0,
      image: "https://placehold.co/600x400/2563eb/white?text=Nutrition+Advice",
      paymentOption: "Cash",
      type: "service",
      position: 1,
      link: "",
      vatRate: "7",
      vatSelectable: true,
    },
  ]

  export const sellingMainData = [
    {
      id: 1,
      date: "2024-01-15 14:30:22",
      member: "John Doe",
      memberType: "Full Member",
      items: [
        { name: "Premium Orange Sneakers", quantity: 2, price: 129.99, type: "Product" },
        { name: "Personal Training Session", quantity: 1, price: 75.0, type: "Service" },
      ],
      totalAmount: 334.98,
      paymentMethod: "Credit Card",
      soldBy: "John Smith",
      invoiceNumber: "INV-2024-001",
      canCancel: true,
    },
    {
      id: 2,
      date: "2024-01-14 09:15:45",
      member: "No Member",
      memberType: "N/A",
      items: [{ name: "Orange Athletic Shoes", quantity: 1, price: 189.5, type: "Product" }],
      totalAmount: 189.5,
      paymentMethod: "Cash",
      soldBy: "Sarah Johnson",
      invoiceNumber: "INV-2024-002",
      canCancel: false,
    },
    {
      id: 3,
      date: "2024-01-13 16:45:12",
      member: "Jane Smith",
      memberType: "Temporary Member",
      items: [
        { name: "Nutrition Consultation", quantity: 3, price: 50.0, type: "Service" },
        { name: "Premium Orange Sneakers", quantity: 1, price: 129.99, type: "Product" },
      ],
      totalAmount: 279.99,
      paymentMethod: "Debit Card",
      soldBy: "Mike Davis",
      invoiceNumber: "INV-2024-003",
      canCancel: true,
    },
  ]