import Rectangle1 from "../../../public/Rectangle 1.png";
import Avatar from "../../../public/gray-avatar-fotor-20250912192528.png";

export const communicationsData = [
  {
    id: 1,
    name: "John Doe",
    message: "Hey, how's the project going?",
    time: "2 min ago",
    avatar: Rectangle1,
  },
  {
    id: 2,
    name: "Jane Smith",
    message: "Meeting scheduled for tomorrow",
    time: "10 min ago",
    avatar: Rectangle1,
  },
];

export const todosData = [
  {
    id: 1,
    title: "Review project proposal",
    assignee: "Mike Johnson",
  },
  {
    id: 2,
    title: "Update documentation",
    assignee: "Sarah Davis",
  },
];

export const birthdaysData = [
  {
    id: 1,
    name: "Alice Johnson",
    date: "Dec 15, 2024",
    avatar: Avatar,
  },
  {
    id: 2,
    name: "Bob Wilson",
    date: "Dec 20, 2024",
    avatar: Avatar,
  },
];

export const customLinksData = [
  {
    id: 1,
    title: "Google Drive",
    url: "https://drive.google.com",
  },
  {
    id: 2,
    title: "GitHub",
    url: "https://github.com",
  },
];

export const todosTaskData = [
  {
    id: 1,
    title: "Prepare quarterly performance review presentation for the management board meeting on Friday",
    assignees: ["Jack Smith", "Jane Doe"],
    roles: ["Manager"],
    tags: ["Important", "Meeting"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-20",
    dueTime: "09:00",
    reminder: "1 day before",
    repeat: "",
    isPinned: true,
    dragVersion: 0,
    createdAt: "2025-01-10T08:00:00.000Z",
  },
  {
    id: 2,
    title: "Follow up with client regarding contract renewal and discuss new pricing options for the upcoming year",
    assignees: ["Sarah Davis"],
    roles: ["Support"],
    tags: ["Client", "Important"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-18",
    dueTime: "14:30",
    reminder: "30 minutes before",
    repeat: "",
    isPinned: true,
    dragVersion: 0,
    createdAt: "2025-01-12T10:30:00.000Z",
  },
  {
    id: 3,
    title: "Update the employee handbook with new remote work policies and vacation request procedures",
    assignees: ["Mike Johnson", "Alex Miller"],
    roles: ["Admin"],
    tags: ["Work", "Important"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-25",
    dueTime: "17:00",
    reminder: "1 hour before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-08T14:00:00.000Z",
  },
  {
    id: 4,
    title: "Schedule and coordinate team building event for Q1 - book venue, catering, and send calendar invites",
    assignees: ["Jessica Brown"],
    roles: ["Manager"],
    tags: ["Meeting", "Personal"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-22",
    dueTime: "11:00",
    reminder: "15 minutes before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-11T09:00:00.000Z",
  },
  {
    id: 5,
    title: "Review and approve weekly expense reports from all department heads",
    assignees: ["John Wilson"],
    roles: ["Admin"],
    tags: ["Work", "Urgent"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-17",
    dueTime: "16:00",
    reminder: "On time",
    repeat: "Weekly",
    repeatSettings: {
      frequency: "weekly",
      endType: "never",
      endDate: "",
      occurrences: "",
    },
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-06T11:00:00.000Z",
  },
  {
    id: 6,
    title: "Conduct new member orientation session - gym tour, equipment demo, and membership benefits overview",
    assignees: ["Jack Smith"],
    roles: ["Trainer"],
    tags: ["Onboarding", "Client"],
    status: "ongoing",
    category: "member",
    dueDate: "2025-01-19",
    dueTime: "10:00",
    reminder: "5 minutes before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-13T08:30:00.000Z",
  },
  {
    id: 7,
    title: "Send monthly newsletter to all active members with upcoming class schedules and promotions",
    assignees: ["Sarah Davis", "Jessica Brown"],
    roles: ["Support"],
    tags: ["Work", "Client"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-31",
    dueTime: "09:00",
    reminder: "1 day before",
    repeat: "Monthly",
    repeatSettings: {
      frequency: "monthly",
      endType: "onDate",
      endDate: "2025-12-31",
      occurrences: "",
    },
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-05T10:00:00.000Z",
  },
  {
    id: 8,
    title: "Daily equipment inspection and maintenance check - report any issues to facility manager immediately",
    assignees: ["Alex Miller"],
    roles: ["Trainer"],
    tags: ["Work"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-16",
    dueTime: "07:00",
    reminder: "On time",
    repeat: "Daily",
    repeatSettings: {
      frequency: "daily",
      endType: "never",
      endDate: "",
      occurrences: "",
    },
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-01T07:00:00.000Z",
  },
  {
    id: 9,
    title: "Completed initial consultation with potential corporate wellness client - proposal sent for 50 employee memberships",
    assignees: ["Jane Doe", "Mike Johnson"],
    roles: ["Manager"],
    tags: ["Client", "Important"],
    status: "completed",
    category: "staff",
    dueDate: "2025-01-14",
    dueTime: "15:00",
    reminder: "30 minutes before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-07T13:00:00.000Z",
  },
  {
    id: 10,
    title: "Finished updating the member management system with new CRM integration and automated email workflows",
    assignees: ["John Wilson"],
    roles: ["Admin"],
    tags: ["Work", "Study"],
    status: "completed",
    category: "staff",
    dueDate: "2025-01-12",
    dueTime: "18:00",
    reminder: "1 hour before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-03T09:00:00.000Z",
  },
  {
    id: 11,
    title: "Successfully completed staff CPR and First Aid certification renewal training for all trainers",
    assignees: ["Jack Smith", "Alex Miller", "Jessica Brown"],
    roles: ["Trainer"],
    tags: ["Onboarding", "Important"],
    status: "completed",
    category: "staff",
    dueDate: "2025-01-10",
    dueTime: "14:00",
    reminder: "1 day before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2024-12-20T10:00:00.000Z",
  },
  {
    id: 12,
    title: "Vendor meeting cancelled due to scheduling conflict - waiting for vendor to propose new dates for equipment demo",
    assignees: ["Mike Johnson"],
    roles: ["Manager"],
    tags: ["Meeting"],
    status: "canceled",
    category: "staff",
    dueDate: "2025-01-15",
    dueTime: "10:00",
    reminder: "15 minutes before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-08T11:00:00.000Z",
  },
  {
    id: 13,
    title: "Marketing campaign postponed indefinitely - budget reallocated to equipment upgrades per management decision",
    assignees: ["Sarah Davis"],
    roles: ["Support"],
    tags: ["Work", "Personal"],
    status: "canceled",
    category: "staff",
    dueDate: "2025-01-20",
    dueTime: "09:00",
    reminder: "1 hour before",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-09T14:00:00.000Z",
  },
  {
    id: 14,
    title: "Research and compile comparison report on competitor pricing and membership packages in the local market",
    assignees: ["Jane Doe"],
    roles: ["Manager"],
    tags: ["Study", "Work"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-01-28",
    dueTime: "12:00",
    reminder: "Custom",
    customReminderValue: "2",
    customReminderUnit: "Hours",
    repeat: "",
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-14T08:00:00.000Z",
  },
  {
    id: 15,
    title: "Prepare and submit monthly financial report to accounting department including all revenue streams and expenses",
    assignees: ["John Wilson", "Jessica Brown"],
    roles: ["Admin"],
    tags: ["Important", "Work"],
    status: "ongoing",
    category: "staff",
    dueDate: "2025-02-01",
    dueTime: "17:00",
    reminder: "1 day before",
    repeat: "Monthly",
    repeatSettings: {
      frequency: "monthly",
      endType: "after",
      endDate: "",
      occurrences: 12,
    },
    isPinned: false,
    dragVersion: 0,
    createdAt: "2025-01-02T09:00:00.000Z",
  },
];

export const configuredTagsData = [
  { id: 1, name: "Important", color: "#D32F2F" },   // Dark Red
  { id: 2, name: "Urgent", color: "#F57C00" },      // Dark Orange
  { id: 3, name: "Meeting", color: "#7B1FA2" },     // Dark Purple
  { id: 4, name: "Client", color: "#1565C0" },      // Dark Blue
  { id: 5, name: "Onboarding", color: "#512DA8" },  // Dark Indigo
  { id: 6, name: "Personal", color: "#C2185B" },    // Dark Pink
  { id: 7, name: "Work", color: "#2E7D32" },        // Dark Green
  { id: 8, name: "Study", color: "#FF8F00" },       // Dark Amber
];


export const availableAssigneesData = [
  { id: 1, firstName: "Jack", lastName: "Smith" },
  { id: 2, firstName: "Jane", lastName: "Doe" },
  { id: 3, firstName: "John", lastName: "Wilson" },
  { id: 4, firstName: "Jessica", lastName: "Brown" },
  { id: 5, firstName: "Mike", lastName: "Johnson" },
  { id: 6, firstName: "Sarah", lastName: "Davis" },
  { id: 7, firstName: "Alex", lastName: "Miller" },
];
