import { Calendar, FileText, MailX, MessageSquare } from "lucide-react"
import { MdOutlineHolidayVillage } from "react-icons/md"

export const activitiesData = [
    {
      id: 1,
      type: "vacation",
      title: "Vacation Request - Sarah Wilson",
      description: "Requesting 5 days off from March 15-19, 2025 for family vacation",
      timestamp: "2025-01-09T14:30:00",
      status: "pending",
      actionRequired: true,
      isArchived: false,
      details: {
        employee: "Sarah Wilson",
        department: "Training",
        dates: "March 15-19, 2025",
        days: 5,
        reason: "Family vacation",
        coverage: "Mike Johnson (confirmed)",
        submittedAt: "2025-01-09T14:30:00",
      },
    },
    {
      id: 2,
      type: "email",
      title: "Failed Email Delivery - Member Notifications",
      description: "5 appointment reminder emails failed to send due to invalid email addresses",
      timestamp: "2025-01-09T13:45:00",
      status: "failed",
      actionRequired: true,
      isArchived: false,
      details: {
        failedEmails: [
          { email: "old.email@example.com", member: "John Doe", reason: "Invalid email address" },
          { email: "bounced@domain.com", member: "Jane Smith", reason: "Mailbox full" },
          { email: "invalid@test", member: "Bob Wilson", reason: "Invalid format" },
        ],
        emailType: "Appointment Reminders",
        attemptedAt: "2025-01-09T13:45:00",
      },
    },
    {
      id: 3,
      type: "contract",
      title: "Contract Expiring Soon - 3 Members",
      description: "3 member contracts are expiring within the next 30 days",
      timestamp: "2025-01-09T12:00:00",
      status: "warning",
      actionRequired: true,
      isArchived: false,
      details: {
        expiringContracts: [
          { member: "Yolanda Martinez", expiryDate: "2025-02-01", daysLeft: 23 },
          { member: "Denis Johnson", expiryDate: "2025-02-05", daysLeft: 27 },
          { member: "Nicole Smith", expiryDate: "2025-02-08", daysLeft: 30 },
        ],
      },
    },
    {
      id: 4,
      type: "appointment",
      title: "New Appointment Request - Trial Training",
      description: "New trial training request from potential member Lisa Anderson",
      timestamp: "2025-01-09T11:15:00",
      status: "pending",
      actionRequired: true,
      isArchived: false,
      details: {
        requestType: "Trial Training",
        name: "Lisa Anderson",
        email: "lisa.anderson@email.com",
        phone: "+1234567890",
        preferredDate: "2025-01-15",
        preferredTime: "10:00 AM",
        interests: ["Strength Training", "Cardio"],
        source: "Website Contact Form",
      },
    },
    {
      id: 6,
      type: "system",
      title: "System Backup Completed",
      description: "Daily system backup completed successfully at 3:00 AM",
      timestamp: "2025-01-09T03:00:00",
      status: "completed",
      actionRequired: false,
      isArchived: false,
      details: {
        backupSize: "2.4 GB",
        duration: "45 minutes",
        location: "Cloud Storage",
        nextBackup: "2025-01-10T03:00:00",
      },
    },
    {
      id: 8,
      type: "communication",
      title: "Newsletter Campaign Sent",
      description: "Monthly newsletter sent to 1,247 subscribers with 94% delivery rate",
      timestamp: "2025-01-09T08:00:00",
      status: "completed",
      actionRequired: false,
      isArchived: false,
      details: {
        campaign: "January 2025 Newsletter",
        totalRecipients: 1247,
        delivered: 1172,
        opened: 456,
        clicked: 89,
        bounced: 75,
      },
    },
    {
      id: 9,
      type: "vacation",
      title: "Vacation Request - Mike Johnson",
      description: "Requesting 3 days off for medical appointment",
      timestamp: "2025-01-08T16:20:00",
      status: "pending",
      actionRequired: true,
      isArchived: false,
      details: {
        employee: "Mike Johnson",
        department: "Personal Training",
        dates: "January 20-22, 2025",
        days: 3,
        reason: "Medical appointment",
        coverage: "Sarah Wilson (pending confirmation)",
        submittedAt: "2025-01-08T16:20:00",
      },
    },
    {
      id: 10,
      type: "appointment",
      title: "Appointment Cancellation - Last Minute",
      description: "Member cancelled appointment 30 minutes before scheduled time",
      timestamp: "2025-01-08T14:30:00",
      status: "cancelled",
      actionRequired: true,
      isArchived: false,
      details: {
        member: "Jennifer Wilson",
        appointmentType: "Personal Training",
        scheduledTime: "2025-01-08T15:00:00",
        cancelledAt: "2025-01-08T14:30:00",
        reason: "Emergency",
        trainer: "Alex Rodriguez",
        rescheduleRequested: true,
      },
    },
  ]


  export const  activityTypes = {
      vacation: {
        name: "Vacation Requests",
        icon: MdOutlineHolidayVillage,
        color: "bg-blue-600",
        textColor: "text-blue-400",
      },
      email: { name: "Email Issues", icon: MailX, color: "bg-red-600", textColor: "text-red-400" },
      contract: { name: "Contract Expiring", icon: FileText, color: "bg-yellow-600", textColor: "text-yellow-400" },
      appointment: { name: "Appointment Requests", icon: Calendar, color: "bg-green-600", textColor: "text-green-400" },
      communication: {
        name: "Communications",
        icon: MessageSquare,
        color: "bg-indigo-600",
        textColor: "text-indigo-400",
      },
    }