// Bulletin Board Default Data
// This file contains initial/dummy data for the bulletin board
// Replace with API calls when backend is ready

export const defaultTags = [
  { id: 1, name: "Important", color: "#ef4444" },
  { id: 2, name: "Info", color: "#3b82f6" },
  { id: 3, name: "Event", color: "#8b5cf6" },
  { id: 4, name: "Lost Property", color: "#f59e0b" },
]

export const defaultPosts = [
  {
    id: 1,
    title: "Welcome to the Bulletin Board",
    content: "<p>This is where important announcements and information will be shared with team members and staff.</p><p><strong>Key updates:</strong></p><ul><li>New scheduling system rolling out next week</li><li>Updated safety protocols</li></ul>",
    visibility: "Members",
    status: "Active",
    author: "Admin",
    createdAt: Date.now() - 86400000 * 2,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop",
    tags: [],
    schedule: null,
  },
  {
    id: 2,
    title: "Summer Fitness Challenge Starting Soon",
    content: "<p>Get ready for our annual Summer Fitness Challenge!</p><p><strong>What to expect:</strong></p><ul><li>6-week program</li><li>Weekly challenges</li><li>Great prizes for winners</li></ul><p>Registration opens on the start date.</p>",
    visibility: "Members",
    status: "Scheduled",
    author: "Fitness Team",
    createdAt: Date.now() - 86400000,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&h=450&fit=crop",
    tags: [3],
    schedule: {
      type: 'scheduled',
      startDate: new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0],
      startTime: '09:00',
      hasEndDate: true,
      endDate: new Date(Date.now() + 86400000 * 60).toISOString().split('T')[0],
      endTime: '18:00',
    },
  },
  {
    id: 3,
    title: "Found: Keychain with Gym Logo",
    content: "<p>A keychain with a gym logo and 3 keys was found near the lockers yesterday.</p>",
    visibility: "Members",
    status: "Active",
    author: "Front Desk",
    createdAt: Date.now() - 86400000,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&h=450&fit=crop",
    tags: [4],
    schedule: null,
  },
  {
    id: 4,
    title: "Quick Update",
    content: "<p>Meeting at 3 PM today.</p>",
    visibility: "Staff",
    status: "Active",
    author: "Manager",
    createdAt: Date.now() - 86400000,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=450&fit=crop",
    tags: [1],
    schedule: null,
  },
  {
    id: 5,
    title: "New Equipment Arriving Next Month",
    content: "<p>We're excited to announce that new cardio equipment will be arriving next month!</p>",
    visibility: "Members",
    status: "Scheduled",
    author: "Management",
    createdAt: Date.now() - 86400000 * 2,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1517960413843-0aee8e2b3285?w=800&h=450&fit=crop",
    tags: [2],
    schedule: {
      type: 'scheduled',
      startDate: new Date(Date.now() + 86400000 * 14).toISOString().split('T')[0],
      startTime: '10:00',
      hasEndDate: false,
      endDate: '',
      endTime: '',
    },
  },
  {
    id: 6,
    title: "Holiday Schedule Update",
    content: "<p>Please note the updated holiday schedule for the upcoming season.</p>",
    visibility: "Members",
    status: "Inactive",
    author: "HR",
    createdAt: Date.now() - 86400000 * 5,
    createdBy: "current-user",
    image: "https://images.unsplash.com/photo-1485217988980-11786ced9454?w=800&h=450&fit=crop",
    tags: [3],
    schedule: null,
  },
  {
    id: 7,
    title: "Staff Training Session",
    content: "<p>Mandatory training session scheduled for all staff members next Monday.</p>",
    visibility: "Staff",
    status: "Inactive",
    author: "Training Dept",
    createdAt: Date.now() - 86400000 * 7,
    createdBy: "other-user",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=450&fit=crop",
    tags: [1, 2],
    schedule: null,
  },
]

// NOTE: Media Library data (mediaLibraryFolders, mediaLibraryDesigns) has been moved to
// the shared file: ../../utils/studio-states/media-library-picker-modal-state.js
// Import from there if needed.
